### ISSUE TITLE
Visualize output of model

### ISSUE THREAD

**Issue by idontlikelongname** [HuangJunJie2017/BEVDet#10]
Thanks for your great works.

I want to draw 3D detection in multi camera images, or in the BEV format. 
I want to know any scripts meet my requirements.
I used test.py but failed with errors.

**Comment by idontlikelongname** [comment]
sorry for bother you again. I plots lidar points and output gt boxes in BEV image. but the results are weird.
I used pretrained model which download from https://drive.google.com/file/d/10innSxqN7NgbktrlfPjWjE7gz-xpbJO_/view.
![Screenshot from 2022-06-06 21-16-58](https://user-images.githubusercontent.com/7677343/172168163-40b1d594-9fdc-4914-b4e1-0e9cf1dae7a6.png)

**Comment by HuangJunJie2017** [comment]
I have never tried the '--show' function in tools/test.py before. And now, I encounter some problem in using open3d. We will check this and add guideline for visualization recently.  I suggest you take the visualized result of Centerpoint as a reference~

**Comment by HuangJunJie2017** [comment]
@idontlikelongname hi, it seems ok for me to use --show. 
Note: I set the thread to 0.5 to only maintain the predictions with a relatively high detection score.  The threshold is defined in line-488 in https://github.com/HuangJunJie2017/BEVDet/tree/master/mmdet3d/models/detectors/mvx_two_stage.py
![image](https://user-images.githubusercontent.com/31001081/172349108-6b3612fe-9a06-40ff-8324-98ffb1e9a130.png)

**Comment by idontlikelongname** [comment]
thanks for your reply. I will try it. maybe the score thresh is key points to this issue.

**Comment by Jumponthemoon** [comment]
> sorry for bother you again. I plots lidar points and output gt boxes in BEV image. but the results are weird. I used pretrained model which download from https://drive.google.com/file/d/10innSxqN7NgbktrlfPjWjE7gz-xpbJO_/view. ![Screenshot from 2022-06-06 21-16-58](https://user-images.githubusercontent.com/7677343/172168163-40b1d594-9fdc-4914-b4e1-0e9cf1dae7a6.png)

@idontlikelongname how ot get the visualization like this?
