### ISSUE TITLE
cannot import name 'bev_pool_v2_ext' from 'mmdet3d.ops.bev_pool_v2' 

### ISSUE THREAD

**Issue by Jinrong-Qin** [HuangJunJie2017/BEVDet#100]
I did not find this file in the relevant path.
Could you tell me how to solve this problem？

**Comment by HuangJunJie2017** [comment]
@Aqin2386592438 
cd BEVDet && pip install  -v -e .

**Comment by Jinrong-Qin** [comment]
It cannot be compiled and always has path problems：
AssertionError: Egg-link /nexenta/fae-team/jrqin/project/BEVDet/mmdetection3d does not match installed location of mmdet3d (at /nexenta/fae-team/jrqin/project/BEVDet/)

**Comment by Jinrong-Qin** [comment]
> @Aqin2386592438 cd BEVDet && pip install -v -e .

**Comment by HuangJunJie2017** [comment]
@Aqin2386592438 why you have 'mmdetection3d' in the BEVDet dir?

**Comment by Jinrong-Qin** [comment]
> @Aqin2386592438 why you have 'mmdetection3d' in the BEVDet dir?

just only need to download the BEVDet project and compile it？Should I install mmdetection3d in another folder？I cannot be compiled it after getting_started.md

**Comment by HuangJunJie2017** [comment]
@Aqin2386592438 have you seen this instruction 'installing BEVDet as mmdetection3d'?

**Comment by chaijiajie** [comment]
> @Aqin2386592438 have you seen this instruction 'installing BEVDet as mmdetection3d'?

cannot find this instruction...

**Comment by HuangJunJie2017** [comment]
@chaijiajie here https://github.com/HuangJunJie2017/BEVDet#installation-and-data-preparation
