### ISSUE TITLE
About the implementation of BEVDepth

### ISSUE THREAD

**Issue by toyot-li** [HuangJunJie2017/BEVDet#101]
**Describe the feature**

**Motivation**
@HuangJunJie2017 Thanks for your work. Would you add an implementation of BEVDepth (rather than BEVDepth4D, temporal version)?

**Comment by yukaizhou** [comment]
借楼确认个问题哈，谢谢了。@HuangJunJie2017 感谢great work。在看代码时，发现BEVDet_dev2/configs/bevdet/bevdet4d-r50-depth-cbgs.py在预测速度时，并没有使用预测偏移量替代预测速度？期待您的回复。
