### ISSUE TITLE
Difference between the .pkl files created by create_data_bevdet.py and create_data.py in BEVDet-dev2.0

### ISSUE THREAD

**Issue by zwei-lin** [HuangJunJie2017/BEVDet#103]
Hi,
    Thanks for the great works!
    I find BEVDet-dev2.0 needs to create an additional pkl file for bevdet, which is missing in the version1.0. What is the difference between the .pkl files created by create_data_bevdet.py and create_data.py? Why do we need the additional pkl file?

**Comment by HuangJunJie2017** [comment]
@zwei-lin you can figure out this through the code diff~
