### ISSUE TITLE
Question about mAP=0

### ISSUE THREAD

**Issue by Haotian0717** [HuangJunJie2017/BEVDet#105]
Hi Junjie, I downloaded nuScense Mini Dataset. And I used your create_data_bevdet.py to get .pkl. Then, I just used train.py to train the data. All the settings are default except I changed the batch_size=1. But after training, it shows that mAP=0 and other metrics are abnormal. Could you please give me some help?
`Evaluating bboxes of pts_bbox
mAP: 0.0000                                                                                                                                                                                                
mATE: 1.0000
mASE: 1.0000
mAOE: 1.0000
mAVE: 1.0000
mAAE: 1.0000
NDS: 0.0000
Eval time: 1.3s

Per-class results:
Object Class	AP	ATE	ASE	AOE	AVE	AAE
car	0.000	1.000	1.000	1.000	1.000	1.000
truck	0.000	1.000	1.000	1.000	1.000	1.000
bus	0.000	1.000	1.000	1.000	1.000	1.000
trailer	0.000	1.000	1.000	1.000	1.000	1.000
construction_vehicle	0.000	1.000	1.000	1.000	1.000	1.000
pedestrian	0.000	1.000	1.000	1.000	1.000	1.000
motorcycle	0.000	1.000	1.000	1.000	1.000	1.000
bicycle	0.000	1.000	1.000	1.000	1.000	1.000
traffic_cone	0.000	1.000	1.000	nan	nan	nan
barrier	0.000	1.000	1.000	1.000	nan	nan
2022-12-06 09:52:41,445 - mmdet - INFO - Exp name: bevdet-r50.py
`

**Comment by HuangJunJie2017** [comment]
@Haotian0717 try not to use mini dataset? i have no experience about that.

**Comment by Haotian0717** [comment]
I did not use pre-trained weight when I try to train the model,which leads to 0 mAP.

**Comment by alpacaduby** [comment]
My settings are almost the same as yours and I met the same problem,how do you solve this problem eventually?My maximun batch size is 6 due to device limitation,and I can only use a split Nuscenes dataset  that is just 10% as large as the full set.
