### ISSUE TITLE
Temporal Fusion in the new Dev2.0 Branch

### ISSUE THREAD

**Issue by zw615** [HuangJunJie2017/BEVDet#107]
Hi, I am reading the new code in dev2.0 branch. It seems to me that the 'the long term temporal fusion as SOLOFusion.' is really implemented by concatenating the features extracted from the previous 1-9 key frames, right? So there is no high-resolution, shot-term temporal fusion as SOLOFusion? 

In this sense, it seems to the the difference between this dev2.0 implementation and the previous master branch implementation, is that 1) it uses more historic frames; 2) it only chooses key frames as historic frames; 3) it doesn't use random temporal augmentation as before. Is my understanding correct? It is really amazing to see that these small changes lead to hugh performance boost. I wonder if you have tried them on larger models (e.g. VovNet-99 or ConvNeXT-Base)?

Thanks a lot!

**Comment by zw615** [comment]
Also, I notice that in the dev2.0 branch, the model predicts velocity, instead of distance, as in previous master branch. I wonder how does this factor affect peroformance?

**Comment by HuangJunJie2017** [comment]
Haven’t，dev2.0 is deployment oriented
velocity is better for multiple previous frames
