### ISSUE TITLE
Question about the inference speed.

### ISSUE THREAD

**Issue by exiawsh** [HuangJunJie2017/BEVDet#11]
Hello, thanks for the great work!
I have found that the inference speed report in bevdet and bevdet4d seems different.
The inference speed in bevdet(704*256) is about 7-8 fps, and in bevdet4d  is 15.6 fps, what caused the inconsistency?
You used Bacthsize 4 inference speed or Bachsize 1?

**Comment by HuangJunJie2017** [comment]
15.6fps is an idea inference speed. It needs the acceleration described in the paper. We will support the acceleration recently.
