### ISSUE TITLE
About the new nuScenes Camera-only SOTA results

### ISSUE THREAD

**Issue by zw615** [HuangJunJie2017/BEVDet#110]
Hi, based on your new post on [zhihu](https://zhuanlan.zhihu.com/p/593558337?utm_source=wechat_session&utm_medium=social&utm_oi=54787974365184), you have achieved new SOTA result on nuScenes test set with:

1. SwinTranformer-Base
2. 900x1600 resolution
3. Future frame fusion
4. Multi-scale test

I wonder if you could release the config file for this new result? More specifically, I wonder how did you implement future frame fusion and multi-scale test? Shouldn't using future frame fusion be unrealistic, as in the real world future information is not accessible? Also, what's your setup for multi-scale test?

Thanks a lot!

**Comment by zw615** [comment]
And by the way, the ema checkpoint is used for evaluation, or the original non-ema checkpoint? If ema is used, how did you set init_updates in MEGVIIEMAHook?

**Comment by HuangJunJie2017** [comment]
So far, the details of the submitted results are still kept private.
