### ISSUE TITLE
error for visualize the predicted result.

### ISSUE THREAD

**Issue by TommyAnqi** [HuangJunJie2017/BEVDet#113]
Hi,
when I test the code on branch dev2.0 by running the following command:
python tools/test.py configs/bevdet/bevdet-r50-cbgs.py ./weights/bevdet-r50-cbgs.pth --show --show-dir ./ret/
TypeError: show_results() got an unexpected keyword argument 'show'
I used the mmdet3d in the repo instead of official version.... can you give some tips on it

**Comment by zuojiaqi0312** [comment]
when i visualize result, first using test.py to get results.json file. then using vis.py to get a video. Maybe help...

**Comment by TommyAnqi** [comment]
> when i visualize result, first using test.py to get results.json file. then using vis.py to get a video. Maybe help...

thanks, it works well...

**Comment by WYYAHYT** [comment]
You can remove arguments `show `and `score_thr ` of func `model.module.show_results()` in `mmdet3d/apis/test.py`, then `points.obj` and `pred.obj` will be generated.
