### ISSUE TITLE
AssertionError: bev_pool_v2 is not in the plugin list of tensorrt

### ISSUE THREAD

**Issue by Han-code0819** [HuangJunJie2017/BEVDet#114]
Hi, I have already installed mmdeploy fromhttps://github.com/HuangJunJie2017/mmdeploy.git, but there is an error when I used the command: python tools/convert_bevdet_to_TRT.py $config $checkpoint $work_dir --fuse-conv-bn --fp16
Could you please give me some instructions? Thank you.

2022-12-28 04:21:28,519 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /opt/conda/lib/python3.8/site-packages/mmdeploy/lib/libmmdeploy_tensorrt_ops.so

Traceback (most recent call last):
  File "tools/convert_bevdet_to_TRT.py", line 177, in <module>
    main()
  File "tools/convert_bevdet_to_TRT.py", line 58, in main
    assert 'bev_pool_v2' in get_plugin_names(), \

AssertionError: bev_pool_v2 is not in the plugin list of tensorrt, please install mmdeploy from https://github.com/HuangJunJie2017/mmdeploy.git

**Comment by HuangJunJie2017** [comment]
@Han-code0819 
print(get_plugin_names()) to see if 'bev_pool_v2' in get_plugin_names()?
if not, you haven't installed mmdeploy from https://github.com/HuangJunJie2017/mmdeploy.git properly.

**Comment by Han-code0819** [comment]
> @Han-code0819 print(get_plugin_names()) to see if 'bev_pool_v2' in get_plugin_names()? if not, you haven't installed mmdeploy from https://github.com/HuangJunJie2017/mmdeploy.git properly.

Thank you, and for now I have created .onnx and .engine, but there are still several questions:

1. The Error is : "/opt/conda/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py:401: UserWarning: DeprecationWarning: pretrai is deprecated, please use "init_cfg" instead", do I need to modify something or the Code will modify the warning by itself?

2. "WARNING: The shape inference of mmdeploy::bev_pool_v2 type is missing, so it may result in wrong shape inference for  exported graph. Please consider adding it in symbolic function." I cannot find the specidied mistake location, and what is the "symbolic function" refer to? Is it important to the final result ("ONNX Model Correct" is showed after that warning)?

3. I just find the "--fp16" parameter in the Code, can it generate other type of data (like fp32, int8 and so on)?

**Comment by HuangJunJie2017** [comment]
1. warning is not error and have no impact on the result
2. the same as 1
3. by default without '--fp16', it converts models in fp32 mode, int8 is not supported in this repo now. You can refer to mmdeploy for an example.

**Comment by debug851** [comment]
> 
I met the same problem as you. How did you solve it? Than u

**Comment by debug851** [comment]
> 嗨，我已经安装了 mmdeploy fromhttps://github.com/HuangJunJie2017/mmdeploy.git，但是当我使用命令时出现错误：python tools/convert_bevdet_to_TRT.py $config $checkpoint $work_dir --fuse-conv-bn --fp16 你能给我一些说明吗？谢谢。
> 
> 2022-12-28 04：21：28，519 - mmdeploy - 信息 - 成功从 /opt/conda/lib/python3.8/site-packages/mmdeploy/lib/libmmdeploy_tensorrt_ops.so 加载张量插件
> 
> 回溯（最近一次调用）：文件 “tools/convert_bevdet_to_TRT.py”，第 177 行，在 main（） 中 文件 “tools/convert_bevdet_to_TRT.py”，第 58 行，在 get_plugin_names（） 中的主断言中 'bev_pool_v2' 中，\
> 
> 断言错误：bev_pool_v2不在 tensorrt 的插件列表中，请从 https://github.com/HuangJunJie2017/mmdeploy.git 安装 mmdeploy

@Han-code0819 
I met the same problem as you. How did you solve it? Than u

**Comment by Han-code0819** [comment]
> 
If Readme.md file cannot support you to link ops with mmdeploy, using Dockerfile to do it. (if docker build -t xxx command cannot run successfully, execuate the command line by line manually)
