### ISSUE TITLE
TensorRT conversion error (bevdet4d-r50-depth-cbgs.py)

### ISSUE THREAD

**Issue by myteen2** [HuangJunJie2017/BEVDet#119]
**Describe the bug**
I set up the environment by building docker image with Docker file (https://github.com/HuangJunJie2017/BEVDet/blob/dev2.0/docker/Dockerfile). 
Everything looks like going well, except for the convert to trt. 
Model training is going on without any problem. 

The execution of tools/convert_bevdet_to_TRT.py outputs KeyError: 'BEVDepth4DTRT is not in the models registry'

**Reproduction**

1. What command or script did you run?

$ python tools/convert_bevdet_to_TRT.py configs/bevdet/bevdet4d-r50-depth-cbgs.py work_dirs/bevdet4d-r50-depth-cbgs/epoch_15.pth work_dirs/bevdet4d-r50-depth-cbgs --fuse-conv-bn --fp16

2. Did you make any modifications on the code or config? Did you understand what you have modified?
No, not at all

3. What dataset did you use?
nuScenes 

**Environment**

1. Please run `python mmdet3d/utils/collect_env.py` to collect necessary environment information and paste it here.

sys.platform: linux
Python: 3.8.15 (default, Nov 24 2022, 15:19:38) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3,4,5,6,7: NVIDIA
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 11.7, V11.7.99
GCC: gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,

TorchVision: 0.11.0
OpenCV: 4.7.0
MMCV: 1.5.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.25.1
MMSegmentation: 0.25.0
MMDetection3D: 1.0.0rc4+90369c3
spconv2.0: False

3. You may add addition that may be helpful for locating the problem, such as
   - How you installed PyTorch \[e.g., pip, conda, source\]
   - Dockerfile provided in https://github.com/HuangJunJie2017/mmdeploy/blob/master/docker/GPU/Dockerfile
   - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

2023-01-06 07:36:31,736 - mmdeploy - INFO - Successfully loaded tensorrt plugins from /root/workspace/mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
Traceback (most recent call last):
  File "tools/convert_bevdet_to_TRT.py", line 174, in <module>
    main()
  File "tools/convert_bevdet_to_TRT.py", line 97, in main
    model = build_model(cfg.model, test_cfg=cfg.get('test_cfg'))
  File "/root/workspace/BEVDet/mmdet3d/models/builder.py", line 122, in build_model
    return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
  File "/root/workspace/BEVDet/mmdet3d/models/builder.py", line 95, in build_detector
    return MMDET_DETECTORS.build(
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 237, in build
    return self.build_func(*args, **kwargs, registry=self)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.8/site-packages/mmcv/utils/registry.py", line 61, in build_from_cfg
    raise KeyError(
KeyError: 'BEVDepth4DTRT is not in the models registry'

Below is what I got from "print(get_plugin_names())"

['DisentangledAttention_TRT', 'GroupNormalizationPlugin', 'CustomQKVToContextPluginDynamic', 'CustomQKVToContextPluginDynamic', 'CustomQKVToContextPluginDynamic', 'CustomEmbLayerNormPluginDynamic', 'CustomEmbLayerNormPluginDynamic', 'CustomEmbLayerNormPluginDynamic', 'CustomFCPluginDynamic', 'CustomGeluPluginDynamic', 'CustomSkipLayerNormPluginDynamic', 'CustomSkipLayerNormPluginDynamic', 'CustomSkipLayerNormPluginDynamic', 'CustomSkipLayerNormPluginDynamic', 'TRTBatchedBEVNMS', 'TRTBatchedNMS', 'TRTBatchedRotatedNMS', 'bev_pool_v2', 'TRTBicubicInterpolate', 'MMCVDeformConv2d', 'GatherTopk', 'GridPriorsTRT', 'grid_sampler', 'TRTInstanceNormalization', 'MMCVModulatedDeformConv2d', 'MMCVMultiLevelRoiAlign', 'MMCVMultiLevelRotatedRoiAlign', 'MMCVRoiAlign', 'ScaledDotProductAttentionTRT']

**Comment by HuangJunJie2017** [comment]
@myteen2 currently only CLASS BEVDet is supported as an example. You can support CLASS BEVDepth4D personly by following this example.

**Comment by myteen2** [comment]
> @myteen2 currently only CLASS BEVDet is supported as an example. You can support CLASS BEVDepth4D personly by following this example.

Thank you for the quick reply :)
I'll try with that example.

**Comment by changtimwu** [comment]
Well, this is a bit off-topic.   I saw most quantization works via TensorRT are FP16.  Is there anybody working on quantizing the BEV networks into INT8?
