### ISSUE TITLE
BEVDet/tools/misc/browse_dataset.py error in visualization

### ISSUE THREAD

**Issue by choiszt** [HuangJunJie2017/BEVDet#120]
When I implemented the browse_dataset.py to see the origin dataset of nuscenes (bevdetv2-nuscenes_infos_train.pkl), there is something wrong with the key results['ann_info'],which is not exist.

可视化过程中报错没有在rusult中找到ann_info的key，但此时已经在train-pipeline的条件下运行

 File "BEVDet/mmdet3d/datasets/pipelines/loading.py", line 559, in _load_bboxes_3d
    results['gt_bboxes_3d'] = results['ann_info']['gt_bboxes_3d']
KeyError: 'ann_info'

my args:				"BEVDet/configs/_base_/datasets/nus-3d.py",
				"--task","det",
				"--output-dir",
				"BEVDet/targetresultfolder",
				"--aug"

**Comment by HuangJunJie2017** [comment]
@choiszt  browse_dataset.py is not supported currently, I use to use 'python tools/analysis_tools/vis.py $savepath/pts_bbox/results_nusc.json' instead
