### ISSUE TITLE
IndexError: _Map_base::at

### ISSUE THREAD

**Issue by wuwangzhuanwan** [HuangJunJie2017/BEVDet#127]
When I convert model using "convert_bevdet_to_TRT.py", I always meet the error "IndexError: _Map_base::at". I try to set the paramter "keep_initializers_as_inputs=True", but can't solve this problem. I try to owngrade the version of torch from 1.13 to 1.12,  but this method will block the owner when executing “torch.onnx.export(...)”. How can I solve this problem？

**Comment by HuangJunJie2017** [comment]
@wuwangzhuanwan 
Downgrading the torch version is recommended. I use torch1.9 in development instead.
