### ISSUE TITLE
Key frame used in temporal alignment

### ISSUE THREAD

**Issue by toyot-li** [HuangJunJie2017/BEVDet#129]
@HuangJunJie2017 I would like to confirm how do the key frames are utilized in the latest version of BEVDet4D? The past 8 frames are sent to the network?

**Comment by HuangJunJie2017** [comment]
@zen-d yes, exactly, the bev features of the past 8 frames are retained and concated with the current's.

**Comment by toyot-li** [comment]
@HuangJunJie2017 Thanks for your prompt reply. I guess you have conducted experiments with other alternative settings, for example, 1. using past 8 frames, but also including non-key ones. 2. randomly sampling 8 keyframes in the past. 3. randomly sampling 8 frames (including both keyframes and non-key ones) in the past, looks like the initial version of BEVDet4D design. Do the above options all achieve sub-optimal performance?

**Comment by toyot-li** [comment]
@HuangJunJie2017 Any update? Thanks

**Comment by HuangJunJie2017** [comment]
@zen-d 
->Do the above options all achieve sub-optimal performance? 
I am not sure. It is awesome if you can verify this and share the results.

**Comment by toyot-li** [comment]
@HuangJunJie2017 Thanks, I will try and share the ablation in this thread when GPU devices are vacant.
