### ISSUE TITLE
NuScenesDataset: __init__() got an unexpected keyword argument 'img_info_prototype'

### ISSUE THREAD

**Issue by Egozjuer** [HuangJunJie2017/BEVDet#13]
Hello,I have met  such error when I use your *.pth to infer model

**Comment by HuangJunJie2017** [comment]
@Egozjuer please pull the latest code. This error has been fixed with this commit
https://github.com/HuangJunJie2017/BEVDet/commit/33a3f339c07d6d9e87bdd9d18598a8d8e5918ba4

**Comment by HuangJunJie2017** [comment]
@Egozjuer You need to pull and use the BEVDet project instead of modifying the official mmdet3d on your own.

**Comment by Egozjuer** [comment]
> @Egozjuer You need to pull and use the BEVDet project instead of modifying the official mmdet3d on your own.

那我是不是就不需要安装官方的mmdetection3d么，直接在你这个文件夹下run就好了？

**Comment by HuangJunJie2017** [comment]
@Egozjuer Yes. BEVDet is built upon mmdet3d and it maintains all features of mmdet3d. You don't need to install mmdetection3d additionally.

**Comment by Egozjuer** [comment]
> @Egozjuer Yes. BEVDet is built upon mmdet3d and it maintains all features of mmdet3d. You don't need to install mmdetection3d additionally.
我卸载了官方的mmdetection3d，发现又出现了这个错误
File "/home/zjlab/fq/perception/od/BEVDet/mmdet3d/ops/ball_query/ball_query.py", line 4, in <module>
    from . import ball_query_ext
ImportError: cannot import name 'ball_query_ext' from 'mmdet3d.ops.ball_query' (/home/zjlab/fq/perception/od/BEVDet/mmdet3d/ops/ball_query/__init__.py)

**Comment by Egozjuer** [comment]
> @Egozjuer Prepare BEVDet just like the official mmdet3d: cd BEVDet && python setup.py develop

又发生了异常: KeyError
'SwinTransformer is already registered in models'
  File "/home/zjlab/fq/perception/od/BEVDet/mmdet3d/models/backbones/swin.py", line 531, in <module>
    class SwinTransformer(BaseModule):

**Comment by Egozjuer** [comment]
> @Egozjuer Prepare BEVDet just like the official mmdet3d: cd BEVDet && python setup.py develop

mmcv 版本1.4.0
mmdet版本 2.23.0
mmsegmentation 0.22.1

**Comment by wanglaotou** [comment]
hello, i see the code in: https://github.com/HuangJunJie2017/BEVDet/blob/master/mmdet3d/datasets/nuscenes_dataset.py#L461
from nuscenes import NuScenes, but i cannot find the nuscenes file, i am confused, please tell me if you are free, thanks.

**Comment by kangxiao18** [comment]
> > > @Egozjuer Prepare BEVDet just like the official mmdet3d: cd BEVDet && python setup.py develop
> > 
> > 
> > mmcv 版本1.4.0 mmdet版本 2.23.0 mmsegmentation 0.22.1
> 
> Degrading the mmdet to 2.14.0

Hi, Could you please give us an runnable environment including mmlab related? Like mmdet, mmcv and mmsegmentation's version.

**Comment by kangxiao18** [comment]
> > > @Egozjuer Prepare BEVDet just like the official mmdet3d: cd BEVDet && python setup.py develop
> > 
> > 
> > mmcv 版本1.4.0 mmdet版本 2.23.0 mmsegmentation 0.22.1
> 
> Degrading the mmdet to 2.14.0

Hi, Could you please give us an runnable environment configuration especially mmlab related? Like mmdet, mmcv and mmsegmentation's version.
