### ISSUE TITLE
tensorRT deploy problem

### ISSUE THREAD

**Issue by mttsky** [HuangJunJie2017/BEVDet#132]
.engine have generated, but throw follow OutOfMemory error, ask if this error affect the result? thanks.
[virtualMemoryBuffer.cpp::resizePhysical::144] Error Code 2: OutOfMemory (no further information)
![image](https://user-images.githubusercontent.com/8543230/216505496-4cd2505d-dbf6-4232-baab-a5219ca39bed.png)

**Comment by HuangJunJie2017** [comment]
@mttsky use docker? set '--shm-size 64G'?

**Comment by mttsky** [comment]
thanks for your reply.
![image](https://user-images.githubusercontent.com/8543230/216506035-79953cc3-d3f0-4a71-87bd-a4dece9f467e.png)
![image](https://user-images.githubusercontent.com/8543230/216506174-9e8af974-7fa3-4be6-8097-75e86d3f207c.png)

**Comment by HuangJunJie2017** [comment]
@mttsky  type of your gpu? and version of tensorrt?

**Comment by HuangJunJie2017** [comment]
@mttsky  have you try fp32 by removing '--fp16' and '--int8'

**Comment by mttsky** [comment]
> @mttsky type of your gpu? and version of tensorrt?

 NVIDIA A40, tensorrt: 8.4.3.1

**Comment by mttsky** [comment]
> @mttsky have you try fp32 by removing '--fp16' and '--int8'

I try

**Comment by mttsky** [comment]
solved, other programs occupy memory.

**Comment by mttsky** [comment]
thanks, @HuangJunJie2017
