### ISSUE TITLE
Postprocessing

### ISSUE THREAD

**Issue by jeho-lee** [HuangJunJie2017/BEVDet#133]
Hi. Thx for the great work, especially for the effort on latency optimization.
As you guys mentioned in the paper, the time of postprocessing is about 14.3 ms.
Can you explain what the BEVDet does for this postprocessing stage?
This stage is for NMS?

**Comment by HuangJunJie2017** [comment]
@jeho-lee yes, mainly for NMS

**Comment by jeho-lee** [comment]
Thanks for the clarification :)
