### ISSUE TITLE
Question about receptive field

### ISSUE THREAD

**Issue by lhyakn** [HuangJunJie2017/BEVDet#134]
Thanks for your great work about bevdetv2! I noticed that you changed the coordinate system of the receptive field, So I changed the coordinate of CenterPoint to train a lidar based detector, but the interesting thing is the mAP has dropped 3 points. 

Perhaps changing the coordinate system of the receptive field is useful for camera-based detectors, but useless or even harmful for lidar-based detectors? And how much has this operation improved on bevdetv2?

**Comment by HuangJunJie2017** [comment]
@lhyakn 
Please refer to the technique report 'BEVPoolv2: A Cutting-edge Implementation of BEVDet Toward Deployment' for the reason for changing the coordinate system of the receptive field.
I conjecture that the lidar-based detectors share the same problem as the image-based detectors. Is your implementation defective? Please be patient in checking all details.

**Comment by lhyakn** [comment]
> @lhyakn Please refer to the technique report 'BEVPoolv2: A Cutting-edge Implementation of BEVDet Toward Deployment' for the reason for changing the coordinate system of the receptive field. I conjecture that the lidar-based detectors share the same problem as the image-based detectors. Is your implementation defective? Please be patient in checking all details.

Yeah, there are some problems I found with my implementation, now it is performing as expected. Thanks for your help, I'll close this issue.
