### ISSUE TITLE
BEVDetTRT dimension conversion

### ISSUE THREAD

**Issue by mttsky** [HuangJunJie2017/BEVDet#136]
Hi @HuangJunJie2017     
 tran_feat = tran_feat.permute(0, 2, 3, 1)  **#last dim is C**

x = TRTBEVPoolv2.apply(depth.contiguous(), tran_feat.contiguous(),
                               ranks_depth, ranks_feat, ranks_bev,
                               interval_starts, interval_lengths)

feat = feat.view(1, n, feat.shape[3], h, w) **#channel adjust to the second dimension**
feat = feat.permute(0, 1, 3, 4, 2) **#adjust to the last dimension**

why do this? thanks.

**Comment by HuangJunJie2017** [comment]
@mttsky 
        tran_feat = tran_feat.permute(0, 2, 3, 1)
        x = TRTBEVPoolv2.apply(depth.contiguous(), tran_feat.contiguous(),
                               ranks_depth, ranks_feat, ranks_bev,
                               interval_starts, interval_lengths)
        x = x.permute(0, 3, 1, 2).contiguous()
???  
conducting permute operation before and after BEVPoolv2 is not necessary.  If you want to remove them,  you just need to accordingly adjust the coordinate calculation in the CUDA implementation of BEVPoolv2.

**Comment by mttsky** [comment]
thansk fot your reply,  

feat's C has been adjusted to the last dimension before being passed in.

I means that what is the purpose of "feat = feat.view(1, n, feat.shape[3], h, w) " 【C adjust to the second dimension and next adjust to the last dimension】 in TRTBEVPoolv2 forward.

**Comment by HuangJunJie2017** [comment]
@mttsky 
I see your problem. I haven't checked the forward function in type TRTBEVPoolv2.  The following operations are redundant.
        feat = feat.view(1, n, feat.shape[3], h, w)
        feat = feat.permute(0, 1, 3, 4, 2)
I will fix this later.
