### ISSUE TITLE
Which deploy config should I use in mmdeploy/config/mmdet3d?

### ISSUE THREAD

**Issue by WYYAHYT** [HuangJunJie2017/BEVDet#137]
convert to TensorRT:
`python tools/convert_bevdet_to_TRT.py $config $checkpoint $work_dir --fuse-conv-bn --fp16`

I want to know which configuration file in mmdeploy/config/mmdet3d to use for bevdet-r50:

Really hope someone could help

**Comment by HuangJunJie2017** [comment]
@WYYAHYT use config in BEVDet instead~ for example
python tools/convert_bevdet_to_TRT.py configs/bevdet/bevdet-r50.py $checkpoint $work_dir --fuse-conv-bn --fp16

**Comment by WYYAHYT** [comment]
@HuangJunJie2017 Thanks a lot!! I thought it was the same as mmdeploy.
