### ISSUE TITLE
What needs to be modified in config if I change  BEV Resolution from 0.8m to 0.4m?

### ISSUE THREAD

**Issue by clw5180** [HuangJunJie2017/BEVDet#138]
Thx

**Comment by HuangJunJie2017** [comment]
@clw5180  for example in https://github.com/HuangJunJie2017/BEVDet/blob/dev2.0/configs/bevdet/bevdet-r50.py
line 34/35 0.8->0.4
line 99/113/127 8->4

**Comment by clw5180** [comment]
I tried it , but mAP is much lower than before（ - 7mAP ),  maybe there are some other places needs to modify ? Thanks !

> @clw5180 for example in https://github.com/HuangJunJie2017/BEVDet/blob/dev2.0/configs/bevdet/bevdet-r50.py line 34/35 0.8->0.4 line 99/113/127 8->4

**Comment by HuangJunJie2017** [comment]
@clw5180 
large bev resolution may need a longer training schedule
train with cbgs instead~
