### ISSUE TITLE
pretrained model inference with mmdet3d 1.0 problem.

### ISSUE THREAD

**Issue by AndyYuan96** [HuangJunJie2017/BEVDet#139]
Hi, thanks for sharing so great code, I copy some code from the repo to my code based on mmdet3d 1.0, and to verify if my copy is right, I use bevdet-r50 pretrained weight to inference, and the result only have a little difference, around 1 point in NDS.
As my inference result don't have too much difference with the repo's result, my mASE and mAOE is normal compared with other issue, So I just wonder that if you can give me some advice, many thanks.

mAP: 0.2954
mATE: 0.7376
mASE: 0.3073
mAOE: 0.5791
mAVE: 0.9264
mAAE: 0.2416
NDS: 0.3685.

**Comment by HuangJunJie2017** [comment]
@AndyYuan96  Just check numerical consistency step by step  from input tensors to output tensors

**Comment by AndyYuan96** [comment]
figure out why, for others that want to inference with the trained model in mmdet3d 1.0, change output_to_nusc_box function in nuscenes_dataset.py in mmdet3d 1.0, add two line : box_yaw = -box_yaw - np.ip / 2, nus_box_dims = box_dims, and comment nus_box_dims = box_dims[:,[1,0,2]]. the result is exactly the same with the repo's result.
