### ISSUE TITLE
Question about intermediate BEV feature of the previous frame 

### ISSUE THREAD

**Issue by ged0606** [HuangJunJie2017/BEVDet#14]
Hello, thanks for your great work!
Does the BEV feature of the previous frame is saved from previous computation, or computed at the same time with current frame? It seems cost less time using previous computation result when inference.

**Comment by HuangJunJie2017** [comment]
@ged0606  hi, the BEV feature is computed at the same time with the current frame. This repo is designed for research purposes and we try not to modify the testing logic of mmdet3d.  It is suggested to save BEV feature from previous computation when testing the idea inference speed and deploying in practice. We will support this recently.

**Comment by ged0606** [comment]
I see, thanks for you reply!

**Comment by jeho-lee** [comment]
Hi. Does the current version of the BEVDet framework supports saving previous BEV features for inference speed-up?
