### ISSUE TITLE
dev-2.0's bevdet-r50's improvement compared with master branch

### ISSUE THREAD

**Issue by AndyYuan96** [HuangJunJie2017/BEVDet#140]
Hi, I notice dev-2.0's bevdet-r50-cbgs 's mAP 30.7 and NDS 38.2, and master's result is mAP 29.9 and NDS 37.7, I just wonder where the improvement comes from, EMAHook or use the origin of ego coordinate system as the center of the receptive field instead of the Lidar's. 

In https://github.com/HuangJunJie2017/BEVDet/issues/135#issue-1571981867, it looks like ema can give large improvement to bevdet4d-r50, from mAP: 0.3744 NDS: 0.4989 to mAP: 0.3974 NDS: 0.5186, why bevdet-r50 don't have so large improvement with EMAHook.

What's more, do you think that using the origin of ego coordinate system as the center of the receptive field for lidar-only method like centerpoint can also get performance improvement?As I don't know using the origin of ego coordinate system as the center of the receptive field will cause what problem. Thanks for your kindly answer.

**Comment by lhyakn** [comment]
> What's more, do you think that using the origin of ego coordinate system as the center of the receptive field for lidar-only method like centerpoint can also get performance improvement?As I don't know using the origin of ego coordinate system as the center of the receptive field will cause what problem. Thanks for your kindly answer.

I changed the receptive field of centerpoint from lidar to ego, but I don't see any improvement (mAP 56.92 before/ 55.60 after).

**Comment by AndyYuan96** [comment]
> > What's more, do you think that using the origin of ego coordinate system as the center of the receptive field for lidar-only method like centerpoint can also get performance improvement?As I don't know using the origin of ego coordinate system as the center of the receptive field will cause what problem. Thanks for your kindly answer.
> 
> I changed the receptive field of centerpoint from lidar to ego, but I don't see any improvement (mAP 56.92 before/ 55.60 after).

thanks for sharing the result

**Comment by HuangJunJie2017** [comment]
@AndyYuan96 
1. EMAHook offers configuration-wise performance improvement, please refer to BEVDepth for an ablation study on different configurations.  
2. With regard to  #135 , mAP: 0.3744 NDS: 0.4989  is not the performance of bevdet4d-r50, as when the EMAHook is absent, we should scale down the learning rate in the last few epoch for more stable convergence.
3. please refer to #134 for some suggestions, I believe that the receptive field adjustment is adaptive to lidar-only methods. But I haven‘t verified this.
