### ISSUE TITLE
Performance of bevdet-r50.py

### ISSUE THREAD

**Issue by lhyakn** [HuangJunJie2017/BEVDet#142]
I trained the model with config bevdet-r50 several times, it seems that the performance of bevdet-r50 is unstable (mAP from 21.xx to 24.xx). Is this normal? Is this because of not using CBGS?

**Comment by HuangJunJie2017** [comment]
@lhyakn  It is not that normal. 
Have you modified any code? 
Have you checked the loss consistency with the released log? 
Have you eval with the released checkpoint to check the inference?

**Comment by lhyakn** [comment]
> Have you modified any code.

No, In case it's a problem with my code, I recloned code from latest commit and without any modification. data was recreated by 'creat_data_bevdet.py.'

> Have you checked the loss consistency with the released log?

Yes, if the final mAP is 24.xx then the loss is similar to the one in the released log. But the final mAP is not always 24. More details in the log below.
[20230211_233022.log](https://github.com/HuangJunJie2017/BEVDet/files/10728806/20230211_233022.log)
[20230213_144857.log](https://github.com/HuangJunJie2017/BEVDet/files/10728807/20230213_144857.log)
[20230214_000831.log](https://github.com/HuangJunJie2017/BEVDet/files/10728808/20230214_000831.log)


> Have you eval with the released checkpoint to check the inference?

Yes, the inference result is the same as the released inference result (NDS:32.23 mAP:27.87).

**Comment by yukaizhou** [comment]
I also encountered a similar problem. That is, use bevdet4d-r50-depth-cbgs.py, which adds the use of mixed precision training and large input（512x1408）. However, the gradient explosion occurs during the training process, so that it cannot converge.  More details in the log below.
[20230213_221028.log](https://github.com/HuangJunJie2017/BEVDet/files/10731522/20230213_221028.log)

**Comment by LuPaoPao** [comment]
Same here！
Without any changes~But get worse performance.

[20230305_220222.log](https://github.com/HuangJunJie2017/BEVDet/files/10893988/20230305_220222.log)

**Comment by HuangJunJie2017** [comment]
train without CBGS is deprecated.
