### ISSUE TITLE
How to select BEVDet or BEVDepth

### ISSUE THREAD

**Issue by PowerDi** [HuangJunJie2017/BEVDet#143]
I think one of the most different is the use of LIDAR data. So could we only use BEVDet to generate depth/distance information but do not use its detect function?

**Comment by HuangJunJie2017** [comment]
@PowerDi  Please refer to the provided configurations for examples in configs/bevdet/*

**Comment by PowerDi** [comment]
> @PowerDi Please refer to the provided configurations for examples in configs/bevdet/*

Thanks the reply. But I still comfusing. As we can obtain a depth distribution map with the value (0~1), is it possibly to generate absolute depth in order to directly transform a pixel 2D to 3D point？

**Comment by HuangJunJie2017** [comment]
@PowerDi yes, as the depth is predicted in a classification pattern, you can select the depth with the highest confidence and obtain the absolute depth according to the depth class id and the predefined depth classes in https://github.com/HuangJunJie2017/BEVDet/blob/cf9d62d42906c76ddd9cfe67324c0ddc4d8c3b2d/configs/bevdet/bevdet-r50.py#L37

**Comment by PowerDi** [comment]
@HuangJunJie2017 Maybe I can change step size to test precision. Have u ever got some informations about the depth precision?
