### ISSUE TITLE
different head

### ISSUE THREAD

**Issue by AndyYuan96** [HuangJunJie2017/BEVDet#144]
Hi，have you ever try different like transfusion-head，I just change the center-head to transfusion-head，the performance drop a lot，1/5 trainset， drop from NDS 0.1835 to NDS 0.0576。

**Comment by HuangJunJie2017** [comment]
I haven't tried this

**Comment by Yzichen** [comment]
> Hi，have you ever try different like transfusion-head，I just change the center-head to transfusion-head，the performance drop a lot，1/5 trainset， drop from NDS 0.1835 to NDS 0.0576。

@AndyYuan96  I'm also trying this and have also found that the performance goes down a lot. Can I add your wechat to exchange ideas?
