### ISSUE TITLE
Why BN instead of using SyncBN like most configs do?

### ISSUE THREAD

**Issue by ytwanghaoyu** [HuangJunJie2017/BEVDet#147]
I'm curious about using BN instead of SyncBN as most config do, especially consider it might have an effect when doing distributed training. 

Is there any specific reason why use BN?

**Comment by ytwanghaoyu** [comment]
Or more specifically, does using BN give a performance improvement?

**Comment by HuangJunJie2017** [comment]
@ytwanghaoyu According to the ablation study I have done, SyncBN doesn't show any superiority to BN in the performance aspect. Extra communication latency makes it deprecated in all configurations.

**Comment by ytwanghaoyu** [comment]
Thanks for your reply,

**Comment by ytwanghaoyu** [comment]
@HuangJunJie2017  Sorry for reopening the issue.

Just curious about how much time was consumed by the synchronisation process.

With my test, one epoch from 20 mins to 25 mins, which was about 25% more time. I think it's too much time consumed by sync bn, therefore I'm not quite sure about the correctness of the result.

**Comment by HuangJunJie2017** [comment]
@ytwanghaoyu It is platform-depended. I think 25% is normal as far as I know.

**Comment by ytwanghaoyu** [comment]
Coooool, thanks a lot.
