### ISSUE TITLE
bevpoolv2 speed

### ISSUE THREAD

**Issue by AndyYuan96** [HuangJunJie2017/BEVDet#149]
Hi，I use viewtransformer in my project，as I want to use bigger input image resolution，and bevpool can‘t training with limit gpu memory，I just download dev-2.0 branch，and use the bevpoolv2，I use master branch‘s preprocess and only use the bevpoolv2 core code，but I find the memory did use less，but the inference speed drop a lot。for example，I use nuscenes dataset，with input resolution 448 * 800 and 8 v100-32g， with bevpool， inference speed is 28 task/s， but with bevpool v2， inference speed is 10 task/s with mmdetection3d。

I just wonder can I directly use bevpool v2 instead of bevpool，and keep using master branch‘s preprocess，I remove the bda parameter of bevpool v2.

**Comment by WenxuanLi-whu** [comment]
是的，我也存在这样地问题，怎么解决，速度比以前慢了一倍以上

**Comment by WenxuanLi-whu** [comment]
而且我测试了一下，深度采样【1,60,0.5】的配置只比【4,45,1】的配置只高1个点左右
分辨率386*1056，v2-99的主干
