### ISSUE TITLE
Detail results

### ISSUE THREAD

**Issue by yingfei1016** [HuangJunJie2017/BEVDet#151]
Hello, 

We want to cite and compare with bevpoolv2. Could you provide detail results, including mATE, mASE,mAOE,mAVE,mAAE?
![image](https://user-images.githubusercontent.com/106943722/220505479-8c916fb3-14db-4390-a951-8c34f1e9a46e.png)
 Thanks!

**Comment by HuangJunJie2017** [comment]
@yingfei1016 
pts_bbox_NuScenes/mATE:0.5719
pts_bbox_NuScenes/mASE:0.2751
pts_bbox_NuScenes/mAOE:0.4630
pts_bbox_NuScenes/mAVE:0.2750
pts_bbox_NuScenes/mAAE:0.1879
pts_bbox_NuScenes/NDS:0.5259
pts_bbox_NuScenes/mAP:0.4063

pts_bbox_NuScenes/mATE:0.5777
pts_bbox_NuScenes/mASE:0.2754
pts_bbox_NuScenes/mAOE:0.4627
pts_bbox_NuScenes/mAVE:0.2803
pts_bbox_NuScenes/mAAE:0.1878
pts_bbox_NuScenes/NDS:0.5227
pts_bbox_NuScenes/mAP:0.4021
