### ISSUE TITLE
Reason why ego_cam is fixed to CAM_FRONT

### ISSUE THREAD

**Issue by jeho-lee** [HuangJunJie2017/BEVDet#155]
Hi. 
When calculating sweepsensor2keyego in loading.py, the ego2global matrix is always set to the one for CAM_FRONT.
According to your paper, the origin of the ego coord. system is set to the center of the receptive field.
So the intention of the code is to set the receptive field center as "CAM_FRONT" camera? not IMU sensor?

**Comment by HuangJunJie2017** [comment]
@jeho-lee  >ego2global matrix is always set to the one for CAM_FRONT.
This statement is not established as far as I know.

**Comment by jeho-lee** [comment]
According to **PrepareImageInputs** class in loading.py and **NuScenesDataset** class in nuscenes_dataset.py, 
the default value of 'ego_cam' parameter is set to 'CAM_FRONT'.

I'm testing BEVDet4D using the tools/test.py and bevdet4d-r50-depth-cbgs.py config.
And as far as I know, there are no statements to set the ego_cam as None.
Also, the value of 'ego_cam' var from the NuScenesDataset instance is printed as CAM_FRONT.

Is there any statement that I've missed?

**Comment by HuangJunJie2017** [comment]
@jeho-lee I mean that the transformation from ego to global should not be set to one, as this means that the ego coordinate system is identical to the global coordinate system. Please check your statement carefully.

**Comment by HuangJunJie2017** [comment]
@jeho-lee  >the default value of 'ego_cam' parameter is set to 'CAM_FRONT'
ego_cam='CAM_FRONT' does not mean that we use the camera coordinate system. Instead, we use the ego coordinate system defined on the IMU sensor, which is recorded when the 'CAM_FRONT' camera captures the images.

**Comment by jeho-lee** [comment]
Oh, sorry for the confusion.
I mean the keyego2global matrix always comes from 'CAM_FRONT', not the identity matrix.

And your final comment clarifies my misunderstandings.
Thank you so much :)

**Comment by daxiongpro** [comment]
作者你们好。请教一下：为什么每个相机都有一个 ego2global的转换矩阵？按照我的理解，ego 坐标系和 global 坐标系对于每个相机都是同一个呀？
