### ISSUE TITLE
The performance affected by the lr schedule.

### ISSUE THREAD

**Issue by DevLinyan** [HuangJunJie2017/BEVDet#156]
**Notice**

 Hi, junjie. I have a question as follows:

1.  why you do not use the lr decay using StepLR similar in the last version? 

As we know, the performance will be better if we adopt the lr decay in the training process. Is EMA the cause of this operation？Or you have tuned these hyper-params, that removing lr decay can achieve the better performance?

**Comment by HuangJunJie2017** [comment]
@linyanAI 
>Is EMA the cause of this operation?  Yes
