### ISSUE TITLE
    assert 'bev_pool_v2' in get_plugin_names(), \ AssertionError: bev_pool_v2 is not in the plugin list of tensorrt, please install mmdeploy from https://github.com/HuangJunJie2017/mmdeploy.git

### ISSUE THREAD

**Issue by shuishenbushui** [HuangJunJie2017/BEVDet#157]
Convert to TensorRT and test inference speed.
2. convert to TensorRT
python tools/convert_bevdet_to_TRT.py $config $checkpoint $work_dir --fuse-conv-bn --fp16 --int8 

errors:
   assert 'bev_pool_v2' in get_plugin_names(), \
AssertionError: bev_pool_v2 is not in the plugin list of tensorrt, please install mmdeploy from https://github.com/HuangJunJie2017/mmdeploy.git

I cant find any bev_pool_v2 in mmdeploy,where is the bev_pool_v2 code of Tensorrt?

**Comment by shuishenbushui** [comment]
I think you forget upload your code in mmdeploy, is that right?

**Comment by HuangJunJie2017** [comment]
@shuishenbushui .....nice conjecture~
https://github.com/HuangJunJie2017/mmdeploy/tree/f70f3af35474929c1cc402c9d058cc40457e5188/csrc/mmdeploy/backend_ops/tensorrt/bevpoolv2

**Comment by 15116513319** [comment]
重装mmdeploy,https://blog.csdn.net/weixin_43863869/article/details/124836907
