### ISSUE TITLE
DCN leads to 0 mAP

### ISSUE THREAD

**Issue by toyot-li** [HuangJunJie2017/BEVDet#158]
@HuangJunJie2017 I set use_dcn as True in BEVDepth and got 0 mAP. But I see that the original BEVDepth uses DCN in DepthNet. What is the reason for disabling DCN in this repo? Is the experimental result the same as mine? Thanks

**Comment by HuangJunJie2017** [comment]
@zen-d Divergent loss?

**Comment by toyot-li** [comment]
@HuangJunJie2017 Yes, loss becomes increasing, grad norm becomes very large in the 15th epoch.

**Comment by HuangJunJie2017** [comment]
@zen-d That's the point~Removing DCN makes the training more stable, but will not lead to obvious performance degeneration.

**Comment by toyot-li** [comment]
@HuangJunJie2017 Thanks for your quick reply! May I know why the official BEVDepth could still converge with DCN inserted? More specifically, what is the underlying reason that only one DCN operator makes this repo's BEVDepth diverge?

**Comment by HuangJunJie2017** [comment]
@zen-d the official BEVDepth also has the same problem~ you can refer to these issues for extra infos  
https://github.com/Megvii-BaseDetection/BEVDepth/issues/36
https://github.com/Megvii-BaseDetection/BEVDepth/issues/24

**Comment by toyot-li** [comment]
@HuangJunJie2017 Thanks a lot for letting me know this. It indeed provides useful background for my understanding. But I have used the WD of 1e-2, as the default value. According to my experience, it has been a relatively large value. In addition, I have not met similar problems when training 2D image detectors and 3D LiDAR point clout detectors (Correct me if not the fact). Would you like to share some insights about why the auxiliary depth net (or the entire BEV-based detector?) looks so "fragile"? Thanks.

**Comment by HuangJunJie2017** [comment]
@zen-d I have no idea other than that the DOF of DCN is too large.
