### ISSUE TITLE
cfg.model.type + 'TRT'

### ISSUE THREAD

**Issue by wuwangzhuanwan** [HuangJunJie2017/BEVDet#159]
Why add "TRT" in line 33 of `tools/convert_bevdet_to_TRT.py`, this will cause `BEVDET4DTRT is not in the models registery`

**Comment by HuangJunJie2017** [comment]
@wuwangzhuanwan BEVDET4DTRT hasn't been supported now. You can achieve this by imitating the BEVDetTRT class.
