### ISSUE TITLE
After retraining, I found that the projection results always shift forward. If the official model is used, it is normal. Has the author encountered it?

### ISSUE THREAD

**Issue by abing222** [HuangJunJie2017/BEVDet#16]
![1538984242447730](https://user-images.githubusercontent.com/44023160/172516553-211dac76-6758-4dea-99d4-3a650b4f8e63.jpg)

**Comment by abing222** [comment]
map and nds are normal, bev projection is normal, and z prediction is poor

**Comment by abing222** [comment]
There is no problem with the visualization code. The visualization of the official model is completely normal. Such problems will occur with the retrained model

**Comment by HuangJunJie2017** [comment]
It seems ok when I use the '--show' in tools/test.py. The predicted bounding boxes of BEVDet are tightly surrounding the lidar points of the targets.
![image](https://user-images.githubusercontent.com/31001081/172523559-e5dbd642-a980-4576-9081-dcd985921812.png)

**Comment by abing222** [comment]
> It seems ok when I use the '--show' in tools/test.py. The predicted bounding boxes of BEVDet are tightly surrounding the lidar points of the targets. ![image](https://user-images.githubusercontent.com/31001081/172523559-e5dbd642-a980-4576-9081-dcd985921812.png)

There is no problem with Bev, but the accuracy of Z cannot be seen

**Comment by abing222** [comment]
> It seems ok when I use the '--show' in tools/test.py. The predicted bounding boxes of BEVDet are tightly surrounding the lidar points of the targets. ![image](https://user-images.githubusercontent.com/31001081/172523559-e5dbd642-a980-4576-9081-dcd985921812.png)

The officially provided model visualization is normal, but the Z error will be large after retraining, but this will not affect the map and NDS

**Comment by HuangJunJie2017** [comment]
@abing222 The z prediction seems ok in my visualization.

**Comment by abing222** [comment]
> @abing222 The z prediction seems ok in my visualization.



> 

There is no error in the provided model, and Z prediction is normal, but Z will have a large error if the model is retrained

**Comment by HuangJunJie2017** [comment]
@abing222 I got it, you mean there is something wrong with the training process. I will check this.

**Comment by abing222** [comment]
> @abing222 I got it, you mean there is something wrong with the training process. I will check this.

thank you

I have checked the bbox and camera external parameters after Bev enhancement, and there is no problem, that is, GT is no problem

**Comment by HuangJunJie2017** [comment]
@abing222 What configuration do you use for retraining, bevdet or the bevdet4d

**Comment by abing222** [comment]
> @abing222 What configuration do you use for retraining, bevdet or the bevdet4d

bevdet tiny

**Comment by HuangJunJie2017** [comment]
> > @abing222 What configuration do you use for retraining, bevdet or the bevdet4d
> 
> bevdet tiny

got it

**Comment by HuangJunJie2017** [comment]
@abing222 may I have your training log?

**Comment by abing222** [comment]
> @abing222 may I have your training log?



> @abing222 may I have your training log? [junjie.huang@ieee.org](mailto:junjie.huang@ieee.org)

yes

**Comment by luqiang6q** [comment]
> ![1538984242447730](https://user-images.githubusercontent.com/44023160/172516553-211dac76-6758-4dea-99d4-3a650b4f8e63.jpg)

Can you provide your visualization command? I'd like to try it.I don't know how to visualize on multi images

**Comment by MandyMo** [comment]
<img width="783" alt="image" src="https://user-images.githubusercontent.com/13689401/179928007-31a2cbc1-c2a4-45d3-8b95-7ad9854f3045.png">

同样碰到了类似的问题，不知道作者有没有碰到，嘻嘻。

**Comment by HuangJunJie2017** [comment]
@MandyMo It seems like some false positive result,  i suggest you to use a higher score threshold~
