### ISSUE TITLE
BEVDet-Gamma's perfomance on nuscenes val split

### ISSUE THREAD

**Issue by woxihuanjiangguo** [HuangJunJie2017/BEVDet#160]
Hello author, can you share the detailed performance of BEVDet-Gamma on NuScenes val split?

**Comment by HuangJunJie2017** [comment]
@woxihuanjiangguo train with train set only and without tta
mAP: 0.5474
mATE: 0.4470
mASE: 0.2651
mAOE: 0.3278
mAVE: 0.1846
mAAE: 0.1878
NDS: 0.6325

**Comment by woxihuanjiangguo** [comment]
Thanks！

**Comment by linyanAI** [comment]
Hello, is this results the EMA with TTA or just the EMA results without TTA.
