### ISSUE TITLE
About bda_aug_conf

### ISSUE THREAD

**Issue by zuojiaqi0312** [HuangJunJie2017/BEVDet#161]
hi,thanks for you work.
I see some code in the configuration file. one of them is bda_aug_conf, it is used in LoadAnnotationsBEVDepth class. It looks like feature enhancement for real 3D information. But why should we do feature enhancement for real 3D information? Can you explain its function？thanks for you time

**Comment by HuangJunJie2017** [comment]
@zuojiaqi0312 please refer to the technical report for explanations
