### ISSUE TITLE
Error when I create dataset

### ISSUE THREAD

**Issue by zhenghw2000** [HuangJunJie2017/BEVDet#162]
Thanks for your error report and we appreciate it a lot.
When I reprocess the nuscenes dataset with the script `python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes`. It reports errors:
![image](https://user-images.githubusercontent.com/127185486/223354687-cf2c81f0-47d9-4011-b106-529bbd272d38.png)
How can I solve it?

**Comment by HuangJunJie2017** [comment]
@zhenghw2000  do not modify any code before you run this~ 
create_groundtruth_database() should be in line 89 instead of line87

**Comment by zhenghw2000** [comment]
@HuangJunJie2017 Hi! I downloaded your code again and ran `create_ data.py `file, but the same problem still exists.
![image](https://user-images.githubusercontent.com/127185486/223738040-f75df40a-5831-470f-a180-0e4c6e923a5a.png)

**Comment by HuangJunJie2017** [comment]
@zhenghw2000 
I have never seen this in development, it seems to be a personal issue
In fact, you should use create_data_bevdet.py instead to create the pkl for BEVDet.
If you insist on using create_data.py for personal reasons, try to fix this on your own

**Comment by zhenghw2000** [comment]
Thanks for your reply



---- Replied Message ----
| From | Huang ***@***.***> |
| Date | 03/08/2023 23:05 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [HuangJunJie2017/BEVDet] Error when I create dataset (Issue #162) |

@zhenghw2000
I have never seen this in development, it seems to be a personal issue
In fact, you should use create_data_bevdet.py instead to create the pkl for BEVDet.
If you insist on using create_data.py for personal reasons, try to fix this on your own

**Comment by lilkeker** [comment]
> @HuangJunJie2017你好！我再次下载了你的代码并运行`create_ data.py `文件，但同样的问题仍然存在。 ![图像](https://user-images.githubusercontent.com/127185486/223738040-f75df40a-5831-470f-a180-0e4c6e923a5a.png)

你好，我也遇到了相同的问题，我现在想在bevdet——dev2上复现bevfusion ,因此需要训练一个点云模型，在训练点云的过程中需要使用    dict(type='ObjectSample', db_sampler=db_sampler),并且指定 'nuscenes_dbinfos_train.pkl'，因此我需要用create_data.py来生成这个dbinfos_train.pkl文件，我出现了这个问题，原因是bevdet_dev2.0使用的annn和原本的mmdet3d 的anno 不同，bevdet使用LoadAnnotationsBEVDepth，而原本的mmdet3d使用LoadAnnotations3D，并且我遇到了一个坐标系的问题，我现在因为要做融合的模型，因此需要统一bevdet和我现在点云模型在同一（ego坐标系）坐标系下，我不太知道怎么修改，你能帮我指导一下吗？
