### ISSUE TITLE
KeyError: 'BEVDet is not in the models registry'

### ISSUE THREAD

**Issue by jyh3690** [HuangJunJie2017/BEVDet#163]
![image](https://user-images.githubusercontent.com/73591423/223962034-e341dd3d-1adb-4e4e-854a-1024eb9cb0bb.png)
i have an error and i can not resolve it,can anyone help me?thanks

**Comment by HuangJunJie2017** [comment]
@jyh3690 For ERROR like 'xxxx is not in the models regsitry'. 
please add prefix 'PYTHONPATH="$(dirname $0)/..":$PYTHONPATH' if you have not installed BEVDET in your python environment
for example:
`PYTHONPATH="$(dirname $0)/..":$PYTHONPATH python tools/analysis_tools/get_flops.py configs/bevdet/bevdet-r50.py --shape 256 704`

**Comment by jyh3690** [comment]
![image](https://user-images.githubusercontent.com/73591423/223965514-420148b5-9f79-4490-a238-3ada6cf2907a.png)
you are so nice!thank you very much,but i have another problem,i am so sorry

**Comment by HuangJunJie2017** [comment]
@jyh3690 
you are not expected to modify this prefix 'PYTHONPATH="$(dirname $0)/..":$PYTHONPATH'

**Comment by jyh3690** [comment]
thank you so much!you are so nice!
