### ISSUE TITLE
Performance drop with bevpool v2 during training

### ISSUE THREAD

**Issue by HatakeKiki** [HuangJunJie2017/BEVDet#164]
Great improvements for image feature pooling! I try to replace the bevpool module in BEVFusion-MIT with bevpool v2 as in this repo. I use previously trained model with bevpool v1 for evaluation with bevpool v2, and all metrics are the same. But when I use bevpool v2 for training, the performance will drop from mAP (68.89 -> 67.96) and NDS (71.68 -> 71.08).
Specifically, I replace the original bev_pool with voxel_pooling_v2 with corresponding inputs:

            feats, depth = self.get_cam_feats_depth(img, depth)
            x = self.voxel_pooling_v2(geom, depth, feats, out_bool=out_bool)

**Comment by HuangJunJie2017** [comment]
@HatakeKiki They are identical in theory and I haven't met obvious performance degeneration in development in camera-only 3D object detection.

**Comment by HatakeKiki** [comment]
> @HatakeKiki They are identical in theory and I haven't met obvious performance degeneration in development in camera-only 3D object detection.

Did you train with bevpool v2 in BEVDet, too? Also no performance drop?

**Comment by HuangJunJie2017** [comment]
@HatakeKiki yes

**Comment by HatakeKiki** [comment]
Thank you! I'll keep checking!

**Comment by Yzichen** [comment]
@HatakeKiki May I ask if you have solved this problem?

**Comment by WenxuanLi-whu** [comment]
解决了这个问题吗，怎么配置的，能发个配置参考一下吗
