### ISSUE TITLE
Questions on past frames

### ISSUE THREAD

**Issue by DianCh** [HuangJunJie2017/BEVDet#165]
Hi @HuangJunJie2017 ! Thank you for releasing this nice work. I wonder in your temporal modeling, are the past frames all keyframes (2Hz) or do you also use non-keyframes (original frame-rate)?

**Comment by HuangJunJie2017** [comment]
@DianCh 
The original frame rate is used in the previous version of BEVDet4D in the master branch. 
However, it is deprecated in the latest version in the dev2.0 branch.
Please refer to the following source code in these two branches for how we sample history frames.
tools/create_data(_bevdet).py
mmdet3d/datasets/nuscenes_dataset.py

**Comment by DianCh** [comment]
@HuangJunJie2017 Thank you for the pointer. Can I ask why this change in the dev2.0 branch? What's the advantage of using keyframe-only?

**Comment by HuangJunJie2017** [comment]
@DianCh just because sweepframe is unnecessary from the perspective of accuracy.
