### ISSUE TITLE
Is the result of the model with ema?

### ISSUE THREAD

**Issue by LCH1238** [HuangJunJie2017/BEVDet#167]
如题，请问论文里的结果和这些结果，都是ema模型的结果吗？
![微信截图_20230315141910](https://user-images.githubusercontent.com/43610172/225223910-1d8f9b4f-977b-4909-a8b5-4185b4d08692.png)

**Comment by HuangJunJie2017** [comment]
@LCH1238 results of BEVDet/BEVDet4D techniqual reports  in branch master are trained without ema, while BEVPoolv2 in branch dev2.0 is trained with ema

**Comment by LCH1238** [comment]
> @LCH1238 results of BEVDet/BEVDet4D techniqual reports in branch master are trained without ema, while BEVPoolv2 in branch dev2.0 is trained with ema

非常感谢！
