### ISSUE TITLE
PointToMultiViewDepth？

### ISSUE THREAD

**Issue by ningerlove** [HuangJunJie2017/BEVDet#168]
can you tell me "ranks[1:] != ranks[:-1]" in  PointToMultiViewDepth funtion mean?

**Comment by HuangJunJie2017** [comment]
@ningerlove  to figure out the position that is the rank first appear at the queue, for example 
ranks = [0,0,0,1,1,2,2,2,3,3,3]
kept[1:] = ranks[1:] != ranks[:-1] = [1,0,0,1,0,1,0,0,1,0,0]
