### ISSUE TITLE
How to use your pretrained model to do inference on nuScenes mini dataset?

### ISSUE THREAD

**Issue by cherry-yh** [HuangJunJie2017/BEVDet#17]
Many thanks for your great work! 
I want to use your pretrained model (name as, bevdet-sttiny-pure.pth) to do inference on nuScenes mini dataset, and I use the following command:
python tools/test.py configs/bevdet/bevdet-sttiny.py pretrained_models/bevdet-sttiny-pure.pth --show --show-dir infer_res/

But I encounter an error:
BEVDet-master/mmdet3d/models/detectors/mvx_two_stage.py", line 466, in show_results
    if isinstance(data['points'][0], DC):
KeyError: 'points'

I checked there are only two keys in data, such as dict_keys(['img_metas', 'img_inputs']), while without 'points' key.
Could you please give me some advice on how to do inference?

**Comment by HuangJunJie2017** [comment]
You just need to pull the latest code

**Comment by cherry-yh** [comment]
> You just need to pull the latest code

I have pulled the latest code, and the above error is solved. But I run this code on remote server, what should I do?

**Comment by HuangJunJie2017** [comment]
you can refer to the official mmdet3d for supporting visualization on the remote servers

**Comment by cherry-yh** [comment]
> you can refer to the official mmdet3d for supporting visualization on the remote servers

OK, thanks again.

**Comment by qianchenghao** [comment]
@cherry-yh  Did you solve it?
