### ISSUE TITLE
Number of iters per epoch

### ISSUE THREAD

**Issue by Frank207507** [HuangJunJie2017/BEVDet#170]
nuScenes has more than 20,000 frames. The batch size of each eight-card machine is 8. Therefore, according to theory, each epoch only needs to run more than 300 times, why does it need 1931 times？

**Comment by HuangJunJie2017** [comment]
@Jingwei-Jiang CBGS extends the dataset

**Comment by Frank207507** [comment]
Thank you for your quick response and excellent work！

**Comment by Frank207507** [comment]
I don't want to use cbgs. How should I modify the configs?

**Comment by Frank207507** [comment]
I got it
