### ISSUE TITLE
BEVStereo with BEVPoolV2

### ISSUE THREAD

**Issue by jeho-lee** [HuangJunJie2017/BEVDet#171]
The BEVPoolV2 brings an enormous degradation of BEV construction latency. And since the view transformer is an independent module of the entire detector, I think we can replace the **BEVStereo**'s view transformer with the BEVDet-Dev2's. Am I correct? Does anyone have an opinion on it?

**Comment by HuangJunJie2017** [comment]
@jeho-lee Of cause, as they are identical in theory.

**Comment by jeho-lee** [comment]
Great. Thanks for the comment.
