### ISSUE TITLE
I notice that val loss reaches minimum at 5th epoch, but mAP and NDS achieve maximun at 19th epoch, I'm curious as to why this is the case.

### ISSUE THREAD

**Issue by alpacaduby** [HuangJunJie2017/BEVDet#174]
I think when val loss reaches minimal,maximum mAP and NDS should occur almost simultaneously.
I use my own backbone ,here is the related data:
loss:
![image](https://user-images.githubusercontent.com/98697689/227102816-dfd76c3a-a176-4830-af73-24933bcf11ba.png)
mAP:
![image](https://user-images.githubusercontent.com/98697689/227102778-09ac6f18-0665-4faf-8627-9125b741ed05.png)
NDS:
![image](https://user-images.githubusercontent.com/98697689/227102846-41ed372f-8772-43c1-ac8b-c858fc24ef87.png)

**Comment by HuangJunJie2017** [comment]
@alpacaduby 
Eval in training is deprecated as it may not be adaptive to the BEVDet paradigm.  
Just ignore it or fixed it on your own if you insist on using this feature.
I use '--no-validate' to disable this.
I will set using  '--no-validate' as a default option in the revision.
