### ISSUE TITLE
转换tensorrt 报错

### ISSUE THREAD

**Issue by phoenares** [HuangJunJie2017/BEVDet#175]
大佬，
我在jetson orin上转tensorrt的时候报错，在p100上可以正常转换，能给看下是啥问题吗，没看到具体报错的原因。
pytorch 是1.11.0版本, mmcv 是1.7.0版本, jetson 版本信息如下：
![Uploading Screenshot from 2023-03-23 14-34-38.png…]()

报错信息如下：
python tools/convert_bevdet_to_TRT.py configs/bevdet/bevdet-r50.py bevdet-dev2.0/bevdet-r50.pth engines/ --fuse-conv-bn --fp16 --int8
env/mmcv/mmcv/__init__.py:20: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  warnings.warn(
2023-03-23 13:30:57,003 - mmdeploy - INFO - Successfully loaded tensorrt plugins from mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
archiconda3/envs/mmdeploy/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py:401: UserWarning: DeprecationWarning: pretrained is deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
load checkpoint from local path: bevdet-dev2.0/bevdet-r50.pth
BEVDet/mmdet3d/datasets/pipelines/loading.py:1130: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /media/nvidia/NVME/pytorch/JetPack_5.0/pytorch-v1.11.0/torch/csrc/utils/tensor_new.cpp:207.)
  gt_boxes, gt_labels = torch.Tensor(gt_boxes), torch.tensor(gt_labels)
BEVDet/mmdet3d/datasets/pipelines/loading.py:1130: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /media/nvidia/NVME/pytorch/JetPack_5.0/pytorch-v1.11.0/torch/csrc/utils/tensor_new.cpp:207.)
  gt_boxes, gt_labels = torch.Tensor(gt_boxes), torch.tensor(gt_labels)
BEVDet/mmdet3d/datasets/pipelines/loading.py:1130: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /media/nvidia/NVME/pytorch/JetPack_5.0/pytorch-v1.11.0/torch/csrc/utils/tensor_new.cpp:207.)
  gt_boxes, gt_labels = torch.Tensor(gt_boxes), torch.tensor(gt_labels)
BEVDet/mmdet3d/datasets/pipelines/loading.py:1130: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /media/nvidia/NVME/pytorch/JetPack_5.0/pytorch-v1.11.0/torch/csrc/utils/tensor_new.cpp:207.)
  gt_boxes, gt_labels = torch.Tensor(gt_boxes), torch.tensor(gt_labels)
BEVDet/mmdet3d/models/necks/view_transformer.py:202: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ranks_depth = torch.range(
BEVDet/mmdet3d/models/necks/view_transformer.py:204: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  ranks_feat = torch.range(
BEVDet/mmdet3d/models/necks/view_transformer.py:212: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  batch_idx = torch.range(0, B - 1).reshape(B, 1). \
cuda:0
cuda:0
cuda:0
WARNING: The shape inference of mmdeploy::bev_pool_v2 type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::bev_pool_v2 type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
WARNING: The shape inference of mmdeploy::bev_pool_v2 type is missing, so it may result in wrong shape inference for the exported graph. Please consider adding it in symbolic function.
ONNX Model Correct
  0%|                                                                                                      | 0/81 [00:00<?, ?it/s] BEVDet/mmdet3d/datasets/pipelines/loading.py:1130: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /media/nvidia/NVME/pytorch/JetPack_5.0/pytorch-v1.11.0/torch/csrc/utils/tensor_new.cpp:207.)
  gt_boxes, gt_labels = torch.Tensor(gt_boxes), torch.tensor(gt_labels)
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 81/81 [00:33<00:00,  2.42it/s]
2023-03-23 13:32:44,079 - mmdeploy - INFO - Successfully loaded tensorrt plugins from mmdeploy/mmdeploy/lib/libmmdeploy_tensorrt_ops.so
tools/convert_bevdet_to_TRT.py:245: DeprecationWarning: Use set_memory_pool_limit instead.
  config.max_workspace_size = max_workspace_size
tools/convert_bevdet_to_TRT.py:285: DeprecationWarning: Use build_serialized_network instead.
  engine = builder.build_engine(network, config)
0/81
Segmentation fault (core dumped)

**Comment by HuangJunJie2017** [comment]
@phoenares  mmm, as this prompt doesn't offer any information. I suggest you try some other configuration like converting without '--int8' to locate the problem.

**Comment by phoenares** [comment]
thanks for reply, I have tried without --int8 and --fp16, but still get the same result..

**Comment by HuangJunJie2017** [comment]
@phoenares remove/replace bevpoolv2 with some other operation (regardless of the performance) to check if this operation cause the core dumped.

**Comment by phoenares** [comment]
OK, I will try this.

**Comment by zhangjiannan1** [comment]
@phoenares Did you solve this problem?

**Comment by phoenares** [comment]
sorry, the device is occupied now, I will close this first, and I will update it later when there is progress. Thank you.

**Comment by 15116513319** [comment]
您好，请问这个问题您解决了吗？我也遇到了类似的问题：

File "tools/convert_bevdet_to_TRT.py", line 454, in <module>
    main()
  File "tools/convert_bevdet_to_TRT.py", line 362, in main
    torch.onnx.export(
  File "/home/wxq/archiconda3/envs/bevdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/wxq/archiconda3/envs/bevdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 1533, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/wxq/archiconda3/envs/bevdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/wxq/archiconda3/envs/bevdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 989, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/wxq/archiconda3/envs/bevdet/lib/python3.8/site-packages/torch/onnx/utils.py", line 893, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/wxq/archiconda3/envs/bevdet/lib/python3.8/site-packages/torch/jit/_trace.py", line 1260, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/wxq/archiconda3/envs/bevdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wxq/archiconda3/envs/bevdet/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/wxq/archiconda3/envs/bevdet/lib/python3.8/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/wxq/archiconda3/envs/bevdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1480, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/wxq/archiconda3/envs/bevdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1467, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/wxq/wangxinqi/BEVDet/mmdet3d/models/detectors/bevdet.py", line 244, in forward
    x = TRTBEVPoolv2.apply(depth.contiguous(), tran_feat.contiguous(),
  File "/home/wxq/wangxinqi/BEVDet/mmdet3d/ops/bev_pool_v2/bev_pool.py", line 137, in forward
    bev_feat = bev_pool_v2(depth, feat, ranks_depth, ranks_feat, ranks_bev,
  File "/home/wxq/wangxinqi/BEVDet/mmdet3d/ops/bev_pool_v2/bev_pool.py", line 88, in bev_pool_v2
    x = QuickCumsumCuda.apply(depth, feat, ranks_depth, ranks_feat, ranks_bev,
RuntimeError: _Map_base::at
段错误 (核心已转储)

而且也是在jetson orin上遇到的，大佬要是解决了可以分享一下解决方法吗，非常感谢！！！

**Comment by phoenares** [comment]
还没有，，最近在做别的项目

**Comment by jongsik-moon** [comment]
How did you install onnxruntime? Did you built onnxruntime from source?
