### ISSUE TITLE
Nonezero ops trt

### ISSUE THREAD

**Issue by cswwp** [HuangJunJie2017/BEVDet#176]
![image](https://user-images.githubusercontent.com/11901683/227185156-70e91737-8e88-4f32-9663-7bfb64034b7a.png)
from mmdet3d/models/necks/view_transformer.py   def voxel_pooling_prepare_v2, you try to filter out points that are outside box with code like this:

# filter out points that are outside box
        kept = (coor[:, 0] >= 0) & (coor[:, 0] < self.grid_size[0]) & \
               (coor[:, 1] >= 0) & (coor[:, 1] < self.grid_size[1]) & \
               (coor[:, 2] >= 0) & (coor[:, 2] < self.grid_size[2])
        if len(kept) == 0:
            return None, None, None, None, None
        coor, ranks_depth, ranks_feat = \
            coor[kept], ranks_depth[kept], ranks_feat[kept]
will it attach nonzero error when convert onnx to trt engine?
i meet this nonzero op error when i convert to trt from onnx, do you mind to explain it? thank you and looking forward your replay

![image](https://user-images.githubusercontent.com/11901683/227186309-d3a393e1-a90e-41c5-bc00-c39746bfcbd6.png)
![image](https://user-images.githubusercontent.com/11901683/227186417-23a4028d-a135-4103-9d68-57cf2e75dedf.png)

**Comment by HuangJunJie2017** [comment]
@cswwp you means len(kept)==0?

**Comment by cswwp** [comment]
> 
no, i convert my own model ( an oft module) to tensorrt, where oft module is similar like your view transform
my code is like this

                #3d voxel投影出来的在像素坐标系下的角点坐标，是否可见
                visible = (bbox_corners[..., 0] > 0) & (bbox_corners[..., 0]
                                                        < img_width) & (bbox_corners[..., 1] < img_height) & (bbox_corners[..., 1] > 0)

                # visible = torch.where(bbox_corners[..., 0] > 0, 1, 0) * torch.where(bbox_corners[..., 0] < img_width, 1, 0) \
                #         * torch.where(bbox_corners[..., 1] < img_height, 1, 0) * torch.where(bbox_corners[..., 1] > 0, 1, 0)
                
                

                # visible = torch.nonzero(visible.float()).squeeze(-1)
                # visible = torch.where(visible > 0)[0]
                # visible = bbox_corners[..., 0].clip
                # pdb.set_trace()
                if self.debug:
                    # bbox_corners_c = norm_corners.view(self.height_channel, height, width, 2).cpu().numpy()
                    bbox_corners_c = bbox_corners.float().cpu().numpy()
                    np.save('./bbox_corners_' + str(1 / self.scale) + '_' + str(i) + '.npy', bbox_corners_c)
                    img_corners_c = img_corners.view(self.height_channel, height, width, 2).cpu().numpy()
                    np.save('./img_corners_' + str(1 / self.scale) + '_' + str(i) + '.npy', img_corners_c)
                    visible_c = visible.view(self.height_channel, height, width).cpu().numpy()
                    np.save('./visible_' + str(i) + '.npy', visible_c)
                # Compute the area of each bounding box
                
                
                # pdb.set_trace()

                vox_feat = torch.zeros((channel, z_channel * height * width), device=feature.device)
                if self.with_depth:
                    dist = dist.view(-1, 1).clamp(0, depth)
                    vox_feat[:, visible] = feature[i, :, dist[visible, 0], bbox_corners[visible, 1], bbox_corners[visible, 0]]
                
however, i meet nonzero error when i convert to trt from onnx and the error point to "vox_feat[:, visible] = feature[i, :, dist[visible, 0], bbox_corners[visible, 1], bbox_corners[visible, 0]]" , and i also find you use code like

""
kept = (coor[:, 0] >= 0) & (coor[:, 0] < self.grid_size[0]) & \
           (coor[:, 1] >= 0) & (coor[:, 1] < self.grid_size[1]) & \
           (coor[:, 2] >= 0) & (coor[:, 2] < self.grid_size[2])
    if len(kept) == 0:
        return None, None, None, None, None
    coor, ranks_depth, ranks_feat = \
        coor[kept], ranks_depth[kept], ranks_feat[kept]

"
env:
 tensorrt 8.6
 cuda 11.3
 torch 1.12.1

seems you convert success, haven't you meet nonzero error? any device? thank you

**Comment by HuangJunJie2017** [comment]
@cswwp I haven't met this problem in development. Do you mean that you haven't filterer out the points that are out of scope? And this lead to Nonzero error?

**Comment by cswwp** [comment]
> @cswwp I haven't met this problem in development. Do you mean that you haven't filterer out the points that are out of scope? And this lead to Nonzero error?

No, it indeed filterer out points, but it seems not support when convert to tensorrt from onnx, and i also infer onnx and pth, and the result is normal. It just happen when convert to tensorrt from onnx 😢

**Comment by HuangJunJie2017** [comment]
@cswwp Is converting in float/fp16 mode normal?

**Comment by cswwp** [comment]
@HuangJunJie2017 The error happened when use  "parser.parse(onnx_model.SerializeToString())", and it return false, seems trt not support nonzero operation 

error:
     RuntimeError: Failed to parse onnx, In node 666 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"

and here is node 666 pytorch code 
![image](https://user-images.githubusercontent.com/11901683/227412066-6578678d-d996-4ff6-af12-b6c31f338fe2.png)

**Comment by cswwp** [comment]
> @HuangJunJie2017 The error happened when use "parser.parse(onnx_model.SerializeToString())", and it return false, seems trt not support nonzero operation
> 
> error: RuntimeError: Failed to parse onnx, In node 666 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
> 
> and here is node 666 pytorch code ![image](https://user-images.githubusercontent.com/11901683/227412066-6578678d-d996-4ff6-af12-b6c31f338fe2.png)

seems you use plugin from "https://github.com/HuangJunJie2017/mmdeploy.git" ?


![image](https://user-images.githubusercontent.com/11901683/227412496-d4aa17e8-c9a5-48d6-b369-f7a58415cc7c.png)

**Comment by HuangJunJie2017** [comment]
@cswwp yes，we use plugin to implement the LSS view transformation
