### ISSUE TITLE
tensorrt量化的结果和pytorch原始输出结果差异较大

### ISSUE THREAD

**Issue by zhangjiannan1** [HuangJunJie2017/BEVDet#177]
您好，我这边首先使用convert_bevdet_to_TRT.py这个脚本生成了tensorrt的engine文件，但是在测试tensorrt推理的时候发现其输出结果和pytorch的差异较大，请问这是什么原因呢？

**Comment by zhangjiannan1** [comment]
这是测试的代码
[save_result.txt](https://github.com/HuangJunJie2017/BEVDet/files/11058242/save_result.txt)

**Comment by HuangJunJie2017** [comment]
@zhangjiannan1 差别多大

**Comment by zhangjiannan1** [comment]
我把pytorch和tensorrt的36个输出分别进行了对比，发现最大绝对值误差有超过6，不知道我的测试代码有没有问题，大佬可以先看一下

**Comment by HuangJunJie2017** [comment]
@zhangjiannan1 你可以参考tools/test.py, 把trt输出的结果送评测，我这边经验是bevdet-r50 ptq 掉点在0.5NDS左右

**Comment by zhangjiannan1** [comment]
我这边尝试评测时发现tensorrt的输出shape与pytorch输出的shape不一致，tensorrt输出的结果trt_output是一个长度36的list，其第一个元素trt_output[0]的shape是(6, 2, 128, 128)但是对应的pytorch输出的shape是(1, 2, 128, 128)，请问这可能是什么原因呢

**Comment by HuangJunJie2017** [comment]
@zhangjiannan1 你用benchmark_trt.py时设置 --post-processing 就可以得到预测结果而不是中间结果， 预测结果在这里
https://github.com/HuangJunJie2017/BEVDet/blob/2ae6a02d7a569c5b300a0b57c77ce50bb4e17bc9/tools/analysis_tools/benchmark_trt.py#L167

**Comment by zhangjiannan1** [comment]
我这边尝试过跑这个脚本，但是报了下面的错误：
  File "/opt/conda/lib/python3.8/site-packages/mmdet3d-1.0.0rc4-py3.8-linux-x86_64.egg/mmdet3d/models/dense_heads/centerpoint_head.py", line 754, in get_bboxes
    bboxes = img_metas[i]['box_type_3d'](
IndexError: list index out of range
在debug时发现这个bug的原因就是tensorrt的输出shape与pytorch输出shape不一致引起的，就是我上面提到的问题

**Comment by HuangJunJie2017** [comment]
@zhangjiannan1 改代码了？我还有很多人测试过这个没问题的~

**Comment by zhangjiannan1** [comment]
我这边是拉的最新的代码直接跑的
只运行了下面两个命令：
python tools/convert_bevdet_to_TRT.py configs/bevdet/bevdet-r50.py  bevdet-r50.pth  ./  --fp16

python tools/analysis_tools/benchmark_trt.py configs/bevdet/bevdet-r50.py bevdet_fp16.engine --postprocessing

**Comment by zhangjiannan1** [comment]
我这边是在服务器上测试的A6000的显卡，不知道运行环境不同会不会有影响？
