### ISSUE TITLE
BEVDet with BEVDepth module

### ISSUE THREAD

**Issue by jeho-lee** [HuangJunJie2017/BEVDet#178]
It seems that the BEVDet4D-r50-depth-cbgs model employs the modules from BEVDepth, but there are no checkpoints for BEVDepth-employed BEVDet (not BEVDet"4D").

Can I get this version of model (let's say BEVDet-r50-depth-cbgs)?

Or should I train a new model after replacing the LSSViewTransformer with LSSViewTransformerBEVDepth in the config file?

**Comment by HuangJunJie2017** [comment]
@jeho-lee yes, if you need this configuration, just implement it on your own

**Comment by jeho-lee** [comment]
Thanks for the reply. I'll try that :)

**Comment by jeho-lee** [comment]
I tried to train the BEVDet-r50 with BEVDepth module (i.e., BEVDet-r50-depth). 

And below are the nuscenes val results of BEVDet-r50-_depth_,

![image](https://user-images.githubusercontent.com/70247564/229354386-96d03d80-6124-4124-bccc-cdf240bec09a.png)

According to the [BEVDepth official repo](https://github.com/Megvii-BaseDetection/BEVDepth), BEVDepth-r50 shows 0.3304 mAP and 0.4355 NDS, which is quite different from the results that I got.
The only change in this model is adding BEVDepth's modules. No other configurations.

Any suggestions to reproduce the BEVDepth's results with the BEVDet codebase?
Thanks in advance.

**Comment by cswwp** [comment]
> I tried to train the BEVDet-r50 with BEVDepth module (i.e., BEVDet-r50-depth).
> 
> And below are the nuscenes val results of BEVDet-r50-_depth_,
> 
> ![image](https://user-images.githubusercontent.com/70247564/229354386-96d03d80-6124-4124-bccc-cdf240bec09a.png)
> 
> According to the [BEVDepth official repo](https://github.com/Megvii-BaseDetection/BEVDepth), BEVDepth-r50 shows 0.3304 mAP and 0.4355 NDS, which is quite different from the results that I got. The only change in this model is adding BEVDepth's modules. No other configurations.
> 
> Any suggestions to reproduce the BEVDepth's results with the BEVDet codebase? Thanks in advance.

@jeho-lee I also meet this issue, i write bevdepth as follows
1 write bevdepth class
![image](https://github.com/HuangJunJie2017/BEVDet/assets/11901683/61c8d337-747b-4eee-b12b-9e5fc56b51e7)
2 set config file img_view_transformer = LSSViewTransformerBEVDepth

then i trained the model, and finally eval own dataset, the mAP of bevdepth seems equals to bevdet, no boost, what's your best results now? can you get better result with bevdepth than bevdet?  Any advice? thank you @HuangJunJie2017 @jeho-lee

**Comment by kingofstu** [comment]
> > I tried to train the BEVDet-r50 with BEVDepth module (i.e., BEVDet-r50-depth).
> > And below are the nuscenes val results of BEVDet-r50-_depth_,
> > ![image](https://user-images.githubusercontent.com/70247564/229354386-96d03d80-6124-4124-bccc-cdf240bec09a.png)
> > According to the [BEVDepth official repo](https://github.com/Megvii-BaseDetection/BEVDepth), BEVDepth-r50 shows 0.3304 mAP and 0.4355 NDS, which is quite different from the results that I got. The only change in this model is adding BEVDepth's modules. No other configurations.
> > Any suggestions to reproduce the BEVDepth's results with the BEVDet codebase? Thanks in advance.
> 
> @jeho-lee I also meet this issue, i write bevdepth as follows 1 write bevdepth class ![image](https://private-user-images.githubusercontent.com/11901683/268586927-61c8d337-747b-4eee-b12b-9e5fc56b51e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI0MjcxMDIsIm5iZiI6MTczMjQyNjgwMiwicGF0aCI6Ii8xMTkwMTY4My8yNjg1ODY5MjctNjFjOGQzMzctNzQ3Yi00ZWVlLWIxMmItOWU1ZmM1NmI1MWU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI0VDA1NDAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzOGYzY2NiOWY4YmMxNmUyZjYyMmU2M2RhNGMyZjljNDljMzkzMWFjZWVjZDk0MzllNGM4Y2ZmMmJkZTExMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vekrTwD2ZCjQJN8WcP9r6nATe1DQ7gQ-JaFtujwbXgY) 2 set config file img_view_transformer = LSSViewTransformerBEVDepth
> 
> then i trained the model, and finally eval own dataset, the mAP of bevdepth seems equals to bevdet, no boost, what's your best results now? can you get better result with bevdepth than bevdet? Any advice? thank you @HuangJunJie2017 @jeho-lee

I got the same results with yours, have you solve this problem finally?

**Comment by kingofstu** [comment]
> I tried to train the BEVDet-r50 with BEVDepth module (i.e., BEVDet-r50-depth).
> 
> And below are the nuscenes val results of BEVDet-r50-_depth_,
> 
> ![image](https://user-images.githubusercontent.com/70247564/229354386-96d03d80-6124-4124-bccc-cdf240bec09a.png)
> 
> According to the [BEVDepth official repo](https://github.com/Megvii-BaseDetection/BEVDepth), BEVDepth-r50 shows 0.3304 mAP and 0.4355 NDS, which is quite different from the results that I got. The only change in this model is adding BEVDepth's modules. No other configurations.
> 
> Any suggestions to reproduce the BEVDepth's results with the BEVDet codebase? Thanks in advance.

Hi，for this result， do you use cbgs strategy?
