### ISSUE TITLE
inference on own data

### ISSUE THREAD

**Issue by chrisyan** [HuangJunJie2017/BEVDet#179]
hi,
thank you very much for your work. May I ask how to inference on my own data? suppose I now have 6 images and a lidar data of the same frame, how can I do inference on these data? Any hints would be greatly appreciated.

Best regards
yan

**Comment by HuangJunJie2017** [comment]
@zhiranyan Please refer to https://github.com/HuangJunJie2017/BEVDet/blob/dev2.0/tools/create_data_bevdet.py for an example of preparing data.
