### ISSUE TITLE
The mASE and mAOE is too large

### ISSUE THREAD

**Issue by KeyuLi** [HuangJunJie2017/BEVDet#18]
Thanks  for your great work.
When I training the bevdet with the swinting.py config, I have found the mASE and mAOE is too large in test stage.

the pretrained model you support:
![image](https://user-images.githubusercontent.com/42335923/173024600-b25e8d5f-6943-46ed-8a92-017e498dcc92.png)
the model trained from scratch:
![image](https://user-images.githubusercontent.com/42335923/173024777-1045c5c2-a5d1-4acc-948c-b9f98682eea9.png)

Do you know what could be causing this problem.
best wishes

**Comment by KeyuLi** [comment]
In addition, may I ask how you did the visualization? I want to verify the experimental results by using visualization. The tools/test.py --show have some error when I used.

**Comment by HuangJunJie2017** [comment]
> In addition, may I ask how you did the visualization? I want to verify the experimental results by using visualization. The tools/test.py --show have some error when I used.
An error like this?
RuntimeError: [Open3D ERROR] GLFW Error: X11: The DISPLAY environment variable is missing

**Comment by HuangJunJie2017** [comment]
> Thanks for your great work. When I training the bevdet with the swinting.py config, I have found the mASE and mAOE is too large in test stage.
> 
> the pretrained model you support: ![image](https://user-images.githubusercontent.com/42335923/173024600-b25e8d5f-6943-46ed-8a92-017e498dcc92.png) the model trained from scratch: ![image](https://user-images.githubusercontent.com/42335923/173024777-1045c5c2-a5d1-4acc-948c-b9f98682eea9.png)
> 
> Do you know what could be causing this problem. best wishes

I have upload the training log (in Readme) and suggest you check the loss at first.

**Comment by KeyuLi** [comment]
> > In addition, may I ask how you did the visualization? I want to verify the experimental results by using visualization. The tools/test.py --show have some error when I used.
> 
> An error like this? RuntimeError: [Open3D ERROR] GLFW Error: X11: The DISPLAY environment variable is missing

no, I have solved this problem, the error is "show_results function have an unexpected keyerror show", it seems like a bug from mmdetection3d.

**Comment by KeyuLi** [comment]
> > Thanks for your great work. When I training the bevdet with the swinting.py config, I have found the mASE and mAOE is too large in test stage.
> > the pretrained model you support: ![image](https://user-images.githubusercontent.com/42335923/173024600-b25e8d5f-6943-46ed-8a92-017e498dcc92.png) the model trained from scratch: ![image](https://user-images.githubusercontent.com/42335923/173024777-1045c5c2-a5d1-4acc-948c-b9f98682eea9.png)
> > Do you know what could be causing this problem. best wishes
> 
> I have upload the training log (in Readme) and suggest you check the loss at first.

thanks a lot

**Comment by KeyuLi** [comment]
> > Thanks for your great work. When I training the bevdet with the swinting.py config, I have found the mASE and mAOE is too large in test stage.
> > the pretrained model you support: ![image](https://user-images.githubusercontent.com/42335923/173024600-b25e8d5f-6943-46ed-8a92-017e498dcc92.png) the model trained from scratch: ![image](https://user-images.githubusercontent.com/42335923/173024777-1045c5c2-a5d1-4acc-948c-b9f98682eea9.png)
> > Do you know what could be causing this problem. best wishes
> 
> I have upload the training log (in Readme) and suggest you check the loss at first.

hello, I retrained the model using latest centerpoint_head.py you updated, and the loss is similar to yours in training-log, but the NDS is still smaller than 40, only 30~. Do you have any idea why that might be,thx.

**Comment by HuangJunJie2017** [comment]
@KeyuLi  Large mASE and mAOE may derive from unmatched operation between data preparation in https://github.com/HuangJunJie2017/BEVDet/blob/master/tools/data_converter/nuscenes_converter.py and data post-processing in  https://github.com/HuangJunJie2017/BEVDet/blob/master/mmdet3d/datasets/nuscenes_dataset.py. 
I conjecture that you may use different version of mmdet3d to prepare training data instead of the one BEVDet based on.

**Comment by Pyten** [comment]
@HuangJunJie2017 hello, what should I do if I want to use mmdet3d 1.0 or a newer version, please give me some advice. thx!

**Comment by HuangJunJie2017** [comment]
@Pyten If you have to do that, please check if all modifications relatives with BEVDet are compatible with it……

**Comment by KeyuLi** [comment]
> @KeyuLi Large mASE and mAOE may derive from unmatched operation between data preparation in https://github.com/HuangJunJie2017/BEVDet/blob/master/tools/data_converter/nuscenes_converter.py and data post-processing in https://github.com/HuangJunJie2017/BEVDet/blob/master/mmdet3d/datasets/nuscenes_dataset.py. I conjecture that you may use different version of mmdet3d to prepare training data instead of the one BEVDet based on. Here is the training data i used, you can check this。 https://pan.baidu.com/s/1-o5w0TwvrvQEjFXL5jaQJQ?pwd=fu2x

This is indeed the cause of the problem, thx
