### ISSUE TITLE
How to using cv2.imread() images and using trt_model.forward(dict(img=img, **metas)) to do inference ? 

### ISSUE THREAD

**Issue by lucianzhong** [HuangJunJie2017/BEVDet#180]
According to code in benchmark_trt.py:

    # benchmark with several samples and take the average
    for i, data in enumerate(data_loader):
        if init_:
            inputs = [t.cuda() for t in data['img_inputs'][0]]
            metas_ = model.get_bev_pool_input(inputs)
            metas = dict(
                ranks_bev=metas_[0].int().contiguous(),
                ranks_depth=metas_[1].int().contiguous(),
                ranks_feat=metas_[2].int().contiguous(),
                interval_starts=metas_[3].int().contiguous(),
                interval_lengths=metas_[4].int().contiguous())
            init_ = False
        img = data['img_inputs'][0][0].cuda().squeeze(0).contiguous()
        torch.cuda.synchronize()
        start_time = time.perf_counter()
        trt_output = trt_model.forward(dict(img=img, **metas))

The mode using data_loader as model inputs.
If it is possible to use cv2.imread() to read 6 *.jpg and make it as inputs to model?

**Comment by HuangJunJie2017** [comment]
@lucianzhong of cause, please refer to test_pipeline in 
https://github.com/HuangJunJie2017/BEVDet/blob/2ae6a02d7a569c5b300a0b57c77ce50bb4e17bc9/configs/bevdet/bevdet-r50-cbgs.py#L168  for how data_loader processes inputs.

**Comment by lucianzhong** [comment]
Thanks a lot for quick reply. I will try.
