### ISSUE TITLE
Questions about BEVDet 4D align part

### ISSUE THREAD

**Issue by ytwanghaoyu** [HuangJunJie2017/BEVDet#181]
Hi,

Thanks again for your great work.

While reading the bevdet4d code, I got some questions:

1. Why does BEVDet4D use GT's absolute speed (Use the ground as a reference) * time to calculate distance, instead of relative ego speed  (Use the ego as a reference)  * time, which is more "correct" in the align process.
2. Why do we use complex distance mode, instead of directly predicting speed?
3. This might be an open question, do we have some temporal fusion logic which only uses info like ego movement or even only time stamp differences, to get a higher metric? For example, I'm thinking about self-attention on bev feature level, is that a working method?

**Comment by HuangJunJie2017** [comment]
1 & 2. In cooperation with the temporal sampling augmentation strategy in training.
3. just try it on your own.

**Comment by ytwanghaoyu** [comment]
Thanks for your reply!

> 1 & 2. In cooperation with the temporal sampling augmentation strategy in training.

But I'm still not quite get it, the "temporal sampling augmentation" you mean is the random frame chosen?

I don't see any relation about why not using relative ego speed.

**Comment by ytwanghaoyu** [comment]
![image](https://user-images.githubusercontent.com/25526912/227859346-8c7e9f2a-5be6-48d2-ae62-dfd9021ff009.png)
As shown in your paper, the align will align different frame with a same ego position. But that means the moving distance of object is relative speed * delta time, instead of abs speed * delta time

**Comment by HuangJunJie2017** [comment]
@ytwanghaoyu yes, you are right, we convert abs speed to relative speed here https://github.com/HuangJunJie2017/BEVDet/blob/2919b997c8fb2cb4737fd844200936ef04900d37/tools/data_converter/prepare_nuscenes_for_bevdet4d.py#L93

**Comment by ytwanghaoyu** [comment]
Yes, but It seems like you have convert it back to abs speed in dataset
https://github.com/HuangJunJie2017/BEVDet/blob/2919b997c8fb2cb4737fd844200936ef04900d37/mmdet3d/datasets/nuscenes_dataset.py#L309-L310

https://github.com/HuangJunJie2017/BEVDet/blob/2919b997c8fb2cb4737fd844200936ef04900d37/configs/bevdet4d/bevdet4d-r50.py#L249

**Comment by HuangJunJie2017** [comment]
@ytwanghaoyu Sorry for the mistake. Back to the previous statement:
>As shown in your paper, the align will align different frame with a same ego position. But that means the moving distance of object is relative speed * delta time, instead of abs speed * delta time

After alignment, the object movement in the BEV feature between two adjacent is abs_dis instead of relative_dis, as shown in the right-down subfigure.

**Comment by ytwanghaoyu** [comment]
Thanks again for your patient and kind reply. 🙏🏻 

But still, there are weird things in this process 🤔

After checking the original code, we use frame-to-frame extrinsic to shift the bev feature from adj frame to cur frame. Just like the figure shown. Therefore the static object is at the same position. And for the moving objects, they will be moved with relative distance, which is relative speed * delta time. It's not quite the same as the "abs distance" you say. 

I know the code might be so long ago for you to recall the detail, but they are pretty annoying for readers. But we still want to figure it out

**Comment by HuangJunJie2017** [comment]
>And for the moving objects, they will be moved with relative distance, which is relative speed * delta time. It's not quite the same as the "abs distance" you say.

With respect to the moving objects, they move with abs distance as shown in the left-top subfigure and right-down subfigure.

**Comment by ytwanghaoyu** [comment]
Ohh, I got it. 

Sorry for the mis-understanding

**Comment by ytwanghaoyu** [comment]
Ahh, actually, I'm still not quite get it. Would you like to add my wechat: hibolo, and have a discussion about it when you have some time?
