### ISSUE TITLE
about bev_pool_v2

### ISSUE THREAD

**Issue by hehangtian** [HuangJunJie2017/BEVDet#182]
when I run the comand, and I meet this erro.
pip install openmim 
mim install mmcv-full
mim install mmdet 
mim install mmsegmentation 
git clone https://github.com/open-mmlab/mmdetection3d.git
cd mmdetection3d
pip install -e . 
cd  ./BEVDet
pip install -e . 
python tools/train.py configs/bevdet/bevdet4d-r50-cbgs.py 

from . import bev_pool_v2_ext
ImportError: /BEVDet/mmdet3d/ops/bev_pool_v2/bev_pool_v2_ext.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC2ENS_14SourceLocationENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE

**Comment by HuangJunJie2017** [comment]
@hehangtian  
I haven't met this in development. 

btw, installing mmdetection3d is unnecessary
>git clone https://github.com/open-mmlab/mmdetection3d.git
>cd mmdetection3d
>pip install -e .

**Comment by HuangJunJie2017** [comment]
which pytorch version do you use for experiment?

**Comment by hehangtian** [comment]
> which pytorch version do you use for experiment?

thanks for your replying, I use pytorch1.10 and cuda11.3

**Comment by hehangtian** [comment]
> @hehangtian I haven't met this in development.
> 
> btw, installing mmdetection3d is unnecessary
> 
> > git clone https://github.com/open-mmlab/mmdetection3d.git
> > cd mmdetection3d
> > pip install -e .

yes, I just following the step in start document. It is unnecessary.

**Comment by HuangJunJie2017** [comment]
mmm, check the cuda version consistency?
```
python
>>> import torch
>>> torch.version.cud
>>>exit()
nvcc -V
```

**Comment by hehangtian** [comment]
> mmm, check the cuda version consistency?
> 
> ```
> python
> >>> import torch
> >>> torch.version.cud
> >>>exit()
> nvcc -V
> ```

torch.version.cuda
'11.3'

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0

**Comment by hehangtian** [comment]
I solve the problem with i list of commands:
pip install openmim -i https://pypi.tuna.tsinghua.edu.cn/simple/
mim install mmcv-full -i https://pypi.tuna.tsinghua.edu.cn/simple/
mim install mmdet -i https://pypi.tuna.tsinghua.edu.cn/simple/
mim install mmsegmentation -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install pycuda     lyft_dataset_sdk     networkx==2.2     numba==0.53.0     numpy     nuscenes-devkit     plyfile     scikit-image     tensorboard     trimesh==2.35.39 -i https://pypi.tuna.tsinghua.edu.cn/simple  --ignore-installed llvmlite
apt-get update
apt install libgl1-mesa-glx
apt-get install libglib2.0-dev
pip install torchvision==0.11.2 -i https://pypi.tuna.tsinghua.edu.cn/simple/
cd BEVDet
python setup.py develop
pip install opencv_python==3.4.10.37 -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install numpy==1.23.5 -i https://pypi.tuna.tsinghua.edu.cn/simple/
pip install setuptools==59.5.0 -i https://pypi.tuna.tsinghua.edu.cn/simple/
python3 -m pip install --user protobuf==3.20.1 -i https://pypi.tuna.tsinghua.edu.cn/simple/

**Comment by hehangtian** [comment]
But I don't know the reason of this problem...

**Comment by HuangJunJie2017** [comment]
nice, anyway, thanks very much for you to share the aforementioned information.
