### ISSUE TITLE
After execute train.py with --resume-from,get error.

### ISSUE THREAD

**Issue by lucianzhong** [HuangJunJie2017/BEVDet#183]
After execute train.py with --resume-from,get error.
python tools/train.py configs/bevdet/bevdet-r50.py --resume-from /home/work/BEVDet/BEVDet/checkpoints/bevdet-r50.pth

File "/home/nvidia/archiconda3/envs/mmdeploy_bev/lib/python3.6/site-packages/mmcv/runner/base_runner.py", line 374, in resume
    self._epoch = checkpoint['meta']['epoch']
KeyError: 'meta'

Please have a look. 
By the way, I want to fine-tune the model with my own dataset. How should I create my own dataset ?

**Comment by lucianzhong** [comment]
My guess is that having not save bevdet-r50.pth with ['meta'] during train. 

Is bevdet-r50.pth with ['meta'] avaliable somewhere ?

Appreciate for you time.

**Comment by HuangJunJie2017** [comment]
@lucianzhong  
1.the provided pth file is purified. try not to resume from it and use load_from instead
2.please refer to https://github.com/HuangJunJie2017/BEVDet/blob/dev2.0/tools/create_data_bevdet.py for how data is processed

**Comment by lucianzhong** [comment]
Got it. Thanks a lot

**Comment by 123mutouren-lhq** [comment]
> Got it. Thanks a lot

hello,do you realize the load_from function,can give some help
