### ISSUE TITLE
请问BEVDet-Gamma在每张显卡batch size为8的情况下，训练大约占用多少显存？

### ISSUE THREAD

**Issue by LCH1238** [HuangJunJie2017/BEVDet#184]
24G显存够不够用？

**Comment by HuangJunJie2017** [comment]
@LCH1238 We trained BEVDet-Gamma with 4 * 8 3090 and batch size 2

**Comment by LCH1238** [comment]
> @LCH1238 We trained BEVDet-Gamma with 4 * 8 3090 and batch size 2

谢谢，请问这样的设备训练BEVDet-Gamma大约需要多长时间？

**Comment by HuangJunJie2017** [comment]
@LCH1238 3天左右，一般八九个epoch就饱和了

**Comment by LCH1238** [comment]
谢谢！

**Comment by LCH1238** [comment]
> @LCH1238 3天左右，一般八九个epoch就饱和了

谢谢！
