### ISSUE TITLE
About the detailed KPI of BEVDet4D-R50-cbgs

### ISSUE THREAD

**Issue by hehangtian** [HuangJunJie2017/BEVDet#186]
Dear author, I am doing Bevdet-related research recently. Could you please provide detailed evaluation values of the bevdet4d model? Models such as bevdet-r50 are also needed if available. Thank you. Thank you very much.

**Comment by HuangJunJie2017** [comment]
@hehangtian In dev2.1, detailed evaluation values have been attached to the top of the config file.
