### ISSUE TITLE
Migrate BEVDet to MMEngine ? 

### ISSUE THREAD

**Issue by xavierjimenezp** [HuangJunJie2017/BEVDet#187]
Currently, BEVDet utilizes the MMCV runner, which lacks support for new functionalities like FSDP distributed training. One possible solution could be to migrate the project to MMEngine.

Would you consider the possibility of migrating the project to MMEngine as a potential solution?

**Comment by HuangJunJie2017** [comment]
@xavierjimenezp FSDP is an attractive feature, I would like to consider building the next-generation BEVDet based on MMEngine.
