### ISSUE TITLE
Why we generally need cbgs training for ViT backbone?

### ISSUE THREAD

**Issue by synsin0** [HuangJunJie2017/BEVDet#188]
I find that most BEV algorithms with Swin backbone adopts a CBGS training strategy(e.g. your early config bevdet-sttiny.py and Swin-L in GeoMIM). And I find that without CBGS the mAP drops drastically, but it is not the case for BEVFormer with Resnet-101 or V2-99. I wonder why we need cbgs for ViT. Could you provide some insights on this issue. Thanks a lot.

**Comment by HuangJunJie2017** [comment]
@synsin0 They rely on the FCOS3D pre-train for accelerating the convergency.

**Comment by synsin0** [comment]
Get! I will try to train Swin on FCOS3D first. By the way, in another issue you show fast convergence of R50 without cbgs initialized from torchvision by changing a different optimizer, does it also apply to ViT backbone?

**Comment by HuangJunJie2017** [comment]
@synsin0 which issue?

**Comment by synsin0** [comment]
issue56: https://github.com/HuangJunJie2017/BEVDet/issues/56

**Comment by HuangJunJie2017** [comment]
@synsin0  grad clip can offer faster convergency, but still not enough for training bevdet with 24 epoch and pretrained on imagenet.

**Comment by synsin0** [comment]
Thanks for your response.
