### ISSUE TITLE
关于bevdet4d 训练问题

### ISSUE THREAD

**Issue by fengguibinyn** [HuangJunJie2017/BEVDet#189]
def extract_img_feat(self,
                         img,
                         img_metas,
                         pred_prev=False,
                         sequential=False,
                         **kwargs):
什么情况下需要 把 pred_prev 和 sequential 设置成true 谢谢

**Comment by HuangJunJie2017** [comment]
@fengguibinyn when you use tools/analysis_tools/benchmark_sequential.py

**Comment by crisz94** [comment]
> @fengguibinyn when you use tools/analysis_tools/benchmark_sequential.py

@HuangJunJie2017 This question bothers me too, so sequential and pred_prev only set to true in tools/analysis_tools/benchmark_sequential.py? In the training process these two params will be false by default?

**Comment by HuangJunJie2017** [comment]
@crisz94 yes

**Comment by crisz94** [comment]
> @crisz94 yes

@HuangJunJie2017 Thanks for your reply! I'll check it out again

**Comment by aqr1961** [comment]
黄博士您好，之前我在测试推理速度时，没有把 pred_prev 和 sequential 设置成true。我想知道，这样测试出来的推理速度是否是可以接受的，还是会产生较大的影响呢？

**Comment by aqr1961** [comment]
在2.1版本中  如果改为True，则遇到了这样的报错信息，设置为false则正常
/etc/BEVDet-dev2.1# python tools/analysis_tools/benchmark_sequential.py configs/bevdet/bevdet-r50-4d-cbgs.py ckpts/bevdet-r50-4d-cbgs.pth --fuse-conv-bn 
/root/anaconda3/envs/openmmlab/lib/python3.8/site-packages/mmdet/models/backbones/resnet.py:401: UserWarning: DeprecationWarning: pretrained is deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is deprecated, '
load checkpoint from local path: ckpts/bevdet-r50-4d-cbgs.pth
Traceback (most recent call last):
  File "tools/analysis_tools/benchmark_sequential.py", line 114, in <module>
    main()
  File "tools/analysis_tools/benchmark_sequential.py", line 80, in main
    feat_prev, inputs = model.module.extract_img_feat(
  File "/etc/BEVDet-dev2.1/mmdet3d/models/detectors/bevdet.py", line 457, in extract_img_feat
    return self.extract_img_feat_sequential(img, kwargs['feat_prev'])
KeyError: 'feat_prev'

**Comment by gaowei724** [comment]
> @crisz94 yes

您好，请问训练过程默认不开sequential的话，历史帧bev_feat是在哪里对齐到当前帧的呢？（我运行的配置是python train.py bevdet-r50-4dlongterm-cbgs.py），我看了代码似乎只有sequential时候才会调用extract_img_feat_sequential在这个函数里才会调用shift_feature函数，而我运行的配置里跳过了特征对齐的操作，是不需要还是说我忽略了什么关键代码？

**Comment by BozhouZha** [comment]
> > @crisz94 yes
> 
> 您好，请问训练过程默认不开sequential的话，历史帧bev_feat是在哪里对齐到当前帧的呢？（我运行的配置是python train.py bevdet-r50-4dlongterm-cbgs.py），我看了代码似乎只有sequential时候才会调用extract_img_feat_sequential在这个函数里才会调用shift_feature函数，而我运行的配置里跳过了特征对齐的操作，是不需要还是说我忽略了什么关键代码？

Same question here, did you figure it out?

**Comment by smilezxq** [comment]
> > [@crisz94](https://github.com/crisz94) yes
> 
> 您好，请问训练过程默认不开sequential的话，历史帧bev_feat是在哪里对齐到当前帧的呢？（我运行的配置是python train.py bevdet-r50-4dlongterm-cbgs.py），我看了代码似乎只有sequential时候才会调用extract_img_feat_sequential在这个函数里才会调用shift_feature函数，而我运行的配置里跳过了特征对齐的操作，是不需要还是说我忽略了什么关键代码？

same question too
