### ISSUE TITLE
Question about BEV Augmentation

### ISSUE THREAD

**Issue by kaixinbear** [HuangJunJie2017/BEVDet#19]
In the paper description, the bev aug operation is implemented by changing feature and gt simultaneously.

> In practice, the operations are conducted both on the output feature of the view transformer and the 3D object detection targets to keep their spatial consistency.

However, in the code base, I can only find bev flip code in class RandomFlip3D, in mmdet3d/datasets/pipelines/transforms_3d.py , which change project matrix and gt simultaneously in the dataloader.

So I am confused about the inconsistency between the paper and code.

**Comment by HuangJunJie2017** [comment]
@kaixinbear You should checkout all changes in this file through the initial commit of BEVDet

**Comment by kaixinbear** [comment]
I check the changes but can't find explict augmentation code for bev feature.Could you please send me a quote for this code?

**Comment by HuangJunJie2017** [comment]
@kaixinbear all changes in this file are designed for modifying the bev feature in data augmentation

**Comment by gaojunbin** [comment]
I also have the same question. In the code, it seems that the data augmentation of bev is achieved by adjusting the external matrix of camera and the ground truth, without explicitly processing bev feature. 
Is this equivalent,?or where is my understanding wrong. Thanks.

**Comment by HuangJunJie2017** [comment]
@gaojunbin yes，adjusting the point cloud in view transformer is more precise than adjusting the bev feature

**Comment by gaojunbin** [comment]
> @gaojunbin yes，adjusting the point cloud in view transformer is more precise than adjusting the bev feature

I see. Thank you.
