### ISSUE TITLE
坐标系转换以及多模融合模型相关

### ISSUE THREAD

**Issue by WangJian981002** [HuangJunJie2017/BEVDet#190]
感谢您精彩的工作！

  近期我准备基于您的工作复现一下BEVFusion，在关于坐标系方面有一些疑问希望得到您的解答！

  请问在Bevdet-dev2.0 codebase中，最后生成的bev feature是在什么什么坐标系下？（ego vehicle frame？ camera frame? ..）
  我注意到mmdet3d中基于lidar的3d检测所生成的annotation(3d_gt_bboxs)是在lidar坐标系下的。而Bevdet-dev2.0所读取的anno来自于bevdetv2-nuscenes_infos_train.pkl，如果我想在lidar coords. sys.下生成来在image stream的bev feature，应该注意到哪些部分呢？

**Comment by WangJian981002** [comment]
经过将3d_gt_bboxs和lidar point进行可视化后我发现现在的Bevdet-dev2.0应该是将annos转到ego frame下（defined by IMU?）

那么请问现在训练每一帧的时间戳是基于camera frame确定的还是lidar frame?

**Comment by lilkeker** [comment]
> 经过将3d_gt_bboxs和lidar point进行可视化后我发现现在的Bevdet-dev2.0应该是将annos转到ego frame下（defined by IMU?）
> 
> 那么请问现在训练每一帧的时间戳是基于camera frame确定的还是lidar frame?
Hello, I also want to reproduce bevfuison on the basis of bevdet4d, can you provide the contact information, I have some questions and want to communicate with yo

**Comment by lilkeker** [comment]
> 经过将3d_gt_bboxs和激光雷达点进入可视觉化后我发现现在的Bevdet-dev2.0应该是将annos转到ego frame下（由IMU确定？）
> 
> 那请问现在在训练每一屏的时候决定是基于相框框架确定的还是激光雷达框架？

并且我也遇见了和您一样的问题，我将预训练好的 tranfusion-lidar (纯点云输入模型)在bevdetdev2.0的环境下eval也得到了相同的问题，Map=0 ,我排查过point_cloud_range等超参数的配置，但是好像也是得用高版本的mmdet3d重新生成pkl文件，（还没有具体尝试是不是这个原因）
![image](https://user-images.githubusercontent.com/81810465/230782115-0d02df19-66f3-44e7-a728-fb0e84dd4f77.png)

**Comment by WangJian981002** [comment]
> 



> > 经过将3d_gt_bboxs和激光雷达点进入可视觉化后我发现现在的Bevdet-dev2.0应该是将annos转到ego frame下（由IMU确定？）
> > 那请问现在在训练每一屏的时候决定是基于相框框架确定的还是激光雷达框架？
> 
> 并且我也遇见了和您一样的问题，我将预训练好的 tranfusion-lidar (纯点云输入模型)在bevdetdev2.0的环境下eval也得到了相同的问题，Map=0 ,我排查过point_cloud_range等超参数的配置，但是好像也是得用高版本的mmdet3d重新生成pkl文件，（还没有具体尝试是不是这个原因） ![image](https://user-images.githubusercontent.com/81810465/230782115-0d02df19-66f3-44e7-a728-fb0e84dd4f77.png)

这个问题我是用官方的mmdet3d文件时出现的，导致的原因是评测时所用的pkl文件是在mmdet3d1.0.0之前的版本生成的，我用1.0.0rc4重新生成以后就好了。

不过即使你重新生成新的pkl文件，在该repo下（bevdetdev2.0）仍然会产生map=0的结果。原因如下：
官方mmdet3d的annos是基于LIDAR坐标系下的，而bevdetv2.0的每一帧样本是基于自车坐标系的，并且默认CAM_FRONT所采集时的时间。
直接用pretained tranfusion-lidar的预测结果与评测的gt不在同一坐标系

**Comment by lilkeker** [comment]
> 

所以现在解决办法只有在bevdetdev2下重新训练一个transfusion吗？(T＿T)

**Comment by HuangJunJie2017** [comment]
建议用ego吧，因为评测时评测范围应该以ego中心

**Comment by lilkeker** [comment]
> > 
> 
> > > 经过将3d_gt_bboxs和激光雷达点进入可视觉化后我发现现在的Bevdet-dev2.0应该是将annos转到ego frame下（由IMU确定？）
> > > 那请问现在在训练每一屏的时候决定是基于相框框架确定的还是激光雷达框架？
> > 
> > 
> > 并且我也遇见了和您一样的问题，我将预训练好的 tranfusion-lidar (纯点云输入模型)在bevdetdev2.0的环境下eval也得到了相同的问题，Map=0 ,我排查过point_cloud_range等超参数的配置，但是好像也是得用高版本的mmdet3d重新生成pkl文件，（还没有具体尝试是不是这个原因） ![image](https://user-images.githubusercontent.com/81810465/230782115-0d02df19-66f3-44e7-a728-fb0e84dd4f77.png)
> 
> 这个问题我是用官方的mmdet3d文件时出现的，导致的原因是评测时所用的pkl文件是在mmdet3d1.0.0之前的版本生成的，我用1.0.0rc4重新生成以后就好了。
> 
> 不过即使你重新生成新的pkl文件，在该repo下（bevdetdev2.0）仍然会产生map=0的结果。原因如下： 官方mmdet3d的annos是基于LIDAR坐标系下的，而bevdetv2.0的每一帧样本是基于自车坐标系的，并且默认CAM_FRONT所采集时的时间。 直接用pretained tranfusion-lidar的预测结果与评测的gt不在同一坐标系

您好，按照你的提示我利用bevdet_dev2中的'bevdetv2-nuscenes_infos_train.pkl'训练transfusion,并且test_data_config的时候也用的这个annfile ,并且我在train_pipeline和test_pipeline中加入了将'point'由lidar 系转到ego 系的过程，训练了三个epoch 后验证map 和Nds 仍然0,请问你知道为什么吗?您的回答将对我非常有帮助，谢谢！
![image](https://user-images.githubusercontent.com/81810465/231238528-757bd638-e808-47c6-b110-579cfc162f07.png)
![image](https://user-images.githubusercontent.com/81810465/231238727-3363d123-a8c7-4b27-a830-5977d2f41a20.png)
![image](https://user-images.githubusercontent.com/81810465/231238923-7580989b-baa5-4125-b483-38d6cfab2884.png)

**Comment by WangJian981002** [comment]
> > > 
> > 
> > 
> > > > 经过将3d_gt_bboxs和激光雷达点进入可视觉化后我发现现在的Bevdet-dev2.0应该是将annos转到ego frame下（由IMU确定？）
> > > > 那请问现在在训练每一屏的时候决定是基于相框框架确定的还是激光雷达框架？
> > > 
> > > 
> > > 并且我也遇见了和您一样的问题，我将预训练好的 tranfusion-lidar (纯点云输入模型)在bevdetdev2.0的环境下eval也得到了相同的问题，Map=0 ,我排查过point_cloud_range等超参数的配置，但是好像也是得用高版本的mmdet3d重新生成pkl文件，（还没有具体尝试是不是这个原因） ![image](https://user-images.githubusercontent.com/81810465/230782115-0d02df19-66f3-44e7-a728-fb0e84dd4f77.png)
> > 
> > 
> > 这个问题我是用官方的mmdet3d文件时出现的，导致的原因是评测时所用的pkl文件是在mmdet3d1.0.0之前的版本生成的，我用1.0.0rc4重新生成以后就好了。
> > 不过即使你重新生成新的pkl文件，在该repo下（bevdetdev2.0）仍然会产生map=0的结果。原因如下： 官方mmdet3d的annos是基于LIDAR坐标系下的，而bevdetv2.0的每一帧样本是基于自车坐标系的，并且默认CAM_FRONT所采集时的时间。 直接用pretained tranfusion-lidar的预测结果与评测的gt不在同一坐标系
> 
> 您好，按照你的提示我利用bevdet_dev2中的'bevdetv2-nuscenes_infos_train.pkl'训练transfusion,并且test_data_config的时候也用的这个annfile ,并且我在train_pipeline和test_pipeline中加入了将'point'由lidar 系转到ego 系的过程，训练了三个epoch 后验证map 和Nds 仍然0,请问你知道为什么吗?您的回答将对我非常有帮助，谢谢！ ![image](https://user-images.githubusercontent.com/81810465/231238528-757bd638-e808-47c6-b110-579cfc162f07.png) ![image](https://user-images.githubusercontent.com/81810465/231238727-3363d123-a8c7-4b27-a830-5977d2f41a20.png) ![image](https://user-images.githubusercontent.com/81810465/231238923-7580989b-baa5-4125-b483-38d6cfab2884.png)

建议可视化一下转换后的点云和gt_bboxes是否对应，排查一下是不是坐标转换过程的错先

**Comment by jhzhang19** [comment]
@lilkeker  你好，最后你通过PointToEGO这个过程实现点云与图像融合了吗？
