### ISSUE TITLE
difference between bevdet4d and bevdet4d depth

### ISSUE THREAD

**Issue by ahnz7** [HuangJunJie2017/BEVDet#191]
hallo,
thank you very much for your work. I have a question between bevdet4d and bevdet4d-depth. I notice that in bevdet4d-depth there is a special depth loss. In original bevdet4d we have already trained the depth loss by the 3d infos. why do we need another loss for depth?

**Comment by HuangJunJie2017** [comment]
@ahnz7  please refer to BEVDepth(https://arxiv.org/abs/2206.10092) for reasoning.

**Comment by ahnz7** [comment]
> @ahnz7 please refer to BEVDepth(https://arxiv.org/abs/2206.10092) for reasoning.

thx
