### ISSUE TITLE
关于BEV的数据增强，为什么可以改变lidar points的scale

### ISSUE THREAD

**Issue by imyyf** [HuangJunJie2017/BEVDet#193]
从配置文件的161行可以看出
https://github.com/HuangJunJie2017/BEVDet/blob/b17b6e85b3243ef2eaf3a05102e333cb4b7e830b/configs/bevdepth/bevdepth4d-r50.py#L161
会对Lidar points 的坐标乘上一个系数，这种增强方法有什么缘由吗，最初是谁提出来的呀。而且乘上系数后，等于改变点的位置了，那么point_cloud_range这个参数需要相关的调整吗，还是只在https://github.com/HuangJunJie2017/BEVDet/blob/b17b6e85b3243ef2eaf3a05102e333cb4b7e830b/mmdet3d/datasets/pipelines/transforms_3d.py#L679 679行修改对应的变换矩阵就行了。

**Comment by HuangJunJie2017** [comment]
@imyyf 
BEVDet inherit it from CenterPoint 
point_cloud_range need not be modified in data augmentation
