### ISSUE TITLE
BEVDet和BEVDepth

### ISSUE THREAD

**Issue by ahnz7** [HuangJunJie2017/BEVDet#195]
你好，上次你建议我去看BEVDepth相关的论文，我有去阅读，但依然有一个疑惑。在原始的BEVDet中经过bevdet模型之后我们得到的dim中的x和y分别是基于激光雷达坐标系下的值，我的理解y就是所谓的深度信息，在做loss的时候已经计算过了。不知道这样的理解是否正确？如果没有错误，那么在BEVDet4DDepth中增加的一个Depth_loss是否和原始的BEVDet计算深度损失（也就是y）重复了？亦或者直接用lidar进行显式的训练效果会更好？

**Comment by HuangJunJie2017** [comment]
@ahnz7 depth supervision from lidar is better than that from the target, from the perspective of generalization.

**Comment by ahnz7** [comment]
> @ahnz7 depth supervision from lidar is better than that from the target, from the perspective of generalization.

Thank you for your prompt reply
