### ISSUE TITLE
Missing Checkpoint in Master branch

### ISSUE THREAD

**Issue by ZLTJohn** [HuangJunJie2017/BEVDet#196]
Thank you for sharing the BEVDet series code! However I find bevdet checkpoints are missing in [master branch](https://github.com/HuangJunJie2017/BEVDet/tree/master). There is no checkpoint files in the [google link](https://drive.google.com/drive/folders/1VnJv-dNb6-gkKTq7uC_Q6YsRq_q3NI-t?usp=sharing) so I can not verify your code in my environment. Could you please fix this issue?

**Comment by HuangJunJie2017** [comment]
@ZLTJohn 
The master branch is deprecated. Please use the latest branch dev2.1 instead~

**Comment by ZLTJohn** [comment]
Thank you for your quick reply!
Yes. I've used the latest branch, and the checkpoints are good.
In fact, I'm modifying bevdet based on [your PR](https://github.com/open-mmlab/mmdetection3d/pull/1952)  for latest mmdet3d, in order to do experiments in the latest mmdet3d, and it's clear that that PR is based on your  [master branch](https://github.com/HuangJunJie2017/BEVDet/tree/master). However, I failed to reproduce the result of [bevdet_r50.py](https://github.com/HuangJunJie2017/BEVDet/blob/master/configs/bevdet/bevdet-r50.py), so I'm asking if the checkpoint of bevdet-r50.py in master branch is available or not.

**Comment by HuangJunJie2017** [comment]
@ZLTJohn URL of the pre-trained model/log in the master branch has been updated. Only the fp16 version can be retrieved from the local disk. good luck~

**Comment by ZLTJohn** [comment]
Thanks a lot. ^_^
