### ISSUE TITLE
AssertionError: bev_pool_v2 is not in the plugin list of tensorrt, please install mmdeploy from https://github.com/HuangJunJie2017/mmdeploy.git

### ISSUE THREAD

**Issue by RaSungryong** [HuangJunJie2017/BEVDet#197]
I convert the model to TensorRT by this command
python tools/convert_bevdet_to_TRT.py configs/bevdet/bevdet-r50-cbgs.py checkpoint/bevdet-r50-cbgs.pth work_dir --fuse-conv-bn --fp16 --int8

Traceback (most recent call last):
  File "tools/convert_bevdet_to_TRT.py", line 452, in <module>
    main()
  File "tools/convert_bevdet_to_TRT.py", line 300, in main
    assert 'bev_pool_v2' in get_plugin_names(), \
AssertionError: bev_pool_v2 is not in the plugin list of tensorrt, please install mmdeploy from https://github.com/HuangJunJie2017/mmdeploy.git

cuda ： 11.3
TensorRT： 8.2.3
What is the reason？

**Comment by HuangJunJie2017** [comment]
@RaSungryong have you properly installed mmdeploy from https://github.com/HuangJunJie2017/mmdeploy.git?

**Comment by RaSungryong** [comment]
@HuangJunJie2017 Yes, I installed it according to the steps. But I don't know why it happened, so I'm going to reinstall it.

**Comment by HuangJunJie2017** [comment]
@RaSungryong if you do not use a docker, try to follow the instruction in dockerfile to install mmdeploy https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/docker/Dockerfile

**Comment by cyn-liu** [comment]
@RaSungryong Hi:
Have you solved this problem?
I install the mmdeploy form [https://github.com/HuangJunJie2017/mmdeploy](https://github.com/HuangJunJie2017/mmdeploy), but this problem is still arise.
