### ISSUE TITLE
The output format

### ISSUE THREAD

**Issue by tonyyang1995** [HuangJunJie2017/BEVDet#2]
Hello, Thanks for sharing the paper. Since you are using BEV space for the final detection, so I am wondering whether the output from your network should be under bev bin imgs (the same as Lift-splat-shoot). So when you do the evaluation, do you need to project the bev outputs back to each images?

**Comment by HuangJunJie2017** [comment]
The output should be transformed into the world coordinate system, where the ground truth actually defined in. @tonyyang1995
