### ISSUE TITLE
作者你好，请问sample_bda_augmentation这个数据增强方案是怎么发挥作用的呢？

### ISSUE THREAD

**Issue by WeiSQ-zju** [HuangJunJie2017/BEVDet#200]
我看到配置文件里给了bda_aug_conf的参数，然后在LoadAnnotationsBEVDepth类里对gt_boxes做了变换，然后在view_transformer中对lidar坐标做了变换，但是我不太理解他是怎么发挥作用的，您能帮我解释一下吗

**Comment by HuangJunJie2017** [comment]
不能，建议弃坑

**Comment by WeiSQ-zju** [comment]
是我的问题太简单大佬不愿意回答，还是这个问题不重要没必要去纠结呀

**Comment by HuangJunJie2017** [comment]
拒绝回答，这种不想花时间看代码的人才会提出来的问题

**Comment by WeiSQ-zju** [comment]
哈哈哈哈哈哈，好的吧，你是大佬你说啥都对

**Comment by northeastsquare** [comment]
https://github.com/HuangJunJie2017/BEVDet/issues/380
参考一下
