### ISSUE TITLE
Could you share c++ version of model inference by tensorrt ? 

### ISSUE THREAD

**Issue by JarveeLee** [HuangJunJie2017/BEVDet#201]
Thanks for your great contribution ! 
It would be great if you can share code to inference BEVDet tensorrt model, because this model seems to require multiple and sequential inputs and multiple outputs, whose outputs are part of inputs for next frame, I feel it difficult to re-write tools/analysis_tools/benchmark_trt.py in c++ version ....

**Comment by JarveeLee** [comment]
This is really a complex model .....

**Comment by HuangJunJie2017** [comment]
@JarveeLee A complex model? I wonder which model you compare to？

**Comment by JarveeLee** [comment]
compare to a simple yolox with just one 2d image input .... which is easy to perform c++ inference in tensorrt

**Comment by HuangJunJie2017** [comment]
@JarveeLee 
mmm, the task is more complicated, just be patient in deployment. 
It is impossible for me to write and release a C++ version.

**Comment by JarveeLee** [comment]
OK I understand, I will try harder with more patience ......

**Comment by LCH1238** [comment]
[bevdet-tensorrt-cpp](https://github.com/LCH1238/bevdet-tensorrt-cpp)

**Comment by LCH1238** [comment]
[bevdet-tensorrt-cpp](https://github.com/LCH1238/bevdet-tensorrt-cpp) You can refer to this code.
