### ISSUE TITLE
BEVDet和BEVDet4d中是否涉及transformer技术

### ISSUE THREAD

**Issue by aqr1961** [HuangJunJie2017/BEVDet#206]
请问BEVDET  BEVDET4D网络是否涉及了transformer相关技术，在哪里用到了这方面的技术了呢。只要涉及到了一点点就可以。

**Comment by HuangJunJie2017** [comment]
@aqr1961  We use the transformer only in the backbone Swin-transformer.

**Comment by aqr1961** [comment]
非常感谢 所以说 BEVDET-R50等相关模型 虽然有view transformer模块 但实际上并未使用transformer相关技术吧

**Comment by HuangJunJie2017** [comment]
@aqr1961 yes
