### ISSUE TITLE
TypeError: class `VoxelNet`

### ISSUE THREAD

**Issue by Neiizo** [HuangJunJie2017/BEVDet#207]
Hi. I wanted to test your code, but I was stuck at the [verification step](https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/docs/en/getting_started.md). 

First, I didn't have the same files as in the github, for some reasons. For instances, I had to create the checkpoints folder, and then the data from the corresponding github page, and in configs/second, my files weren't the same. Mine were called second_hv... where as on github it's the opposite. It's hv_second....
After manually downloading the matching file, I tried to run the command, and was met with the following error

```
(base) C:\Users\XXX\mmdetection3d>python demo/pcd_demo.py demo/data/kitti/000008.bin configs/second/hv_second_secfpn_6x8_80e_kitti-3d-car.py checkpoints/hv_second_secfpn_6x8_80e_kitti-3d-car_20200620_230238-393f000c.pth
Traceback (most recent call last):
  File "C:\Users\XXX\miniconda3\lib\site-packages\mmengine\registry\build_functions.py", line 121, in build_from_cfg
    obj = obj_cls(**args)  # type: ignore
TypeError: VoxelNet.__init__() got an unexpected keyword argument 'voxel_layer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXX\mmdetection3d\demo\pcd_demo.py", line 60, in <module>
    main(args)
  File "C:\Users\XXX\mmdetection3d\demo\pcd_demo.py", line 34, in main
    model = init_model(args.config, args.checkpoint, device=args.device)
  File "c:\users\XXX\mmdetection3d\mmdet3d\apis\inference.py", line 68, in init_model
    model = MODELS.build(config.model)
  File "C:\Users\XXX\miniconda3\lib\site-packages\mmengine\registry\registry.py", line 545, in build
    return self.build_func(cfg, *args, **kwargs, registry=self)
  File "C:\Users\XXX\miniconda3\lib\site-packages\mmengine\registry\build_functions.py", line 241, in build_model_from_cfg
    return build_from_cfg(cfg, registry, default_args)
  File "C:\Users\XXX\miniconda3\lib\site-packages\mmengine\registry\build_functions.py", line 135, in build_from_cfg
    raise type(e)(
TypeError: class `VoxelNet` in mmdet3d/models/detectors/voxelnet.py: VoxelNet.__init__() got an unexpected keyword argument 'voxel_layer'
```

After looking online, I couldn't find someone with a matching error.
Do you know what could've caused this?

Also, I'm sorry. I tried following the issue's template given [here](https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/docs/en/faq.md), but the link isn't working anymore, and I couldn't find it in the given github repo.

Thanks a lot,
Neizo

**Comment by HuangJunJie2017** [comment]
@Neiizo just skip this and validate this repo by inference bevdet with the provided checkpoint.
e.g. python tools/test.py configs/bevdet/bevdet-r50.py $checkpoint --eval mAP
if you are not that familiar with mmdetection3d please refer to the official one for running these demos.

**Comment by Neiizo** [comment]
Hi, thanks for the reply. We've been trying a lot of things since, but we can't anything to work, wether it's on the mmdetection3d side, or with the command you have provided. For your command, the error I get is 
```
Traceback (most recent call last):
  File "tools/test.py", line 8, in <module>
    from mmcv import Config, DictAction
ImportError: cannot import name 'Config' from 'mmcv' (C:\Users\Neizo\miniconda3\envs\openmmlab\lib\site-packages\mmcv\__init__.py)
```
I found a way to fix it, and it was to change to `from mmengine.config import Config`, but then, other issues arose.
we've been looking for answers everywhere, but nothing has been successful, that's why I'm coming back to you. May I be missing something ?

**Comment by HuangJunJie2017** [comment]
@Neiizo please install mmcv-full==1.5.3 mmdet==2.25.0 mmsegmentation==0.25.0

**Comment by Neiizo** [comment]
Hi ! Thanks for the quick reply. I just ran each command with mim install mmcv-full==1.5.3, and the same for the others. However, I got a warning with mmdet:

```
Using cached `mminstall.txt` for mmdet==2.25.0: C:\Users\XXX\.cache\mim\mminstall\mmdet==2.25.0.txt
Get 'mim' extra requirements from `mminstall.txt` for mmdet 2.25.0: ['mmcv-full>=1.3.17'].
```

followed by

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mmdet3d 1.1.0 requires mmdet<3.1.0,>=3.0.0, but you have mmdet 2.25.0 which is incompatible. 
```
I still tried and run the command, and got the following error

```
**Traceback (most recent call last):
  File "tools/test.py", line 15, in <module>
    from mmdet3d.apis import single_gpu_test
  File "c:\users\neizo\bevdet-dev2.1\mmdetection3d\mmdet3d\__init__.py", line 21, in <module>
    assert (mmcv_version >= digit_version(mmcv_minimum_version)
AssertionError: MMCV==1.5.3 is used but incompatible. Please install mmcv>=2.0.0rc4, <2.1.0.**
```

so I'm a little confused...

**Comment by HuangJunJie2017** [comment]
mmdet3d 1.1.0 should not be installed.
