### ISSUE TITLE
Checkpoints link

### ISSUE THREAD

**Issue by GKrafft2** [HuangJunJie2017/BEVDet#208]
Hi,

Is there a google drive link to get the model checkpoints ?

thanks

**Comment by HuangJunJie2017** [comment]
@GKrafft2 
checkpoints for dev2.1
https://drive.google.com/drive/folders/1JMEla_XRpbsPTXMogcZ6xC6lVm51bgFf?usp=sharing
checkpoints for dev2.0
https://drive.google.com/drive/folders/1Dh2FbEChbfhIaBHimPP4jbibs8XjJ5rx?usp=sharing
