### ISSUE TITLE
关于时序融合问题

### ISSUE THREAD

**Issue by fengguibinyn** [HuangJunJie2017/BEVDet#209]
您好，在readme中和代码中，时序融合采用了历史8帧，请问这个历史帧数量在训练和推理时是否要保持一致？readme中给出的fps和nds是采用多少历史帧进行融合预测的呢

**Comment by HuangJunJie2017** [comment]
@fengguibinyn longterm with 8 frames and default with 1 frame. training and testing are kept consistent.
