### ISSUE TITLE
What is the difference between 'gt_boxes' and 'ann_infos' in the data ? 

### ISSUE THREAD

**Issue by JarveeLee** [HuangJunJie2017/BEVDet#210]
Thanks for your great contribution ! After running create_data_bevdet.py I can get bevdetv2-nuscenes_infos_train.pkl and bevdetv2-nuscenes_infos_val.pkl, I notice both in 'gt_boxes' and 'ann_infos' there exists some 3d boxes. 

'gt_boxes' is loaded in mmdet3d/datasets/nuscenes_dataset.py -> def get_ann_info(self, index) -> gt_bboxes_3d = info['gt_boxes']
while 
'ann_infos' is loaded in mmdet3d/datasets/pipelines/loading.py -> class LoadAnnotationsBEVDepth(object) -> gt_boxes, gt_labels = results['ann_infos']

They are quite different both in values and numbers, what is the difference between these two groups of 3d boxes ?

**Comment by HuangJunJie2017** [comment]
@JarveeLee 
We only use 'ann_infos'. 
'gt_boxes' is needless, I will remove this in revision.

**Comment by JarveeLee** [comment]
Because I don't know which group of 3d boxes is the gt to train models.

**Comment by JarveeLee** [comment]
Thanks !!!!!
