### ISSUE TITLE
Test Time Augmentation Code implementation question？

### ISSUE THREAD

**Issue by bamboo188** [HuangJunJie2017/BEVDet#211]
Hello, Thanks for your great contribution!

I've been very interested in 3d detect TTA recently and have tried flipping, rotating and scaling in the image view and flipping and scaling in the bev view based on the bevdet 2.0 branch, respectively. The details are set as follows:

* In bevdet4d-r50-depth-cbgs model,  in the image view: horizontal flip , rotation angle is  2/2.7/ 4 respectively, and in the bev view the horizontal and vertical flip, scale=0.97.

* The bevdet4d-r50-depth-cbgs model was retrained with the input_size increased to (640, 1600) and tested at multiple scales. The scales are 1088, 1536, and 1760, respectively, and the aspect ratio is maintained.

Unfortunately, only the image view no tta+flip has a 0.0011 improvement (from 0.5229 to 0.5240), and the other TTA fusions have a reduction of about 0.002-0.01. Compared to the result of your paper: BEVDet4D-Base has a 0.007 improvement, it seems that my implementation is so bad. However, since the difference between the TTA result and the original result is not large, I guess that there is no big problem with the code.

So, I would like to ask you: 

* Do you think my above TTA results are reasonable? If not, could you give me some suggestions please?
* Can you share what specific methods your TTA includes in the image view and BEV view, such as flip,double flip, rotate and scale?
* When fusing multiple TTA results over nms, is nms still used or is WBF (weighted box fusion) used?
* Does multiscale testing need to increase the resize range of the image view during training?

**Comment by HuangJunJie2017** [comment]
@bamboo188
I use imge flip/ scale 0.96/1.0/1.04(1.0 means the default size in test without tta)/ bev hflip/vflip
When you use bev flip, please refer to my previous work [UDP](https://github.com/HuangJunJie2017/UDP-Pose) to avoid the discretization error.
