### ISSUE TITLE
Estimate the inference speed of BEVDet的探讨

### ISSUE THREAD

**Issue by aqr1961** [HuangJunJie2017/BEVDet#212]
# with pre-computation acceleration
python tools/analysis_tools/benchmark.py $config $checkpoint --fuse-conv-bn
# 4D with pre-computation acceleration
python tools/analysis_tools/benchmark_sequential.py $config $checkpoint --fuse-conv-bn
# view transformer only
python tools/analysis_tools/benchmark_view_transformer.py $config $checkpoint
使用三种方式衡量模型的推理速度   得到了各不相同的结果 请问您的MD文件中使用的是哪种推理方式测评model 的推理速度呢？另外，这三种模型的推理速度测试方式有什么区别吗，主要是把官方的推理过程用自己的代码来实现吗？

**Comment by HuangJunJie2017** [comment]
@aqr1961  
第一个是用来测3D的模型的
第二个用来测带时序建模4D模型的
第三个只测视角变换模块推理速度

**Comment by aqr1961** [comment]
尊敬的黄博士您好，我在使用这行代码进行视角变换模块推理速度测试时，python tools/analysis_tools/benchmark_view_transformer.py configs/bevdet/bevdet-r50-4d-depth-cbgs.py ckpts/bevdet-r50-4d-depth-cbgs.pth  ， Traceback (most recent call last):
  File "tools/analysis_tools/benchmark_view_transformer.py", line 141, in <module>
    fps = main()
  File "tools/analysis_tools/benchmark_view_transformer.py", line 78, in main
    x = depth_net(img_feat.reshape(B * N, C, H, W))
  File "/root/anaconda3/envs/openmmlab2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'mlp_input'（出现了上述报错信息），请问网络方面是否还需要进行调整呢？

**Comment by HuangJunJie2017** [comment]
@aqr1961  use configs/bevdet/bevdet-r50.py instead

**Comment by aqr1961** [comment]
好的，非常感谢您的回复。

**Comment by HuangJunJie2017** [comment]
@aqr1961  Yes, I have added an assertion in the revision.
