### ISSUE TITLE
Config for benchmark

### ISSUE THREAD

**Issue by jianingwangind** [HuangJunJie2017/BEVDet#214]
Thanks for sharing the great work!

I was wondering, it would be great if you could also share the training config files and checkpoints for nuscenes leaderboard version which achieves 0.586 map and 0.664 nds.

Looking forward to your reply

**Comment by HuangJunJie2017** [comment]
@jianingwangind will be released in the next week. The release one may not be bevdet-gamma,  an upgraded version with stereo depth instead.
