### ISSUE TITLE
Checkpoint link of Occupancy Prediction models

### ISSUE THREAD

**Issue by ngoductuanlhp** [HuangJunJie2017/BEVDet#216]
Hi @HuangJunJie2017,

Thanks for sharing this great work. Could you share the Google Drive link of the checkpoint of this model [BEVDet-Occ-STBase-4D-Stereo-2x](https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/configs/bevdet_occ/bevdet-occ-stbase-4d-stereo-512x1408-24e.py) (in the Nuscene Occupancy Prediction task).

I'm looking forward to hearing back from you. Thank you very much.

**Comment by HuangJunJie2017** [comment]
@ngoductuanlhp 
 https://drive.google.com/drive/folders/1JMEla_XRpbsPTXMogcZ6xC6lVm51bgFf?usp=sharing

**Comment by ngoductuanlhp** [comment]
Great! Thank you so much, @HuangJunJie2017.

**Comment by haiphamcse** [comment]
Hi @HuangJunJie2017,

Thanks for sharing the above pretrained weights. However, i notice a config is missing in the Google Drive folder [**BEVDet-STBase-4D-Stereo-512x1408-CBGS](https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/configs/bevdet/bevdet-stbase-4d-stereo-512x1408-cbgs.py)**. Can you please add it to the Google Drive link.
I'm looking forward to hearing back from you. Thank you very much.
