### ISSUE TITLE
如何提升推理速度

### ISSUE THREAD

**Issue by aqr1961** [HuangJunJie2017/BEVDet#217]
尊敬的黄博士您好，我对您的工作十分感兴趣  我也使用了3090 GPU进行推理速度的测试  但是在实际实验中  推理速度始终比您给出的要低一些；并且我的GPU 利用率和显卡占用率都比较低，请问是否可以扩大线程数和batchsize来提升推理速度，请问您在推理测试时也使用了默认的配置吗？

**Comment by HuangJunJie2017** [comment]
@aqr1961 your inference speed is ?

**Comment by aqr1961** [comment]
大约是您速度的60+%，使用bevdet-r50配置时 ，推理速度是22.5 fps

**Comment by HuangJunJie2017** [comment]
@aqr1961 I do use batch 1 for inference speed estimation. Have you checked the inference speed of each module? network/postprocessing/total with 29.1/4.2/33.3 ms?

**Comment by aqr1961** [comment]
那请问，推理速度是否会受到CPU等硬件设施的影响，或者您是否有尝试过更改默认配置来提高推理速度？

**Comment by HuangJunJie2017** [comment]
@aqr1961 Haven't, just pull the code and test it on the machine from Tencent cloud with the docker built from https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/docker/Dockerfile

**Comment by aqr1961** [comment]
好的，非常感谢您的帮助

**Comment by aqr1961** [comment]
> @aqr1961 I do use batch 1 for inference speed estimation. Have you checked the inference speed of each module? network/postprocessing/total with 29.1/4.2/33.3 ms?

您好，我还没有尝试这样操作过，我没有在您提供的代码中找到分别测量的接口，请问您是如何拆分网络部分来分别测量的呢？是否是将模型的骨干网络（backbone）作为网络部分，将检测头（bbox_head）作为后处理部分。
# build the model and load checkpoint
model = build_detector(cfg.model, test_cfg=cfg.get('test_cfg'))
fp16_cfg = cfg.get('fp16', None)
if fp16_cfg is not None:
    wrap_fp16_model(model)
load_checkpoint(model, args.checkpoint, map_location='cpu')

# separate the model into network and postprocessing
network = model.backbone
postprocessing = model.bbox_head
利用类似于上述的代码进行测量的呢
