### ISSUE TITLE
mmdeploy安装问题

### ISSUE THREAD

**Issue by aqr1961** [HuangJunJie2017/BEVDet#218]
黄博士您好，之前按照您的gte_start.md文件配置环境时，使用的是cuda11.0 并安装了与之对应的pytorch1.7.1；但是在安装mmdeploy这个模块时，官方mmdeploy需要安装tensorrt8.2.3（与tensorrt8.2.3版本对应的是cuda11.1版本），这是否会产生不兼容；还是说我应该安装您提供的mmdeploy而不是官方的实现版本？

**Comment by HuangJunJie2017** [comment]
1.please following https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/docker/Dockerfile to prepare your environment
2.cuda11.3 and pytorch==1.10.0  are recommended. the other versions haven't been verified
3.please install mmdeploy as that in https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/docker/Dockerfile
