### ISSUE TITLE
I think getting_started.md could be better

### ISSUE THREAD

**Issue by GG-Bonds** [HuangJunJie2017/BEVDet#219]
Bevdet is a really great project. But I think his `getting_started.md` can be improved to help others install better.😊

The versions of **mmcv** and **mmdetection3d** are not clearly described in getting_started.md. This confuses everyone and wastes a lot of unnecessary time. 🤝

I know `mmdet3d/__init__.py` has limited version of mmcv. But it still doesn't tell the version of mmdetection3d, I hope the author can show us the version of mmcv and mmdetection3d in `getting_started.md`. 

Thanks！🌹

**Comment by HuangJunJie2017** [comment]
@GG-Bonds Thanks for your suggestion. Getting start has been updated.
