### ISSUE TITLE
Can't inference by the master code

### ISSUE THREAD

**Issue by pycoco** [HuangJunJie2017/BEVDet#22]
Thanks for your error report and we appreciate it a lot.

**Describe the bug**
Core dump. After inference  around 4000 samples
![image](https://user-images.githubusercontent.com/11053628/173504372-75d4947f-59f8-4434-8430-6284bf1a216d.png)

**Reproduction**
```
python tools/test.py ./configs/bevdet/bevdet-sttiny.py ./bevdet-sttiny-pure.pth --eval bbox
```

**Environment**
```
TorchVision: 0.9.1+cu111
OpenCV: 4.5.5
MMCV: 1.4.0
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.0
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.2+f0647e7
```

**Comment by HuangJunJie2017** [comment]
First time to seen this error. Have you monitored the CPU memory to check if out of memory? 
By the way, it seems that you are evaluating bevdet-tiny on the nuscenes test set?

**Comment by pycoco** [comment]
> First time to seen this error. Have you monitored the CPU memory to check if out of memory? By the way, it seems that you are evaluating bevdet-tiny on the nuscenes test set?

The cpu memory is ok. And i evaluate  bevdet-tiny on the  nuscenes test set.  Now i don't find the reason. Any suggestions?

**Comment by pycoco** [comment]
> First time to seen this error. Have you monitored the CPU memory to check if out of memory? By the way, it seems that you are evaluating bevdet-tiny on the nuscenes test set?

The cpu memory is ok. And i evaluate  bevdet-tiny on the  nuscenes test set.  Now i don't find the reason. Any suggestions?

**Comment by HuangJunJie2017** [comment]
Is that ok on the nuscenes val set?

**Comment by pycoco** [comment]
> Is that ok on the nuscenes val set?

Also core dump.
![image](https://user-images.githubusercontent.com/11053628/173512633-ea95b0fd-7856-490e-9304-290342b71901.png)

**Comment by HuangJunJie2017** [comment]
Emmm. It seems your environment is not that stable. You can manually split the dataset into pieces and combine the result of each piece.

**Comment by pycoco** [comment]
> Emmm. It seems your environment is not that stable. You can manually split the dataset into pieces and combine the result of each piece.

Thanks for your quick response. i will have a try . Also i can run BEVFusion without any error.  It's such a curious problem.
