### ISSUE TITLE
about align_after_view_transfromation in bevdet4d

### ISSUE THREAD

**Issue by GG-Bonds** [HuangJunJie2017/BEVDet#220]
I found that the results of `align_after_view_transfromation` being True or False in bevdet4d are not much different.

May I ask the author, how should I interpret this result?

I think that after aligning the features, the accuracy should be higher according to common sense.

**Comment by HuangJunJie2017** [comment]
@GG-Bonds Instead, 'False' means align within view transformation.

**Comment by crisz94** [comment]
> @GG-Bonds Instead, 'False' means align within view transformation.

@HuangJunJie2017 Hello, I can't find any clue about "align within view transformation". It seems that LSSViewTransformer can only project img features to bev of current frame. I'm really confused about it. Could you please explain about the question, thanks!

**Comment by crisz94** [comment]
> @GG-Bonds Instead, 'False' means align within view transformation.

@HuangJunJie2017

In my opinion, if you want to "align within view transformation", the matrix "sensor2ego" of adjacent frames should be the transfromation from sensor of adjacent frame to ego of current frame. But it seems that the sensor2ego matrix of adjacent frames still are the transfromation from sensor of adjacent frame to ego of adjacent frame. It's really confused..

**Comment by Agito555** [comment]
> > @GG-Bonds Instead, 'False' means align within view transformation.
> 
> @HuangJunJie2017
> 
> In my opinion, if you want to "align within view transformation", the matrix "sensor2ego" of adjacent frames should be the transfromation from sensor of adjacent frame to ego of current frame. But it seems that the sensor2ego matrix of adjacent frames still are the transfromation from sensor of adjacent frame to ego of adjacent frame. It's really confused..

Me too. It is also hard for me to figure out. Do you figure it out?
