### ISSUE TITLE
Experimental configuration problem

### ISSUE THREAD

**Issue by aqr1961** [HuangJunJie2017/BEVDet#222]
Dear Dr. Huang, I am very interested in your work. In your article, you mentioned that you used a 3090 GPU for the experiment on Tencent Cloud. I would like to know more about other hardware configurations, such as the CPU model information you used.

**Comment by HuangJunJie2017** [comment]
@aqr1961 Intel(R) Xeon(R) Platinum 8255C CPU @ 2.50GHz

**Comment by aqr1961** [comment]
Thank you very much for your reply. Wish you all the best in your research.
