### ISSUE TITLE
how to train custom dataset

### ISSUE THREAD

**Issue by cswwp** [HuangJunJie2017/BEVDet#225]
Thank you for so great job, and i want to know how to train custom dataset? Do you mind give some advice?

**Comment by cswwp** [comment]
@HuangJunJie2017 Thank you for nice work again. Finally it seems work for my own dataset After few days brain storm. now it's training and loss seems normal. The devil is in the details. All your need is vscode debug 😄

**Comment by RunpuWei** [comment]
> @HuangJunJie2017 Thank you for nice work again. Finally it seems work for my own dataset After few days brain storm. now it's training and loss seems normal. The devil is in the details. All your need is vscode debug 😄

Could you please tell me how to build a custom dataset? I found that the mmdet3d official documentation is not very clear.

**Comment by czwbbbbb** [comment]
Hello, how did you build your own dataset, I would like to know the specific steps, thank you very much.

**Comment by cswwp** [comment]
> Quote reply
> Refer

Sorry, i just notice it now. All you need is to rewrite your dataset.py in mmdet3d/datasets/ direction, define your 3d bbox, intrinsic parameters and extrinsic parameters, please reference mmdet3d/datasets/nuscenes_dataset.py
