### ISSUE TITLE
where can I find your paper

### ISSUE THREAD

**Issue by promesse** [HuangJunJie2017/BEVDet#226]
Thanks

**Comment by promesse** [comment]
![image](https://user-images.githubusercontent.com/26239060/236465936-2a450a79-7241-4c15-8d76-1a040fb2dd2d.png)
By the way, here's your range settings. But in the cvpr occ challenge, the range should be like below.
Why are you setting it like this?
![image](https://user-images.githubusercontent.com/26239060/236466550-461c9efb-4c65-4627-94c9-c1fc73ad768f.png)

**Comment by promesse** [comment]
![image](https://user-images.githubusercontent.com/26239060/236466784-58ea701f-a7d0-4527-8df4-7ef78b7ea3c2.png)
What do 3x36epoch 3 mean in the settings?

**Comment by promesse** [comment]
Thank you for your great job!

**Comment by HuangJunJie2017** [comment]
@promesse 
No technique report for the occupancy task by far. I will consider this in the future work.
x is a common measurement of the schedule length in the detection task. 1 x = 12epoch.
