### ISSUE TITLE
Why add "self.cv_frustum" var without usage?

### ISSUE THREAD

**Issue by qihao-plus** [HuangJunJie2017/BEVDet#227]
https://github.com/HuangJunJie2017/BEVDet/blob/5c9fc44076b0716a5bf662355ccf6eeca831986a/mmdet3d/models/necks/view_transformer.py#L799

**Comment by qihao-plus** [comment]
The downsample is set as 4 for `self.cv_frustum`
The downsample is set as 16 for `self.frustum`

**Comment by HuangJunJie2017** [comment]
@qihao-plus 
here https://github.com/HuangJunJie2017/BEVDet/blob/5c9fc44076b0716a5bf662355ccf6eeca831986a/mmdet3d/models/detectors/bevdet.py#LL613C73-L613C73

**Comment by qihao-plus** [comment]
Thx!
