### ISSUE TITLE
I can not get the same map and nds with you

### ISSUE THREAD

**Issue by FDInSky** [HuangJunJie2017/BEVDet#228]
your results:
![image](https://user-images.githubusercontent.com/48318485/236596751-47639a34-88f1-404b-82e5-79cde16f9ac0.png)
my results:
![image](https://user-images.githubusercontent.com/48318485/236596759-4a7f1bbf-ccb4-4f9e-a444-5adb3c30f798.png)

**Comment by HuangJunJie2017** [comment]
@FDInSky Please check the loss consistency with the released one.
