### ISSUE TITLE
Depth loss reports stable errors after training some epochs.

### ISSUE THREAD

**Issue by pmj110119** [HuangJunJie2017/BEVDet#229]
During the training process using `depth_loss`, I encountered a strange problem:
some configs only slightly adjust the `loss_weight`, and after training for some epochs (the start of epoch 2) , they will report stable errors.

Due to the error reported during the training process, it is very difficult to locate the problem. 

May I ask the author if there are any implicit crash conditions for the depth loss in the current code?

**Error log:**

```
operator(): block: [536,0,0], thread: [0,0,0] Assertion `input_val >= zero && input_val <= one` failed.

File "/mmdet3d/models/detectors/bevdet_occ.py", line 470, in forward_train
   loss_depth = self.img_view_transformer.get_depth_loss(gt_depth, depth)
File "/opt/conda/envs/py38t191/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 205, in new_func
     return old_func(*args, **kwargs)
File "/mmdet3d/models/necks/view_transformer.py", line 778, in get_depth_loss
     ).sum() / max(1.0, fg_mask.sum())
RuntimeError: CUDA error: device-side assert triggered
```

**Code:**
```
@force_fp32()
    def get_depth_loss(self, depth_labels, depth_preds):
        depth_labels = self.get_downsampled_gt_depth(depth_labels)
        depth_preds = depth_preds.permute(0, 2, 3,
                                          1).contiguous().view(-1, self.D)
        fg_mask = torch.max(depth_labels, dim=1).values > 0.0
        depth_labels = depth_labels[fg_mask]
        depth_preds = depth_preds[fg_mask]
        with autocast(enabled=False):
            depth_loss = F.binary_cross_entropy(
                depth_preds,
                depth_labels,
                reduction='none',
            ).sum() / max(1.0, fg_mask.sum())
        return self.loss_depth_weight * depth_loss
```

**Comment by Silmeria112** [comment]
Did you solve this issue? I have same problem when I turn on fp16 mode.

**Comment by HuangJunJie2017** [comment]
fp16 is deprecated in this project. Especially on the configs with depth supervision from lidar.

**Comment by zhanghm1995** [comment]
@pmj110119 Have you solved the fp16 problems now? I also encounter this error when using fp16.

**Comment by stduent-vehicle** [comment]
> During the training process using `depth_loss`, I encountered a strange problem: some configs only slightly adjust the `loss_weight`, and after training for some epochs (the start of epoch 2) , they will report stable errors.
> 
> Due to the error reported during the training process, it is very difficult to locate the problem.
> 
> May I ask the author if there are any implicit crash conditions for the depth loss in the current code?
> 
> **Error log:**
> 
> ```
> operator(): block: [536,0,0], thread: [0,0,0] Assertion `input_val >= zero && input_val <= one` failed.
> 
> File "/mmdet3d/models/detectors/bevdet_occ.py", line 470, in forward_train
>    loss_depth = self.img_view_transformer.get_depth_loss(gt_depth, depth)
> File "/opt/conda/envs/py38t191/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 205, in new_func
>      return old_func(*args, **kwargs)
> File "/mmdet3d/models/necks/view_transformer.py", line 778, in get_depth_loss
>      ).sum() / max(1.0, fg_mask.sum())
> RuntimeError: CUDA error: device-side assert triggered
> ```
> 
> **Code:**
> 
> ```
> @force_fp32()
>     def get_depth_loss(self, depth_labels, depth_preds):
>         depth_labels = self.get_downsampled_gt_depth(depth_labels)
>         depth_preds = depth_preds.permute(0, 2, 3,
>                                           1).contiguous().view(-1, self.D)
>         fg_mask = torch.max(depth_labels, dim=1).values > 0.0
>         depth_labels = depth_labels[fg_mask]
>         depth_preds = depth_preds[fg_mask]
>         with autocast(enabled=False):
>             depth_loss = F.binary_cross_entropy(
>                 depth_preds,
>                 depth_labels,
>                 reduction='none',
>             ).sum() / max(1.0, fg_mask.sum())
>         return self.loss_depth_weight * depth_loss
> ```

this maybe help: depth_preds = torch.clamp(depth_preds,0,1)
