### ISSUE TITLE
Question about the original points of velocity in labels

### ISSUE THREAD

**Issue by JarveeLee** [HuangJunJie2017/BEVDet#232]
Hi Junjie, I am confused about the velocity of vehicles in labels. Is it in global coordinates or in ego coordinates, or something else ? 

1 If in ego coordinates in NuScenes I found some cars stayed stationary along side streets whose velocity is (0,0) while ego is moving forward.... That conflicts with this guess.

2 If in global coordinates, without ego2global input, how can model predict velocity in global coordinates ... ?

**Comment by HuangJunJie2017** [comment]
@JarveeLee In dev2.1, we use the ego coordinate of the 'current frame'. The history feature with the ego coordinate of the 'history frame', will be aligned into the same coordinate('current frame'). So, the static object in the feature map is static, as illustrated in the down-right image of:
![image](https://user-images.githubusercontent.com/31001081/236728524-04bdb6d6-1e7f-41a4-ab4f-94c9ebe30c12.png)

**Comment by JarveeLee** [comment]
So you mean the velocity, the values are the same as those in global coordinates , but the direction is in ego coordinate .. ? I am not sure, is Velocity_label = Velocity_global @ global2ego.rotation, feed Velocity_label to train models ? 

For example, if a car is stationary 0m/s, Velocity_global, while ego is moving 5m/s forward, in labels this car is 0m/s or -5m/s ?

**Comment by HuangJunJie2017** [comment]
@JarveeLee Velocity_label = Velocity_global @ global2ego.rotation, feed Velocity_label to train models 
that's right

**Comment by JarveeLee** [comment]
Thanks ! Got it !
