### ISSUE TITLE
Strategies of preparing dataset for bevdet4d

### ISSUE THREAD

**Issue by ZhixiongSun** [HuangJunJie2017/BEVDet#233]
Hi, Thanks for your great job.
I have found that there is a   [max_adj](https://github.com/HuangJunJie2017/BEVDet/blob/master/tools/data_converter/prepare_nuscenes_for_bevdet4d.py#L12) param
I want to ask why we need this or what's the purpose of generate the "sweeps" for each sample.
Could you please explain the main purpose of this [add_adj_info](https://github.com/HuangJunJie2017/BEVDet/blob/master/tools/data_converter/prepare_nuscenes_for_bevdet4d.py#L10) function. 
Thanks in advance.

**Comment by HuangJunJie2017** [comment]
@ZhixiongSun Please use dev2.1 instead, as the master branch is deprecated.
