### ISSUE TITLE
Can't reproduce bevdet-r50 test mAP and NDS

### ISSUE THREAD

**Issue by xXuHaiyang** [HuangJunJie2017/BEVDet#234]
Thanks for your error report and we appreciate it a lot.

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

Can't reproduce bevdet-r50 test mAP and NDS, you report in the github repo as 28.3 and 35.0 but I get 27.4 and 32.9. The env and the dataset is in alignment with yours, and the checkpoint is download from the baidudisk link of yours. 

**Reproduction**

1. What command or script did you run?

```
./tools/dist_test.sh ./configs/bevdet/bevdet-r50.py ./ckpts/bevdet-r50.pth 4 --eval mAP
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?

No.

4. What dataset did you use?

Generate by `python tools/create_data_bevdet.py`

**Environment**

```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA A10
CUDA_HOME: /usr/local/cuda-11.4
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.10.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX512
  - CUDA Runtime 11.3
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.2
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.11.0
OpenCV: 4.7.0
MMCV: 1.5.3
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.3
MMDetection: 2.25.1
MMSegmentation: 0.25.0
MMDetection3D: 1.0.0rc4+
spconv2.0: False
```

**Error traceback**
![WX20230510-141547@2x](https://github.com/HuangJunJie2017/BEVDet/assets/77454392/8f72499b-c1e6-4b9e-a918-8b9c58a96e2b)

```
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by wjxzju** [comment]
> Thanks for your error report and we appreciate it a lot.
> 
> **Checklist**
> 
> 1. I have searched related issues but cannot get the expected help.
> 2. The bug has not been fixed in the latest version.
> 
> **Describe the bug**
> 
> Can't reproduce bevdet-r50 test mAP and NDS, you report in the github repo as 28.3 and 35.0 but I get 27.4 and 32.9. The env and the dataset is in alignment with yours, and the checkpoint is download from the baidudisk link of yours.
> 
> **Reproduction**
> 
> 1. What command or script did you run?
> 
> ```
> ./tools/dist_test.sh ./configs/bevdet/bevdet-r50.py ./ckpts/bevdet-r50.pth 4 --eval mAP
> ```
> 
> 2. Did you make any modifications on the code or config? Did you understand what you have modified?
> 
> No.
> 
> 4. What dataset did you use?
> 
> Generate by `python tools/create_data_bevdet.py`
> 
> **Environment**
> 
> ```
> fatal: not a git repository (or any parent up to mount point /)
> Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
> sys.platform: linux
> Python: 3.8.16 (default, Mar  2 2023, 03:21:46) [GCC 11.2.0]
> CUDA available: True
> GPU 0,1,2,3: NVIDIA A10
> CUDA_HOME: /usr/local/cuda-11.4
> GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
> PyTorch: 1.10.0
> PyTorch compiling details: PyTorch built with:
>   - GCC 7.3
>   - C++ Version: 201402
>   - Intel(R) oneAPI Math Kernel Library Version 2023.1-Product Build 20230303 for Intel(R) 64 architecture applications
>   - Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
>   - OpenMP 201511 (a.k.a. OpenMP 4.5)
>   - LAPACK is enabled (usually provided by MKL)
>   - NNPACK is enabled
>   - CPU capability usage: AVX512
>   - CUDA Runtime 11.3
>   - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
>   - CuDNN 8.2
>   - Magma 2.5.2
>   - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.3, CUDNN_VERSION=8.2.0, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.10.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
> 
> TorchVision: 0.11.0
> OpenCV: 4.7.0
> MMCV: 1.5.3
> MMCV Compiler: GCC 7.3
> MMCV CUDA Compiler: 11.3
> MMDetection: 2.25.1
> MMSegmentation: 0.25.0
> MMDetection3D: 1.0.0rc4+
> spconv2.0: False
> ```
> 
> **Error traceback** ![WX20230510-141547@2x](https://user-images.githubusercontent.com/77454392/237295986-8f72499b-c1e6-4b9e-a918-8b9c58a96e2b.png)
> 
> ```
> A placeholder for trackback.
> ```
> 
> **Bug fix** If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

I have the same result with you，NDS=0.3285, mAP=0.2744

**Comment by jekyll88** [comment]
Got the same result, NDS=0.3285, mAP=0.2744
I used the bev2.1 checkpoint, not sure why the result is similar as bev2.0.

**Comment by HuangJunJie2017** [comment]
@xXuHaiyang @wjxzju @jekyll88 
Sorry, I mistook the epoch_20_ema.pth for epoch_25_ema.pth.
I have fixed this by replacing epoch_20_ema.pth with epoch_25_ema.pth.
Please download the checkpoint and test again.
