### ISSUE TITLE
Can not run test.py, why?

### ISSUE THREAD

**Issue by SimLuo2014** [HuangJunJie2017/BEVDet#235]
when i run test.py, it fails as follow:
Traceback (most recent call last):
  File "tools/test.py", line 8, in <module>
    from mmcv import Config, DictAction
ImportError: cannot import name 'Config' from 'mmcv'

how to fix the above problem?

**Comment by superprogrammai** [comment]
You can try to use mmcv-full == 1.6.0

**Comment by SimLuo2014** [comment]
thanks, it run OK by using lower version of mmcv-full.
