### ISSUE TITLE
Mini-version of Nuscenes Dataset

### ISSUE THREAD

**Issue by SMSajadi99** [HuangJunJie2017/BEVDet#237]
Hello everyone!

Tnx for sharing your helpful project.

I have started working on your Github. However, I want to run the code with mini-version of the Nuscenes dataset. In all part of your code, only the full dataset is used. Since, I have three questions!

1- I want to know that, is it possible to run the code with mini-version?
2- Also, is it possible to generate the .`pkl `files with `mmdetection`? Or, can you provide it on your Github?
3- Are `sweeps `data (I mean non-annotated frames) necessary for your training algorithm? Or, just by the keyframes we can run the training code.

Thank you.

**Comment by HuangJunJie2017** [comment]
@SMSajadi99 
mini-version is deprecated in this project.
please refer to the instructions in README.md for the usage of this project.
