### ISSUE TITLE
How to get pre-trained weights other than Baido pan.

### ISSUE THREAD

**Issue by Ino-Ichan** [HuangJunJie2017/BEVDet#238]
Hi BEVDet team,

Thank you for publishing such a great work.

I would like to try the pre-trained models for the occupancy task, but I am unable to create a Biadu pan account and download the pre-trained model weights.
Is there any way other than Baidu pan that you can provide the pre-trained weights?

Regards

**Comment by HuangJunJie2017** [comment]
@Ino-Ichan https://drive.google.com/drive/folders/1JMEla_XRpbsPTXMogcZ6xC6lVm51bgFf

**Comment by Ino-Ichan** [comment]
@HuangJunJie2017 
Thank you very much! I appreciate your quick response!

**Comment by SenaKorkut** [comment]
Hi, 
I think google drive link does not work anymore. Is there any other platform where we can download the pretrained models? I am having trouble downloading something from baidu.
