### ISSUE TITLE
Understanding/debugging temporal alignment

### ISSUE THREAD

**Issue by polo5** [HuangJunJie2017/BEVDet#239]
Hello,

Thanks for the great repo. I notice that using `align_after_view_transfromation=True` doesn't seem to help performance. This portion of the code (https://github.com/HuangJunJie2017/BEVDet/blob/f71858d02eb0fbd09860150ade67558d7984b1be/mmdet3d/models/detectors/bevdet.py#L290) is both quite hard to understand and hard to debug. 

I'm wondering how you checked that your implementation was correct, and if you have any high level explanation of the steps you're doing here. Different BEV all have their own way of implementing feature alignment and I expect that this should improve performance if properly implemented, but it's hard to check this step visually...

Thanks!

**Comment by lilkeker** [comment]
use 'python tools/test.py $config $checkpoint --eval mAP **--no-aavt**' instead may help performance
