### ISSUE TITLE
BEVDet无cbgs模型的学习率设置问题

### ISSUE THREAD

**Issue by LCH1238** [HuangJunJie2017/BEVDet#241]
您好，这篇工作特别出色！在学习率方面我有一个疑惑：cbgs模型的学习率设置都为dict(type='AdamW', lr=2e-4, weight_decay=1e-2)，但是非cbgs模型的学习率设置为dict(type='AdamW', lr=2e-4, weight_decay=1e-07)，为什么要设置1e-7这么小的学习率衰减呢？

**Comment by HuangJunJie2017** [comment]
@LCH1238 https://github.com/Megvii-BaseDetection/BEVDepth/issues/24
