### ISSUE TITLE
Pre-trained model of Occ-models

### ISSUE THREAD

**Issue by toyot-li** [HuangJunJie2017/BEVDet#242]
@HuangJunJie2017 Hi, when I check the occ log bevdet-occ-stbase-4d-stereo-512x1408-24e.log, I find that in the "unexpected key in source state_dict", there is nothing with the prefix "pts_bbox_head". I would like to make sure do you `load from` the detection model "bevdet-stbase-4d-stereo-512x1408-cbgs.pth" as specified in the config file?

**Comment by HuangJunJie2017** [comment]
@zen-d yes, 'unexpected key in source state_dict' is normal as the pre-trained pth is from detection task while the current task is occupancy.
