### ISSUE TITLE
one error in prepareimageinputs(obj)

### ISSUE THREAD

**Issue by leslie27ch** [HuangJunJie2017/BEVDet#243]
dev2.0 branch 
in function  get_sensor2ego_transformation
cam_name indicate sweepsensor , while ego_cam indicate keysensor，
but you use cam_name as index to get keysensor rot and tran.

![图片](https://github.com/HuangJunJie2017/BEVDet/assets/49723499/81664e46-9fa3-46f9-9caa-2ade2cc8dd0d)

**Comment by HuangJunJie2017** [comment]
@leslie27ch sweepsensor2keyego use ego_cam as key ego, while keysensor2sweepsensor use cam_name as key ego.
