### ISSUE TITLE
BEVDet-STBase-4D-Stereo-512x1408-CBGS Google Drive path

### ISSUE THREAD

**Issue by haiphamcse** [HuangJunJie2017/BEVDet#245]
> Hi @HuangJunJie2017,
> 
> Thanks for sharing the pretrained weights. However, i notice a config is missing in the Google Drive folder [**BEVDet-STBase-4D-Stereo-512x1408-CBGS](https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/configs/bevdet/bevdet-stbase-4d-stereo-512x1408-cbgs.py)**. Can you please add it to the Google Drive link. I'm looking forward to hearing back from you. Thank you very much.

**Comment by HuangJunJie2017** [comment]
@haiphamcse done
https://drive.google.com/drive/folders/1JMEla_XRpbsPTXMogcZ6xC6lVm51bgFf?usp=sharing
