### ISSUE TITLE
how can bevdet save and load previous bev features?

### ISSUE THREAD

**Issue by Surtr07** [HuangJunJie2017/BEVDet#246]
I try to recreate temporal module of bevdet4d,but I do not know how to save the previous features as the input of fuction "extract_img_feat_sequential"

**Comment by HuangJunJie2017** [comment]
@Surtr07  please refer to the following script for how to run the bevdet4d in sequence.
https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/tools/analysis_tools/benchmark_sequential.py
