### ISSUE TITLE
bevpoolv2的耗时和显存问题

### ISSUE THREAD

**Issue by xn1997** [HuangJunJie2017/BEVDet#248]
我用v2替换为v1后，显存和耗时都有所增加，而不是论文里说的都大幅降低，这是因为什么呢，难道是没把accelerate置为true的原因吗？

**Comment by HuangJunJie2017** [comment]
@xn1997 Please refer to the instruction in README.md for how to benchmark the view transformer with the following script:
https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/tools/analysis_tools/benchmark_view_transformer.py

btw, accelerate is set to True in this script by default.

**Comment by xn1997** [comment]
> @xn1997 Please refer to the instruction in README.md for how to benchmark the view transformer with the following script: https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/tools/analysis_tools/benchmark_view_transformer.py
> 
> btw, accelerate is set to True in this script by default.

理论上即便不使用accelerate，v2也应该比v1节省很多显存和计算的对吧？

**Comment by xn1997** [comment]
> @xn1997 Please refer to the instruction in README.md for how to benchmark the view transformer with the following script: https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/tools/analysis_tools/benchmark_view_transformer.py
> 
> btw, accelerate is set to True in this script by default.

```python
start_mem_allocated = torch.cuda.memory_allocated()

bevpoolv1/v2...

end_max_mem_allocated = torch.cuda.memory_allocated()
peak_memory_allocated = \
    end_max_mem_allocated - start_mem_allocated
total_memory_requirement = peak_memory_allocated
print('Memory analysis: \n'
      'Memory requirement : %d B / %.01f MB \n' %
      (total_memory_requirement,
       total_memory_requirement / 1024 / 1024))
```
 在代码的bevpool上下添加这个代码，发现v1和v2的输出一样，就几M的样子，都很小，感觉不大合理
@HuangJunJie2017

**Comment by WenxuanLi-whu** [comment]
> > @xn1997 Please refer to the instruction in README.md for how to benchmark the view transformer with the following script: https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/tools/analysis_tools/benchmark_view_transformer.py
> > btw, accelerate is set to True in this script by default.
> 
> 理论上即便不使用accelerate，v2也应该比v1节省很多显存和计算的对吧？

只是节省显存，计算时间反而变多了，z轴一样的配置
