### ISSUE TITLE
关于大模型BEVDet-base训练显存

### ISSUE THREAD

**Issue by WangJian981002** [HuangJunJie2017/BEVDet#249]
您好！
    请问在训练以下模型时，大概需要占用多少显存，同时训练时长约为多久？在论文中提到bs=64 on 8*RTX3090， 可是我在在训练bevdet-tiny （256*704， swin-t）时每张3090只能放到4
![image](https://github.com/HuangJunJie2017/BEVDet/assets/56680663/171d365a-5918-49f8-8059-a65880b391e8)

**Comment by WangJian981002** [comment]
同时还想请教如果将centerhead替换成tranfusion head是否对最终性能有帮助

**Comment by HuangJunJie2017** [comment]
@WangJian981002 
1. I use batch=2 and 32 3090 GPU for the Swin-base config. please refer to the config/log of  this for an example
![image](https://github.com/HuangJunJie2017/BEVDet/assets/31001081/bcad926d-0198-4190-81dd-5754ceaae5bd)
2. I haven't tried the transfusion head.
