### ISSUE TITLE
I found the gt_bbox sending to the forward_train function is flipped compared to the gt_bbox in the outputs of csgbdatasets. Where is the code for the flip above.

### ISSUE THREAD

**Issue by drilistbox** [HuangJunJie2017/BEVDet#25]

**Comment by HuangJunJie2017** [comment]
@drilistbox class RandomFlip3D(RandomFlip):here

**Comment by ruolinsss** [comment]
> @drilistbox [class RandomFlip3D(RandomFlip):here](https://github.com/HuangJunJie2017/BEVDet/blob/f0647e7be73d7525bbe449fb29239f8623bdec0e/mmdet3d/datasets/pipelines/transforms_3d.py#L68)

Hi, I guess it's not that part. The output of the CSGBdatasets has already passes all "train_pipeline" including randomflip. But the gt_bbox in the output (dict with 4 keys: img_metas, img_inputs, gt_bbox and gt_labels) is different with the gt_bbox used in forward_train function in bevdet.py.  Are there any more code modifying gt_bbox after dataloader and before the loss input? Or did I make mistake?

**Comment by HuangJunJie2017** [comment]
@ruolinsss set workers_per_gpu=0 in config files before debugging.

**Comment by ruolinsss** [comment]
I have already set workers=0 and tried to print `self.dataset[ori_idx]['gt_bboxes_3d']` and `self.dataset[ori_idx]['gt_labels_3d']` in get_item in mmdet3d/datasets/dataset_wrappers.py and `gt_bboxes_3d` and `gt_labels_3d` in forward_train function in mmdet3d/models/detectors/bevdet.py. 

While the labels are the same, the gt bbox are different. I wonder where is the code modifying the gt bbox after dataset wrapper and before forward_train. Thanks a lot!
![2022-06-20 14-47-06屏幕截图](https://user-images.githubusercontent.com/38402213/174542650-79a72e71-df6a-4f6a-af1f-a210d06546e9.png)

**Comment by HuangJunJie2017** [comment]
@ruolinsss Set samples_per_gpu=1. The gt_bboxes_3d after ObjectNameFilter is exactly the same as the input of BEVDet.
![image](https://user-images.githubusercontent.com/31001081/174545108-0e2139a4-4e58-4b4e-ae1d-2f505fe8b3d3.png)
![image](https://user-images.githubusercontent.com/31001081/174545272-bd9f33da-eefe-4515-9482-02caadbf169c.png)

**Comment by ruolinsss** [comment]
> @ruolinsss Set samples_per_gpu=1. The gt_bboxes_3d after ObjectNameFilter is exactly the same as the input of BEVDet. ![image](https://user-images.githubusercontent.com/31001081/174545108-0e2139a4-4e58-4b4e-ae1d-2f505fe8b3d3.png) ![image](https://user-images.githubusercontent.com/31001081/174545272-bd9f33da-eefe-4515-9482-02caadbf169c.png)

I see, thanks!
