### ISSUE TITLE
A800 low speed

### ISSUE THREAD

**Issue by zhangzaibin** [HuangJunJie2017/BEVDet#250]

**Comment by zhangzaibin** [comment]
你好，非常感谢您的工作和代码。我之前用8卡3090训练速度正常，当我在8块a800显卡上跑的时候速度非常慢（a800和a100参数差不多）训练bevdet-depth-4d-r101-1408x512需要20天的时间，我分析可能是a800全精度速度不行，请问你们有相关的尝试和解决办法吗？

**Comment by HuangJunJie2017** [comment]
@zhangzaibin all exp in this project are trained on 3090 and I don't have any experience other than 3090.

**Comment by zhangzaibin** [comment]
非常感谢！！！
