### ISSUE TITLE
Occupancy visualization error

### ISSUE THREAD

**Issue by OliverZhu4** [HuangJunJie2017/BEVDet#253]
Hi Junjie! I'm trying to run the visualization code you provided to for the occupancy prediction task using the downloaded pretrained model by "python tools/test.py configs/bevdet_occ/bevdet-occ-stbase-4d-stereo-512x1408-24e.py bevdet-occ-stbase-4d-stereo-512x1408-24e.pth --format-only --eval-options jsonfile_prefix=result/". But it's giving:" IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices" and it looks like the det[] ndarray is not for occ result visualization. Are there any settings that I'm not using correctly? Or occupancy label visualization is not supported yet.

**Comment by Liz66666** [comment]
@OliverZhu4 Hello, I have also encountered the same problem. Could you please tell me how you resolved it?

<img width="872" height="342" alt="Image" src="https://github.com/user-attachments/assets/0e18e7ed-55ad-44f1-af77-7195cf5ba6dd" />
