### ISSUE TITLE
推理结果投影至图片后，框有错位现象

### ISSUE THREAD

**Issue by BadNaive** [HuangJunJie2017/BEVDet#257]
您好！请教一个问题：
我在nuscenes数据集上进行推理，推理过程中使用了--format-only生成了结果的json文件
读取json文件中的预测框数据（看起来应该是global坐标系的）后，转到ego再转到cam，利用内参进行投影，结果如图：
![result (2)](https://github.com/HuangJunJie2017/BEVDet/assets/38786117/94ecfb87-88b7-4dee-82b6-2ea7129cb4f6)
用的内外参都来自于和推理结果相同的token下，请问是哪里出现了问题？

**Comment by HuangJunJie2017** [comment]
https://github.com/HuangJunJie2017/BEVDet/blob/f71858d02eb0fbd09860150ade67558d7984b1be/mmdet3d/datasets/nuscenes_dataset.py#LL375C17-L375C23 
center here is not the gravity center of the object. It is bottom center instead.  I will fix this soon.
