### ISSUE TITLE
Discussions of Adding Radar data in BEVDet

### ISSUE THREAD

**Issue by cyn-liu** [HuangJunJie2017/BEVDet#262]
I concatenated  RADAR data and the BEV features output by LSS  according to dimension, but **the mAP decreased by 2-3 points.**

Does anyone know why?

**Comment by michbaum** [comment]
Hi, 

we actually try to do a very similar thing at the moment, but we also did not manage to successfully utilize the radar data yet - how exactly did you handle the bda augment step in your implementation? Just exactly the same way as LiDAR is handled?

In the meantime, we tried to work with the already implemented LiDAR data as a proxy, and there we also encountered the problem that the mAP is not increasing as expected (or even decreasing).
Our main hypothesis so far is that the data augmentation steps are not done consistently over the image & point cloud data (some visualization points to this). Might you have a config file that handles the augmentation for the different modalities jointly in some way?

One thing that could also be problematic in your case is the coordinate system. As we understood it, all the features in BEVDet are considered in the LiDAR coordinate system, so you might have to transform into that one and not the ego coordinate system (which I think is the IMU? Not 100% sure here). 

Best regards,
Michael

**Comment by cyn-liu** [comment]
> we actually try to do a very similar thing at the moment, but we also did not manage to successfully utilize the radar data yet - how exactly did you handle the bda augment step in your implementation? Just exactly the same way as LiDAR is handled?
> 
Due to BEVDet perform bda augment to view-cone points, so I performed the same bda augmentation on radar data.

> In the meantime, we tried to work with the already implemented LiDAR data as a proxy, and there we also encountered the problem that the mAP is not increasing as expected (or even decreasing). Our main hypothesis so far is that the data augmentation steps are not done consistently over the image & point cloud data (some visualization points to this). Might you have a config file that handles the augmentation for the different modalities jointly in some way?
> 
Yes, I create an module after LSS to concatenate RGB-BEV feature and rasterisation Radar data.

> One thing that could also be problematic in your case is the coordinate system. As we understood it, all the features in BEVDet are considered in the LiDAR coordinate system, so you might have to transform into that one and not the ego coordinate system (which I think is the IMU? Not 100% sure here).
> 
As far as I know, BEVDet is based on the ego coordinate system, not the Lidar_Top coordinate system.

**Comment by cyn-liu** [comment]
> we actually try to do a very similar thing at the moment, but we also did not manage to successfully utilize the radar data yet - how exactly did you handle the bda augment step in your implementation? Just exactly the same way as LiDAR is handled?
> 
Due to BEVDet perform bda augment to view-cone points, so I performed the same bda augmentation on radar data.

> In the meantime, we tried to work with the already implemented LiDAR data as a proxy, and there we also encountered the problem that the mAP is not increasing as expected (or even decreasing). Our main hypothesis so far is that the data augmentation steps are not done consistently over the image & point cloud data (some visualization points to this). Might you have a config file that handles the augmentation for the different modalities jointly in some way?
> 
Yes, I create an module after LSS to concatenate RGB-BEV feature and rasterisation Radar data.

> One thing that could also be problematic in your case is the coordinate system. As we understood it, all the features in BEVDet are considered in the LiDAR coordinate system, so you might have to transform into that one and not the ego coordinate system (which I think is the IMU? Not 100% sure here).
> 
As far as I know, BEVDet is based on the ego coordinate system, not the Lidar_Top coordinate system.

**Comment by kangxiao18** [comment]
Why don't you guys try with nuScenes's projects that using Camera&Radar together?
https://www.nuscenes.org/object-detection?externalData=no&mapData=no&modalities=Camera%2C%20Radar

**Comment by cyn-liu** [comment]
> Why don't you guys try with nuScenes's projects that using Camera&Radar together? https://www.nuscenes.org/object-detection?externalData=no&mapData=no&modalities=Camera%2C%20Radar

Thanks for your reply.
Do you know the source code of the nuScenes's projects?

**Comment by michbaum** [comment]
Mainly for the augmentation strategies and their benefit shown here and the rather extendable codebase. And honestly, we did not realise that radar loading was not supported at all until we already put in significant effort into the codebase. We also didn't find another competitive project that had a clean open-sourced code base.

Regarding the coordinate system, I didn't mean the Lidar_top frame (or I don't know if it is the same), rather their 'LIDAR' coord type that they use to express the 3D bounding boxes for example [here](https://github.com/HuangJunJie2017/BEVDet/blob/f71858d02eb0fbd09860150ade67558d7984b1be/mmdet3d/datasets/nuscenes_dataset.py#L42) or when loading the lidar points [here](https://github.com/HuangJunJie2017/BEVDet/blob/f71858d02eb0fbd09860150ade67558d7984b1be/configs/bevdet/bevdet-r50.py#L198).
If you look at the view transformer used to transform the 2D image features to BEV, they seem to be transformed to these lidar coordinates as well [here](https://github.com/HuangJunJie2017/BEVDet/blob/f71858d02eb0fbd09860150ade67558d7984b1be/mmdet3d/models/necks/view_transformer.py#L286).
But it's entirely possible that this is the ego coordinate system.

**Comment by ciwei123** [comment]
@cyn-liu Hi， I have the same problem, did you find the reason? 

> I concatenated RADAR data and the BEV features output by LSS according to dimension, but **the mAP decreased by 2-3 points.**
> 
> Does anyone know why?

**Comment by cyn-liu** [comment]
@ciwei123 
I don't know the reason yet.
Perhaps we need to check our code to ensure that the logic is reasonable.
