### ISSUE TITLE
KeyError: 'BEVDet4DTRT is not in the models registry'？

### ISSUE THREAD

**Issue by kangxiao18** [HuangJunJie2017/BEVDet#263]
作者您好，请问2.1版本中下列模型哪个可以转换到trt，可以列个list吗？
bevdet-r50
bevdet-r50-4d-cbgs
bevdet-r50-4d-depth-cbgs
bevdet-r50-4dlongterm-cbgs
bevdet-r50-4dlongterm-depth-cbgs
bevdet-r50-4dlongterm-stereo-cbgs
bevdet-r50-4d-stereo-cbgs
bevdet-r50-cbgs
bevdet-stbase-4d-stereo-512x1408-cbgs

我在测试的过程中bevdet-r50试过可以转换成功；
转换bevdet-stbase-4d-stereo-512x1408-cbgs时，报KeyError: 'BEVStereo4DTRT is not in the models registry'错误；
转换bevdet-r50-4dlongterm-cbgs时，报KeyError: 'BEVDet4DTRT is not in the models registry'错误；
我的转换命令为：python tools/convert_bevdet_to_TRT.py $config configs/bevdet/bevdet-r50-4dlongterm-cbgs.py $checkpoint ckpts/bevdet-r50-4dlongterm-cbgs.pth $work_dir ./output_trt/ --fuse-conv-bn --fp16 --int8

**Comment by HuangJunJie2017** [comment]
@kangxiao18 With respect to TensorRT inference, BEVStereo4D is not supported so far.
