### ISSUE TITLE
关于nuScenes数据集，Val集结果与Test集结果的问题

### ISSUE THREAD

**Issue by LCH1238** [HuangJunJie2017/BEVDet#268]
你好，受到BEVDet的启发，我们做了一些工作，也做了实验。但是提交到Eval服务器，在Test集的结果却和Val集差不多。但看BEV方面的论文里，同一个模型，Test集效果好像比Val集高很多，高六七个点以上，请问这是模型出问题了吗？还是Test集某些参数需要设置的与val集不同？

**Comment by jike5** [comment]
> 你好，受到BEVDet的启发，我们做了一些工作，也做了实验。但是提交到Eval服务器，在Test集的结果却和Val集差不多。但看BEV方面的论文里，同一个模型，Test集效果好像比Val集高很多，高六七个点以上，请问这是模型出问题了吗？还是Test集某些参数需要设置的与val集不同？

您好，我看bevformer论文里给的数据，同一个backbone同一个模型也是test比val高，貌似确实蛮奇怪的

**Comment by Gigalomanicx** [comment]
> 你好，受到BEVDet的启发，我们做了一些工作，也做了实验。但是提交到Eval服务器，在Test集的结果却和Val集差不多。但看BEV方面的论文里，同一个模型，Test集效果好像比Val集高很多，高六七个点以上，请问这是模型出问题了吗？还是Test集某些参数需要设置的与val集不同？

您好，我目前也在BEVDet之上进行一些工作，请问您是如何生成Test集的result_nusc.json的，我这边在执行`python tools/test.py $configs $checkpoint --eval-options jsonfile_prefix=work_dirs/results_test --format-only`时遇到了这个错误。
![image](https://github.com/HuangJunJie2017/BEVDet/assets/109480200/c9eefede-5e1e-480d-a8c7-8c284026b480)
请问您是怎么生成并提交的呢？

**Comment by x1370161679** [comment]
> 你好，受到BEVDet的启发，我们做了一些工作，也做了实验。但是提交到Eval服务器，在Test集的结果却和Val集差不多。但看BEV方面的论文里，同一个模型，Test集效果好像比Val集高很多，高六七个点以上，请问这是模型出问题了吗？还是Test集某些参数需要设置的与val集不同？
你好，我也很疑惑，这是什么原因啊，我看很多相关工作都是这样子

**Comment by ZJUnewer** [comment]
请问这个问题解决了吗，我也遇到了相同的情况，比较疑惑，测试集测试是做了什么改动吗

**Comment by Gigalomanicx** [comment]
> 请问这个问题解决了吗，我也遇到了相同的情况，比较疑惑，测试集测试是做了什么改动吗

在跑最终测试集结果打榜时，会额外加入验证集的数据进行训练。也就是相较于仅跑训练集，额外多了150个场景数据样本（约增加20%），测试集上的性能提升应该是这样带来的。改train config里面的 ann_file，添加val集的pkl就行。
![image](https://github.com/user-attachments/assets/57bec63b-704d-4550-a9f9-526ca9aa8d72)

**Comment by Da1symeeting1** [comment]
@Gigalomanicx  你好，可以发一下这个截图的链接吗，感谢
