### ISSUE TITLE
lidar坐标到bev空间转换疑问

### ISSUE THREAD

**Issue by ycdhqzhiai** [HuangJunJie2017/BEVDet#269]
@HuangJunJie2017  请教下，关于lidar点到bev空间的转换问题，代码里面lidar (point + 51.2) /0.8是什么物理意义啊，坐标系右移 / 0.8就是bev空间坐标吗
https://github.com/HuangJunJie2017/BEVDet/blob/f71858d02eb0fbd09860150ade67558d7984b1be/mmdet3d/models/necks/view_transformer.py#L225

**Comment by LCH1238** [comment]
0.8是步长，就是格子的边长，-51.2是起始点。这行代码是将坐标从3D ego 坐标系转换到BEV格子坐标系

**Comment by loserhou** [comment]
> 0.8是步长，就是格子的边长，-51.2是起始点。这行代码是将坐标从3D ego 坐标系转换到BEV格子坐标系

您好，请问LSS为什么不是转到lidar坐标系而是ego坐标系呢，希望您解答
