### ISSUE TITLE
Problem when testing

### ISSUE THREAD

**Issue by galaxyGGG** [HuangJunJie2017/BEVDet#27]
I prepared the environment and nuscenes dataset according to the guide. However, when running test.py, I met this problem.
Would please help me find what is wrong?THANKS!
![mmexport1655775464456](https://user-images.githubusercontent.com/45815385/174698351-b4b00b49-d952-42d3-b6b4-a51b4d6c2ca7.png)

**Comment by Jumponthemoon** [comment]
Did you fix it and how?
