### ISSUE TITLE
align_after_view_transformation problem

### ISSUE THREAD

**Issue by leslie27ch** [HuangJunJie2017/BEVDet#273]
![图片](https://github.com/HuangJunJie2017/BEVDet/assets/49723499/07c74d60-2be0-4ff6-b9ca-757f64e139d3)
 您好。 sensor2keyego 列表是 pre 和cur 帧 统一到  cur帧camfront_ego的变换矩阵。
当用align_after_view_transformation时，在pre帧输入的 却是： cur帧到cur帧 的camfront_ego变换矩阵。这看起来似乎不合理。
应当在计算bev pre帧时，输入pre帧 到 pre的camfront_ego变换矩阵吧。
感谢回复！~

**Comment by leslie27ch** [comment]
![图片](https://github.com/HuangJunJie2017/BEVDet/assets/49723499/dbaceb47-3271-4ccc-8912-f465b79c3b85)
然后在align_after_view_transformation函数中：
三个红框处， curcam2curego ，precam2curego 怎么能得到： curego2preego ？？ 压根就没有preego。

我想您原本的意思是，如果用align_after_view_transformation，
 在计算bev pre时输入 precam2preego ， 计算cur bev时用 curcam2curego。
然后在lss之后通过 pre ego2cur ego 进行对齐。

而实际代码处，在计算pre bev时，您输入的sensor2keyego[0]是 curcam2curego，这已经完全跟pre cam无关了也不是它的外参。

感谢回复！~

**Comment by HuangJunJie2017** [comment]
> ![图片](https://user-images.githubusercontent.com/49723499/253505955-07c74d60-2be0-4ff6-b9ca-757f64e139d3.png) 您好。 sensor2keyego 列表是 pre 和cur 帧 统一到 cur帧camfront_ego的变换矩阵。 当用align_after_view_transformation时，在pre帧输入的 却是： cur帧到cur帧 的camfront_ego变换矩阵。这看起来似乎不合理。 应当在计算bev pre帧时，输入pre帧 到 pre的camfront_ego变换矩阵吧。 感谢回复！~

因为currcam2currego=prevcam2prevego，相机到自车坐标系标定结果不会随时间变化

**Comment by leslie27ch** [comment]
![253515298-dbaceb47-3271-4ccc-8912-f465b79c3b85](https://github.com/HuangJunJie2017/BEVDet/assets/49723499/b95afc4b-b67c-4d72-a49b-a1b3f7f249d4)

当 currcam2currego=prevcam2prevego。

 l02l1 = c02l0.matmul(torch.inverse(c12l0)) 这句是：  precam2preegp *  （ precam2curego）-1
= precam2preego * curego2precam  结果不是预想的 curego2preego

因此你写反了，应是： torch.inverse(c12l0)).matmul(c02l0)   = curego2precam * precam2preego = curego2precego

所以这实现才性能稍低。
