### ISSUE TITLE
Run mono_det_demo.py problem

### ISSUE THREAD

**Issue by qianchenghao** [HuangJunJie2017/BEVDet#28]
Hi,
I was trying to inference the test data under the demo/data folder using bevdet pretrained model,it shows problem as follow:

`(bevdet) qianch@sv2-px:/mnt/data10/qianch/project/BEVDet$ python demo/mono_det_demo.py demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525.jpg demo/data/nuscenes/n015-2018-07-24-11-22-45+0800__CAM_BACK__1532402927637525_mono3d.coco.json configs/bevdet/bevdet-sttiny.py checkpoints/bevdet4d-sttiny-pure.pth /mnt/data10/qianch/project/BEVDet/mmdet3d/models/backbones/swin.py:622: UserWarning: DeprecationWarning: pretrained is a deprecated, please use "init_cfg" instead
  warnings.warn('DeprecationWarning: pretrained is a deprecated, '
load checkpoint from local path: checkpoints/bevdet4d-sttiny-pure.pth
The model and loaded state dict do not match exactly

size mismatch for img_bev_encoder_backbone.layers.0.0.conv1.weight: copying a param with shape torch.Size([128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 64, 3, 3]).
size mismatch for img_bev_encoder_backbone.layers.0.0.downsample.weight: copying a param with shape torch.Size([128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 64, 3, 3]).
unexpected key in source state_dict: pre_process_net.layers.0.0.conv1.weight, pre_process_net.layers.0.0.bn1.weight, pre_process_net.layers.0.0.bn1.bias, pre_process_net.layers.0.0.bn1.running_mean, pre_process_net.layers.0.0.bn1.running_var, pre_process_net.layers.0.0.bn1.num_batches_tracked, pre_process_net.layers.0.0.conv2.weight, pre_process_net.layers.0.0.bn2.weight, pre_process_net.layers.0.0.bn2.bias, pre_process_net.layers.0.0.bn2.running_mean, pre_process_net.layers.0.0.bn2.running_var, pre_process_net.layers.0.0.bn2.num_batches_tracked, pre_process_net.layers.0.0.downsample.weight, pre_process_net.layers.0.0.downsample.bias, pre_process_net.layers.0.1.conv1.weight, pre_process_net.layers.0.1.bn1.weight, pre_process_net.layers.0.1.bn1.bias, pre_process_net.layers.0.1.bn1.running_mean, pre_process_net.layers.0.1.bn1.running_var, pre_process_net.layers.0.1.bn1.num_batches_tracked, pre_process_net.layers.0.1.conv2.weight, pre_process_net.layers.0.1.bn2.weight, pre_process_net.layers.0.1.bn2.bias, pre_process_net.layers.0.1.bn2.running_mean, pre_process_net.layers.0.1.bn2.running_var, pre_process_net.layers.0.1.bn2.num_batches_tracked

Traceback (most recent call last):
  File "demo/mono_det_demo.py", line 46, in <module>
    main()
  File "demo/mono_det_demo.py", line 31, in main
    model = init_model(args.config, args.checkpoint, device=args.device)
  File "/mnt/data10/qianch/project/BEVDet/mmdet3d/apis/inference.py", line 61, in init_model
    if 'CLASSES' in checkpoint['meta']:
KeyError: 'meta'`

But I used the demo provided by official mmdet3D with fcos configs,it gave the correct result.
Can you help?

**Comment by HuangJunJie2017** [comment]
@qianchenghao 
1. BEVDet is not a monocular 3D objection paradigm. Instead, it is a multi-view paradigm.
2. It seems that you use the bevdet4d-tiny checkpoint with the bevdet-tiny configuration.
3. It seems that an extra demo specific to the BEVDet series is required. I will support this recently.

**Comment by qianchenghao** [comment]
> @qianchenghao
> 
> 1. BEVDet is not a monocular 3D objection paradigm. Instead, it is a multi-view paradigm.
> 2. It seems that you use the bevdet4d-tiny checkpoint with the bevdet-tiny configuration.
> 3. It seems that an extra demo specific to the BEVDet series is required. I will support this recently.

Thanks!
