### ISSUE TITLE
difference between  sensor2keyegos and sensor2egos 

### ISSUE THREAD

**Issue by frkmac3** [HuangJunJie2017/BEVDet#283]
hi, I am checking the code https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/mmdet3d/models/detectors/bevdet.py#L72 , and seems like sensor2keyegos equal to sensor2egos, so why do this step?

**Comment by HuangJunJie2017** [comment]
@frkmac3 they are different since the second frame of a video clip.
