### ISSUE TITLE
dockerfile problem

### ISSUE THREAD

**Issue by PowerDi** [HuangJunJie2017/BEVDet#284]
I see the base source nvcr.io/nvidia/tensorrt:22.07-py3 contains CUDA 11.7. But Arg set CUDA=11.3. So we need 11.7 or 11.3？

**Comment by HuangJunJie2017** [comment]
@PowerDi 11.3 instead. cuda is reinstalled in line 41 
 https://github.com/HuangJunJie2017/BEVDet/blob/f71858d02eb0fbd09860150ade67558d7984b1be/docker/Dockerfile#L41
