### ISSUE TITLE
Confused about the keyego

### ISSUE THREAD

**Issue by tangtaogo** [HuangJunJie2017/BEVDet#285]
Hi,
In the prepare_inputs function (https://github.com/HuangJunJie2017/BEVDet/blob/f71858d02eb0fbd09860150ade67558d7984b1be/mmdet3d/models/detectors/bevdet.py#L69) of BEVDet, the ego corresponding to the first camera is taken as keyego, and the sensor2egos for the other cameras are converted to sensor2keyegos. Since the BEVDet only processes single-frame, why aren't the ego corresponding to several cameras in the same frame the same ego?

**Comment by HuangJunJie2017** [comment]
@tangtaogo 中文？没理解你的问题

**Comment by tangtaogo** [comment]
就是对于bevdet来说，只处理单帧的输入，为什么单帧的6个camera对应的ego坐标系不是同一个，需要转到第一个camera的ego下？

**Comment by HuangJunJie2017** [comment]
@tangtaogo  因为 6 个camera 的时间戳不相同

**Comment by tangtaogo** [comment]
好的，原来是这样啊，谢谢大佬
