### ISSUE TITLE
The problem of inconsistency between the performance of github and the code you announced

### ISSUE THREAD

**Issue by zhenghw111** [HuangJunJie2017/BEVDet#289]
Hello author! Thanks for the great work you do! I found that the performance you announced on GitHub is not consistent with the performance in the code you provided. For example, BEVDet-R50-CBGS has mAP=31.3 on GitHub but only 30.85 in the code, BEVDet-R50-4D-CBGS+align mAP=35.4, but only 31.6 in the code. This doesn't seem reasonable, so what should I use as a criterion?
![image](https://github.com/HuangJunJie2017/BEVDet/assets/108120679/517c0096-b0c6-4a81-ac57-81c27944d203)
[https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/configs/bevdet/bevdet-r50-cbgs.py](url)
[https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/configs/bevdet/bevdet-r50-4d-cbgs.py](url)

**Comment by HuangJunJie2017** [comment]
@zhenghw111 use the performance listed in the config files

**Comment by zhenghw111** [comment]
OK! Thank you for your reply.
