### ISSUE TITLE
max_epochs of bevdet-occ

### ISSUE THREAD

**Issue by Yzichen** [HuangJunJie2017/BEVDet#291]
Why set max_epochs=100 for bevdet-occ, and then stop at the 24th epoch. Why not just set max_epochs=24?

**Comment by HuangJunJie2017** [comment]
@Yzichen 100epoch performs better than 24th~
https://github.com/HuangJunJie2017/BEVDet/blob/dev2.1/configs/bevdet_occ/bevdet-occ-r50-4d-stereo-24e_384704.py
