### ISSUE TITLE
usage of checkpoint

### ISSUE THREAD

**Issue by FANG-MING** [HuangJunJie2017/BEVDet#30]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**
```TypeError: forward() missing 1 required positional argument: 'hw_shape'```

**Reproduction**
1. What command or script did you run?
```with_cp = True``` in swin.

```
torch   == 1.8.1

**Comment by HuangJunJie2017** [comment]
@FANG-MING use checkpoint branch instead?
