### ISSUE TITLE
Config of BEVDet-base

### ISSUE THREAD

**Issue by XuyangBai** [HuangJunJie2017/BEVDet#31]
Hi @HuangJunJie2017 thanks for sharing this wonderful work. Could you please share the config file of BEVDet-base and BEVDet4D-base?

**Comment by HuangJunJie2017** [comment]
@XuyangBai Thanks for you attention! We will release them when time is appropriate.

**Comment by MandyMo** [comment]
大兄弟能不能给个bevdet-base和bevdet4d-base的配置，已经不能容忍想测一下大模型的效果了。

**Comment by MandyMo** [comment]
> @MandyMo Configuration 'Base' is deprecated as it is resource-consumptive. We try to draw the attention of the research community toward a better trade-off between speed and accuracy instead of accuracy alone.

可以发我一个bevdet4d-base的么，我有A100显卡，想测一下效果怎么样。

**Comment by zehuichen123** [comment]
大兄弟 我也有A100 能给个base的config测一测吗
