### ISSUE TITLE
bda shape mismatch

### ISSUE THREAD

**Issue by yutao98** [HuangJunJie2017/BEVDet#312]
When I run
 ```
./tools/dist_test.sh ./configs/bevdet_occ/bevdet-occ-r50-4dlongterm-stereo-24e_384704.py ./bevdet-occ-r50-4dlongterm-stereo_384704-24e.pth 7 --eval miou
```
got
```
RuntimeError: shape '[1, 1, 3, 3]' is invalid for input of size 16
```
https://github.com/HuangJunJie2017/BEVDet/blob/ce387e5f5fdd0b00643d0a2afe70af969543e4e3/mmdet3d/models/necks/view_transformer.py#L747
https://github.com/HuangJunJie2017/BEVDet/blob/ce387e5f5fdd0b00643d0a2afe70af969543e4e3/mmdet3d/datasets/pipelines/loading.py#L1239
And I think these two lines is contradictory, because when I change first line to 
```
bda = bda.view(B, 1, 4, 4).repeat(1, N, 1, 1)
```
I got the same results as you reported.

**Comment by HuangJunJie2017** [comment]
@yutao98 thanks for your comment! you are right and I will fix this soon.
