### ISSUE TITLE
KeyError: "NuScenesDataset: 'LoadAnnotationsBEVDepth is not in the pipeline registry'"

### ISSUE THREAD

**Issue by yang-kuo** [HuangJunJie2017/BEVDet#317]
作者您好，我按照教程进行环境配置和数据集的构建，但是在运行tools.test.py时出现了下面的问题，目前该问题通过各种方法都还没有解决，我想问一下您遇到过这个问题吗，有什么解决方案吗？
  File "/home/yklinux/.conda/envs/bevdet/lib/python3.8/site-packages/mmcv/utils/registry.py", line 74, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "NuScenesDataset: 'LoadAnnotationsBEVDepth is not in the pipeline registry'"
munmap_chunk(): invalid pointer

**Comment by HuangJunJie2017** [comment]
@yang-kuo LoadAnnotationsBEVDepth 这个类在dev3.0里已经被替代，请更新到最新的commit

**Comment by yang-kuo** [comment]
作者您好，我是刚接触BEV感知的，目前跑您的代码出现了一个错误如下，我尝试了很多种方法都没有效果，我想问一下您遇到过吗或者有没有一些见解？
![QQ图片20231221083308](https://github.com/HuangJunJie2017/BEVDet/assets/124995034/8428d185-1aff-4839-80cd-5af288dfe7d6)
我查看一下模型的设备确实是在CPU上，数据是在GPU上，然后我将模型to(device)到GPU上不行，加载模型的位置也改不过来，由遇到过这问题朋友吗，我是在远程服务器上调的。
