### ISSUE TITLE
About the issue of image flipping in image data augmentation

### ISSUE THREAD

**Issue by fengdian8564** [HuangJunJie2017/BEVDet#319]
It is a question about image flipping in image data augmentation.
The question is about the founction named sample_augmentation in 'mmdet3d/datasets/pipelines/loading.py'
I found that adding 180 to rot rather than flipping the image vertically when the vflip is set to True.
Is there any considerations to do that？

Looking forward to your reply

**Comment by HuangJunJie2017** [comment]
@fengdian8564 hflip+rot180=vflip

**Comment by fengdian8564** [comment]
> @fengdian8564 hflip+rot180=vflip

Why not just do hslip and vslip directly？
