### ISSUE TITLE
custom dataset 

### ISSUE THREAD

**Issue by lucianzhong** [HuangJunJie2017/BEVDet#320]
Hi, thanks for this great work.

By given custom dataset's camera intrinsic and extrinsic, is it possible to inference directly without training the model?

Best regards

**Comment by HuangJunJie2017** [comment]
@lucianzhong 
monocular depth estimation is camera intrinsic and extrinsic relative 
if you infer the custom dataset with released models without training,  the depth of predicted targets is incorrect.

**Comment by lucianzhong** [comment]
Thanks for the replay.
