### ISSUE TITLE
关于DAL(arxiv v1)论文Figure 5.配图的疑问

### ISSUE THREAD

**Issue by LCH1238** [HuangJunJie2017/BEVDet#324]
您好，在arxiv v1版的DAL论文中，Figure 5.展示了各个模型推理耗时的比较与各模块的耗时占比。如下图，在右上角图注里橙色为LiDAR分支，黄色为Camera分支，但是在每个模型中，橙色中标的是代表Camera分支模型的参数，黄色标的是代表LiDAR分支模型的参数。请问橙色是代表LiDAR分支还是Camera分支？
![image](https://github.com/HuangJunJie2017/BEVDet/assets/43610172/117c250e-97f0-40f4-9c7a-ac5e556a684b)

**Comment by HuangJunJie2017** [comment]
@LCH1238 图例反了，黄色是lidarbranch

**Comment by LCH1238** [comment]
> @LCH1238 图例反了，黄色是lidarbranch

OK,感谢回复
