### ISSUE TITLE
MMCV mmdet3d version issue

### ISSUE THREAD

**Issue by margokhokhlova** [HuangJunJie2017/BEVDet#33]
With the current docker, there is a problem between versions of the libraries:

Reproduction
```
docker build -t mmdetection3d docker/ --no-cache
```
Then:
```
docker run --gpus all --shm-size=8g -it -v /mnt/nas/experiments/3D_restoration:/mmdetection3d/data mmdetection3d
```
What command or script did you run?
```
python tools/create_data.py nuscenes --root-path ./data/nuscenes --out-dir ./data/nuscenes --extra-tag nuscenes
```

```Traceback (most recent call last):
  File "tools/create_data.py", line 6, in <module>
    from tools.data_converter import kitti_converter as kitti
  File "/mmdetection3d/tools/data_converter/kitti_converter.py", line 9, in <module>
    from mmdet3d.core.bbox import box_np_ops, points_cam2img
  File "/mmdetection3d/mmdet3d/__init__.py", line 5, in <module>
    import mmseg
  File "/opt/conda/lib/python3.7/site-packages/mmseg/__init__.py", line 59, in <module>
    f'MMCV=={mmcv.__version__} is used but incompatible. ' \
AssertionError: MMCV==1.3.8 is used but incompatible. Please install mmcv>=(1, 3, 13, 0, 0, 0), <=(1, 4, 0, 0, 0, 0).
```
However, if I am installing a newer version of MMCV, there is another similar error for a different library.
So far the workarounds found do not help to solve it.

System:
Ubuntu 20.04

**Comment by HuangJunJie2017** [comment]
@margokhokhlova Please refer to the provided log for a feasible list of mmcv/mmdet/mmseg version https://github.com/HuangJunJie2017/BEVDet#main-results

**Comment by margokhokhlova** [comment]
Thank you !
I am not sure to understand the answer, I used the latest version of the docker file provided.
After a day of trying all possible versions, I got something working with:
```
mmcv-full               1.4.0               
mmdet                   2.19.0              
mmdet3d                 0.17.2              /mmdetection3d
mmsegmentation          0.20.0   
```

**Comment by HuangJunJie2017** [comment]
@margokhokhlova - - the version of these modules (I used) has been printed in the released training log. This is what I mean.

**Comment by HuangJunJie2017** [comment]
@margokhokhlova 

TorchVision: 0.10.0
OpenCV: 4.5.4-dev
MMCV: 1.3.13
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.1
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.2+99ad831

**Comment by immarioo** [comment]
cuda11.3 
my env works.
pip install torch==1.12.0 torchvision==0.13.0 torchaudio==0.12.0 --extra-index-url https://download.pytorch.org/whl/cu113
pip install mmcv-full==1.6.0 -f https://download.openmmlab.com/mmcv/dist/cu113/torch1.12/index.html
mim install mmdet
pip install openmim
mim install mmdet
mim install mmsegmentation
cd mmdetection3d/
pip install -e .
