### ISSUE TITLE
RuntimeError: shape '[8, 1, 3, 3]' is invalid for input of size 128

### ISSUE THREAD

**Issue by VincentZ-2020** [HuangJunJie2017/BEVDet#332]
能正常训练bevdet-r50-cbgs.py，但是跑带4D前缀的config均出现以下错误

File "/workspace/project/bevdet/BEVDet/mmdet3d/models/necks/view_transformer.py", line 747, in get_mlp_input
    bda = bda.view(B, 1, 3, 3).repeat(1, N, 1, 1)
RuntimeError: shape '[8, 1, 3, 3]' is invalid for input of size 128

历史issue未发现类似的问题，请看看

**Comment by HuangJunJie2017** [comment]
@VincentZ-2020 fixed with bda = bda.view(B, 1, 4, 4).repeat(1, N, 1, 1) in 
https://github.com/HuangJunJie2017/BEVDet/commit/58c2587a8f89a1927926f0bdb6cde2917c91a9a5
