### ISSUE TITLE
Visualization on output

### ISSUE THREAD

**Issue by Jumponthemoon** [HuangJunJie2017/BEVDet#34]
Hi,
I tried visualize the output on the nuScenes mini dataset and use the command:
python tools/test.py configs/bevdet4d/bevdet4d-sttiny.py checkpoints/bevdet4d-sttiny-pure.pth --eval 'mAP' --eval-options 'show=False' 'out_dir=/xxx/project/BEVDet/result'
The model output the eval metrics,but nothing saved below the result folder.I found it a bit confused to visualize the output,can you help out?

**Comment by HuangJunJie2017** [comment]
@Jumponthemoon  Please refer to this section of introduction for the visualization of the results: https://github.com/HuangJunJie2017/BEVDet#visualize-the-predicted-result-with-open3d

**Comment by Jumponthemoon** [comment]
I tried this with show=False,and it give an empty folder under my show-dir
![image](https://user-images.githubusercontent.com/39290403/177455125-14df028b-1e21-49bb-8515-f6681984711a.png)

**Comment by Jumponthemoon** [comment]
I tried this with --show flag removed,and it still output nothing



> @Jumponthemoon Please refer to this section of introduction for the visualization of the results: https://github.com/HuangJunJie2017/BEVDet#visualize-the-predicted-result-with-open3d

**Comment by HuangJunJie2017** [comment]
@Jumponthemoon .... Why do you try this with --show flag removed? If you remove the --show flag, it indeed should output nothing.

**Comment by Jumponthemoon** [comment]
> @Jumponthemoon .... Why do you try this with --show flag removed? If you remove the --show flag, it indeed should output nothing.

Cause it's on remote server, i don't have a display

**Comment by HuangJunJie2017** [comment]
@Jumponthemoon I suggest you save the intermediate result through the pickle module and visualize it locally. (Build the python environment locally with open3d is enough) Otherwise, you have to build the visualization demo on your own.

**Comment by duohaoxue** [comment]
HI ,I tried visualize the output on the nuScenes  dataset and use the command:
python tools/test.py configs/bevdet/bevdet-sttiny.py  /mnt/sdc/dhx/BEVDet-master/bevdet-sttiny-pure.pth --show --show-dir /mnt/sdc/dhx/BEVDet-master/save

![image](https://user-images.githubusercontent.com/33413603/177533120-4d234578-d955-4e20-93d9-d86a37726de5.png)

**Comment by HuangJunJie2017** [comment]
@duohaoxue  Please git clone the latest BEVDet repo, this error has been fixed in the subsequence commit.

**Comment by duohaoxue** [comment]
Thank you !

**Comment by HuangJunJie2017** [comment]
@Jumponthemoon We have supported visualization remotely. (https://github.com/HuangJunJie2017/BEVDet#visualize-the-predicted-result-with-open3d). I hope this will be helpful for you.
