### ISSUE TITLE
当对训练模型进行可视化的时候，检测框出现错位现象。

### ISSUE THREAD

**Issue by Gigalomanicx** [HuangJunJie2017/BEVDet#347]
没有使用tools/analysis_tools/vis.py，而是直接从result_nusc.json中选取pred_bbox绘制。但是出现了检测框错位现象，检查了很久。
![413893c8a01444035fa5b8fab87b14a7](https://github.com/HuangJunJie2017/BEVDet/assets/109480200/7e80f830-cb39-461e-b5a9-26f8c548defd)
不太确定是因为数据增强还是测试时的'MultiScaleFlipAug3D'。有人遇到过这种情况吗？

**Comment by Gigalomanicx** [comment]
bev下的检测框没有出现错位，配置采用dal-base.py

**Comment by Gigalomanicx** [comment]
![2e409ec2abc739eeab3f613a07180c5](https://github.com/HuangJunJie2017/BEVDet/assets/109480200/f5bf22d2-5959-4d4f-a169-2f3f45fd1348)
附上一个真值可视化与预测可视化的对比。应该不是可视化脚本的问题。

**Comment by Stephanie-Shen324** [comment]
看起来是中心点用错了，一个是gravity center 一个是bottom center

**Comment by Gigalomanicx** [comment]
> 看起来是中心点用错了，一个是gravity center 一个是bottom center

问题已解决，
![image](https://github.com/user-attachments/assets/eeb88f93-73f8-436f-87b9-4b3d85c5f594)

**Comment by dodeokwangyooo** [comment]
大佬代码能借鉴一下学习吗！
