### ISSUE TITLE
dockerfile error

### ISSUE THREAD

**Issue by freshduer** [HuangJunJie2017/BEVDet#349]
pip install onnxruntime-gpu==${ONNXRUNTIME_VERSION} -i https://pypi.tuna.tsinghua.edu.cn/simple
清华源没有1.8的，最低1。10

**Comment by mikehaku** [comment]
I encountered the same problem, possibly because too much time has passed?
我遇到了相同的问题，也许是因为时间过去太久了？
Is there any other available source?
有没有其他可用的源？

**Comment by freshduer** [comment]
> I encountered the same problem, possibly because too much time has passed? 我遇到了相同的问题，也许是因为时间过去太久了？ Is there any other available source? 有没有其他可用的源？

我就用的1.10了，也能跑
