### ISSUE TITLE
train error of bevdet4d-sttiny

### ISSUE THREAD

**Issue by midpushgogo** [HuangJunJie2017/BEVDet#36]
when i use the master branch to train the model on nuscenes:
python tools/train.py configs/bevdet4d/bevdet4d-sttiny.py --work-dir try

some error appear

![image](https://user-images.githubusercontent.com/25641049/177453314-95ed1fd2-fe1a-459d-8409-e9479a967505.png)

**Comment by midpushgogo** [comment]
it seems to work when i change line 314 in master/mmdet3d/models/detectors/mvx_two_stage.py
from   loss_inputs = outs + (gt_bboxes_3d, gt_labels_3d, img_metas)
to  loss_inputs =[gt_bboxes_3d, gt_labels_3d, outs]
is that right ?

**Comment by HuangJunJie2017** [comment]
emmm, plot your environment infos? it seems a bug specific to a specific python version.

**Comment by midpushgogo** [comment]
python 3.8.5
pytorch 1.10.0+cu113
mmcv-full 1.3.8
mmdet 2.14.0
mmseg 0.14.1
mmdet3d 0.17.2

**Comment by HuangJunJie2017** [comment]
I use python 3.7.10 instead. I wonder if you can train CenterPoint without the modification mentioned above? configs/centerpoint/centerpoint_01voxel_second_secfpn_4x8_cyclic_20e_nus.py

**Comment by HuangJunJie2017** [comment]
By the way, python 3.8 is not on the checklist of mmdet3d. https://github.com/HuangJunJie2017/BEVDet/blob/e2f4b40dd7d267a81a0ee1c7453a1229381a6f02/.github/workflows/build.yml#L40 
So it is not recommended to use it for all repos that are built on mmdet3d.

**Comment by midpushgogo** [comment]
when using the bevdet4d-sttiny  ,it use the code behind to compute head loss where located in mmdet3d/models/detectors/mvx_two_stage.py
![image_5](https://user-images.githubusercontent.com/25641049/177471478-27558c15-1e6f-42e1-ad26-30a3090c7bb2.png)
and the self.pts_bbox_head.loss() function refer to mmdet3d/models/dense_heads/centerpoint_head.py  with code
![image_3](https://user-images.githubusercontent.com/25641049/177471952-8bc87018-b503-45d3-a3f2-f91b7a623284.png)
it seems the args can't match between two pictures
