### ISSUE TITLE
Test results of dal-large official evaluation

### ISSUE THREAD

**Issue by muchen2019** [HuangJunJie2017/BEVDet#368]
<img width="589" alt="图3" src="https://github.com/user-attachments/assets/10618dc4-95f1-4bea-b63b-0c681310ce01">
As can be seen in this picture, i try to reproduce the performance of DAL-large provided by author using the dal-large.pth. However, the performance is cannot reach the performance shown in paper. By the way, the performance of dal-large.pth in val is correct. Can author help me solve this problem? May the error in my config or loading.py.

**Comment by nicezzl** [comment]
May I ask how you solved it? I have encountered a similar situation.

**Comment by dodeokwangyooo** [comment]
> <img alt="图3" width="589" src="https://private-user-images.githubusercontent.com/57711333/379667026-10618dc4-95f1-4bea-b63b-0c681310ce01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDM1NTg4OTUsIm5iZiI6MTc0MzU1ODU5NSwicGF0aCI6Ii81NzcxMTMzMy8zNzk2NjcwMjYtMTA2MThkYzQtOTVmMS00YmVhLWI2M2ItMGM2ODEzMTBjZTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwNDAyVDAxNDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyMjk1NmNhYTMzNzcwZWYwZjE4YzkzMWMxNGZjZDkwNTI1NzliMmFjNWFmNjkyZDRjNjU0ZGE0N2Q2ZWE4ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-fRIVtk6NU7IkfcgWCzxmSVjT0EFtdz8a3IxUBiDj-E"> As can be seen in this picture, i try to reproduce the performance of DAL-large provided by author using the dal-large.pth. However, the performance is cannot reach the performance shown in paper. By the way, the performance of dal-large.pth in val is correct. Can author help me solve this problem? May the error in my config or loading.py.

请问一下是怎么在test上验证呢？里面有bda增强需要怎么进行删除呢？
