### ISSUE TITLE
Error on training and testing

### ISSUE THREAD

**Issue by guillemdelgado** [HuangJunJie2017/BEVDet#37]
I have tried running the training and the test within the Docker environment that it is provided in the repo. However in the docker some of the versions were not compatible so I had to change them. Maybe someone had the same error and could give me a hand?

For training I use:
`python tools/train.py configs/bevdet/bevdet-sttiny.py
`
I get then 

> Traceback (most recent call last):
>   File "tools/train.py", line 224, in <module>
>     main()
>   File "tools/train.py", line 183, in main
>     test_cfg=cfg.get('test_cfg'))
>   File "/mmdetection3d/mmdet3d/models/builder.py", line 84, in build_model
>     return build_detector(cfg, train_cfg=train_cfg, test_cfg=test_cfg)
>   File "/mmdetection3d/mmdet3d/models/builder.py", line 58, in build_detector
>     cfg, default_args=dict(train_cfg=train_cfg, test_cfg=test_cfg))
>   File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 212, in build
>     return self.build_func(*args, **kwargs, registry=self)
>   File "/opt/conda/lib/python3.7/site-packages/mmcv/cnn/builder.py", line 27, in build_model_from_cfg
>     return build_from_cfg(cfg, registry, default_args)
>   File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
>     f'{obj_type} is not in the {registry.name} registry')
> KeyError: 'BEVDet is not in the models registry'

For testing I use:
`python tools/test.py configs/bevdet/bevdet-sttiny.py bevdet-sttiny-pure.pth --show --show-dir ./tmp/
`

> I get the following error:
> Traceback (most recent call last):
>   File "tools/test.py", line 226, in <module>
>     main()
>   File "tools/test.py", line 164, in main
>     dataset = build_dataset(cfg.data.test)
>   File "/mmdetection3d/mmdet3d/datasets/builder.py", line 41, in build_dataset
>     dataset = build_from_cfg(cfg, DATASETS, default_args)
>   File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
>     raise type(e)(f'{obj_cls.__name__}: {e}')
> TypeError: NuScenesDataset: __init__() got an unexpected keyword argument 'img_info_prototype'

I am using the following versions:
TorchVision: 0.7.0
OpenCV: 4.6.0
MMCV: 1.3.13
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.2+

**Comment by HuangJunJie2017** [comment]
Do you directly git clone BEVDet or implement BEVDet base on mmdet3d on your own?

**Comment by guillemdelgado** [comment]
> Do you directly git clone BEVDet or implement BEVDet base on mmdet3d on your own?

git clone directly BEVDet

**Comment by HuangJunJie2017** [comment]
use this for training instead?
'./tools/dist_train.sh configs/bevdet/bevdet-sttiny.py 1'

**Comment by guillemdelgado** [comment]
> @guillemdelgado use this for training instead? './tools/dist_train.sh configs/bevdet/bevdet-sttiny.py 1'

No luck either, I get the following error:

> Traceback (most recent call last):
>   File "./tools/train.py", line 17, in <module>
>     from mmdet3d.apis import train_model
>   File "/BEVDet/mmdet3d/apis/__init__.py", line 2, in <module>
>     from .inference import (convert_SyncBN, inference_detector,
>   File "/BEVDet/mmdet3d/apis/inference.py", line 11, in <module>
>     from mmdet3d.core import (Box3DMode, CameraInstance3DBoxes,
>   File "/BEVDet/mmdet3d/core/__init__.py", line 3, in <module>
>     from .bbox import *  # noqa: F401, F403
>   File "/BEVDet/mmdet3d/core/bbox/__init__.py", line 5, in <module>
>     from .iou_calculators import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
>   File "/BEVDet/mmdet3d/core/bbox/iou_calculators/__init__.py", line 2, in <module>
>     from .iou3d_calculator import (AxisAlignedBboxOverlaps3D, BboxOverlaps3D,
>   File "/BEVDet/mmdet3d/core/bbox/iou_calculators/iou3d_calculator.py", line 6, in <module>
>     from ..structures import get_box_type
>   File "/BEVDet/mmdet3d/core/bbox/structures/__init__.py", line 2, in <module>
>     from .base_box3d import BaseInstance3DBoxes
>   File "/BEVDet/mmdet3d/core/bbox/structures/base_box3d.py", line 6, in <module>
>     from mmdet3d.ops.iou3d import iou3d_cuda
>   File "/BEVDet/mmdet3d/ops/__init__.py", line 6, in <module>
>     from .ball_query import ball_query
>   File "/BEVDet/mmdet3d/ops/ball_query/__init__.py", line 1, in <module>
>     from .ball_query import ball_query
>   File "/BEVDet/mmdet3d/ops/ball_query/ball_query.py", line 4, in <module>
>     from . import ball_query_ext
> ImportError: cannot import name 'ball_query_ext' from 'mmdet3d.ops.ball_query' (/BEVDet/mmdet3d/ops/ball_query/__init__.py)

**Comment by HuangJunJie2017** [comment]
@guillemdelgado you haven't prepared the repo before using it.   Just cd BEVDet && python setup.py develop

**Comment by guillemdelgado** [comment]
That was it! Thank you very much. Closing the issue
