### ISSUE TITLE
Logfile for BEVDet

### ISSUE THREAD

**Issue by Divadi** [HuangJunJie2017/BEVDet#38]
Hello, would it be possible to get a google drive mirror for the logfiles? I am unable to access them through the baidu link.

Thank you for your work

**Comment by HuangJunJie2017** [comment]
@Divadi  Sure! You can access them through this link:
https://drive.google.com/drive/folders/1VnJv-dNb6-gkKTq7uC_Q6YsRq_q3NI-t?usp=sharing

**Comment by Divadi** [comment]
Thank you!
