### ISSUE TITLE
Incorporate BEVFusion's BEV Pooling operation into BEVDet

### ISSUE THREAD

**Issue by Divadi** [HuangJunJie2017/BEVDet#39]
Hello, I have been trying to replace BEVDet's QuickCumSum operation with BEVFusion's BEV Pooling operation. 
https://github.com/mit-han-lab/bevfusion/tree/main/mmdet3d/ops/bev_pool

To do so, I simply have replaced 
https://github.com/HuangJunJie2017/BEVDet/blob/e2f4b40dd7d267a81a0ee1c7453a1229381a6f02/mmdet3d/models/necks/view_transformer.py#L164-L169
with
```
x = bev_pool(x, geom_feats, B, self.nx[2], self.nx[0], self.nx[1])
```
Where `bev_pool` is BEVFusion's bev_pool cuda operation.

However, I find that although there is significant speed up, the loss is not decreasing as expected (around 14 at end of epoch 5, while it should be around 9.5).

Looking at the papers, they seem to be equivalent pooling operations, but I was hoping for some guidance in case I missed something.

Thank you!

**Comment by HuangJunJie2017** [comment]
@Divadi Both acceleration modification in BEVDet(https://github.com/HuangJunJie2017/BEVDet#estimate-the-inference-speed-of-bevdet) and BEVFusion should be conducted during testing only. The explanation can be found in technical reports.

**Comment by Divadi** [comment]
Thank you for your prompt response!

I believe I found the relevant section BEVDet:
<img width="848" alt="image" src="https://user-images.githubusercontent.com/17109672/177973613-ddb2a766-a638-4831-923e-6310aa8e6ef0.png">

And for BEVFusion:
<img width="879" alt="image" src="https://user-images.githubusercontent.com/17109672/177973944-91846631-13d6-483b-9068-28b8e56100be.png">

However, it seems like from the technical report in BEVFusion and their codebase, the "interval reduction" cuda operation can be performed during training. Their code https://github.com/mit-han-lab/bevfusion/tree/main/mmdet3d/ops/bev_pool has backward cuda operations defined as well.

Again, I apologize if I missed some details

**Comment by HuangJunJie2017** [comment]
@Divadi I misunderstanding the theory of the acceleration in BEVFusion. And it was confirmed by one of the BEVFusion authors that the acceleration in BEVFusion can be used in training. I will check and support this if it can accelerate the training process.

**Comment by HuangJunJie2017** [comment]
@Divadi 
hi, the problem has been solved and bevpool has been supported in this repo.
the coordinate system definitions of the BEV feature are different in these two repos, so a transpose is required after the bevpool operation.

**Comment by HuangJunJie2017** [comment]
@ruolinsss hi, I have checked the consistency in testing, and there is no performance degeneration. The training consistency is under checking.

**Comment by Divadi** [comment]
@HuangJunJie2017 Thank you for the integration! I had found that there is no inference result change, and training is sped up 2.2 Days -> 1.5 days on 4 GPUs.
However, my original inference results themselves are different from the repository; I'll make another post.

Have you experimented with mixed precision to speed up training? I find that just adding fp16 = dict(loss_scale='dynamic') can reduce another .5 days, but have not completed the training (since I think it would require putting @force_fp32 in some places).
