### ISSUE TITLE
fps question about BEVDet4D-Tiny

### ISSUE THREAD

**Issue by Silmeria112** [HuangJunJie2017/BEVDet#40]
Great piece of work.  I have some question about the fps stated in readme file.  I download the checkpoints and use the commands as below.

# with acceleration
python tools/analysis_tools/benchmark.py configs/bevdet/bevdet-sttiny-accelerated.py $checkpoint
# without acceleration
python tools/analysis_tools/benchmark.py configs/bevdet/bevdet-sttiny.py $checkpoint

For BEVDet4D-tiny, I can only get 3.6FPS on a A100 GPU. For BEVDet-tiny with acceleration, I can only get 12 FPS. Both of these results are lower than the number listed in readme/paper. Any thing I did wrong?

**Comment by HuangJunJie2017** [comment]
@Silmeria112 
1. We use 3090 GPU instead. The inference speed on A100 GPU is not clear. 12FPS is sound OK, as 3090 is more powerful than A100.
2. Testing the inference speed of BEVDet4D has not been supported in this repo. As the calculation of the previous frame feature should not be considered in the current frame. 3.6FPS is sound ok if it is tested without acceleration. 
3. We will support testing the inference speed of BEVDet4D later.

**Comment by Silmeria112** [comment]
Thanks. That's very clear.
