### ISSUE TITLE
Why my self_trained pytorch model is much bigger than your pretrained model?

### ISSUE THREAD

**Issue by cherry-yh** [HuangJunJie2017/BEVDet#42]
Hi, I trained a bevdet model using the config file: configs/bevdet/bevdet-sttiny.py, the checkpoint of each epoch is almost 660M, while your pretrained model 'bevdet-sttiny-pure.pth' is only 214M. 
1) Why my self-trained model is so big? I just use your config file and do not make any changes to the code. 
2) I tried to dump backbone 'swin-transfomer' to ONNX but failed. Do you know how to export swin transformer to ONNX file? 
3) In your paper, the backbone has another choice 'resnet50', 'resnet101', but i can not find config files based on 'resnet' backbone. Where can i find the 'resnet' based config file?

**Comment by HuangJunJie2017** [comment]
There is Something beyond the state_dict in the checkpoint 
I haven’t tried onnx. I think some op in view transformer are not supported in onnx
R50/r101 are under schedule，i am retraining   them recently

**Comment by cherry-yh** [comment]
OK, thanks for your quick reply. 
About question 1, what is the difference between your pretrained model and my self-trained model? Could you please give me some detailed info?

**Comment by HuangJunJie2017** [comment]
you can look into your .pth file by 

'
cp = torch.load($path to file)
print([key for key in cp])
'
