### ISSUE TITLE
About View Transformer

### ISSUE THREAD

**Issue by thom966** [HuangJunJie2017/BEVDet#44]
Hello, 
Thank you for your amazing work.

I have a question regarding the view transformer module.
So far, I have figured out that it uses nuscenes dataset's `sensor2lidar_rotation` and `sensor2lidar_translation` information, which are stored into `rots` and `trans` variables respectively. 

My question is what would be the corresponing rotation and translation matrix if I want to use KITTI dataset. 
KITTI dataset has following matrices:
P0: camera0 projection matrix after rectification, an 3x4 array

P1: camera1 projection matrix after rectification, an 3x4 array

P2: camera2 projection matrix after rectification, an 3x4 array

P3: camera3 projection matrix after rectification, an 3x4 array

R0_rect: rectifying rotation matrix, an 4x4 array

Tr_velo_to_cam: transformation from Velodyne coordinate to camera coordinate, an 4x4 array

Tr_imu_to_velo: transformation from IMU coordinate to Velodyne coordinate, an 4x4 array }

Which information should I use for `trans` and `rots` variables?

Thank you for your help.

**Comment by HuangJunJie2017** [comment]
@thom966 you have to update two function to support kitti/bevdet:
1. update the get_data_info in kitti_dataset.py like this
![image](https://user-images.githubusercontent.com/31001081/179739419-70020e53-66fb-4211-8e10-07d6fdd9764a.png)
' if self.info_style=='BEVDet':
            camera2lidar = np.linalg.inv(rect @ Trv2c)
            input_dict['img_info']['CAM_FRONT']=dict(data_path = img_filename,
                                                     cam_intrinsic = P2,
                                                     sensor2lidar_rotation= camera2lidar[:3,:3],
                                                     sensor2lidar_translation= camera2lidar[:3,3])
            if not self.test_mode:
                bbox = input_dict['ann_info']['gt_bboxes_3d'].tensor
                bbox = torch.cat([bbox,torch.zeros((bbox.shape[0],2))],dim=-1)
                input_dict['ann_info']['gt_bboxes_3d'] = \
                    LiDARInstance3DBoxes(tensor=bbox,box_dim=bbox.shape[-1],
                                         with_yaw=input_dict['ann_info']['gt_bboxes_3d'].with_yaw)'
2. update the get_geometry()  in view_transformer.py like this
![image](https://user-images.githubusercontent.com/31001081/179740209-38faaac8-79b1-4601-bc25-4ea1f81de1de.png)
' if intrins.shape[3]==4: # for KITTI
            shift = intrins[:,:,:3,3]
            points  = points - shift.view(B,N,1,1,1,3,1)
            intrins = intrins[:,:,:3,:3]'

**Comment by thom966** [comment]
Thank you so much for your reply.

I have modified the two files and tried to modify the config file myself.
However, it complains about `info_style` variable, with the following error message:
 `AttributeError: 'KittiDataset' object has no attribute 'info_style' `

Could you please also provide the config file for KITTI?

Appreciate for your help.

**Comment by HuangJunJie2017** [comment]
@thom966 It is not about the config, you have to init info_style parameter in the KittiDataset like that in nuScenesDataset.
![image](https://user-images.githubusercontent.com/31001081/179913968-d5398a6c-8188-4df7-9fad-fdccb4f8569b.png)

**Comment by thom966** [comment]
Hello, I have one more question.
Since KITTI dataset has only one front view image, the view transformer receives an input as `[B, T, C, H, W]` shape of `T=1`, while original code receives `T=6` for nuscenes dataset.

I am not sure whether the problem caused by `T`, but the BEV feature of KITTI image contains only zero elements like below:
`array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])
`
What should be the correct input shape when training KITTI?

**Comment by HuangJunJie2017** [comment]
@thom966  T=1 is ok for KITTI
