### ISSUE TITLE
TypeError: 'module' object is not callable in view_transformer.py when training bevdet4d-sttiny

### ISSUE THREAD

**Issue by double8fun** [HuangJunJie2017/BEVDet#46]
Hello, thanks for your great work.
I encountered an error training bevdet4d-sttiny:

> TypeError: 'module' object is not callable
        bev_feat = self.img_view_transformer.voxel_pooling(geom, volume)
  File "/ws/BEVDet/mmdet3d/models/necks/view_transformer.py", line 165, in voxel_pooling
        self.nx[1])

I reach out to the code
https://github.com/HuangJunJie2017/BEVDet/blob/196fed98adddf1d8b5989b5eb3028af5067157f2/mmdet3d/models/necks/view_transformer.py#L164 
and it seems that the following modification is needed:

modify:
`final = bev_pool(x, geom_feats, B, self.nx[2], self.nx[0], self.nx[1])`
to
`final = bev_pool.bev_pool(x, geom_feats, B, self.nx[2], self.nx[0], self.nx[1])`

With the modification, training starts without error, but I don't know whether it is right.

my env:

> Python: 3.7.10 (default, Jun  4 2021, 14:48:32) [GCC 7.5.0]
GCC: gcc (GCC) 7.3.0
PyTorch: 1.9.0
TorchVision: 0.10.0
OpenCV: 4.6.0
MMCV: 1.3.13
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 11.1
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.2+196fed9

**Comment by HuangJunJie2017** [comment]
@double8fun That is ok, i will check and fix this soon.

**Comment by HuangJunJie2017** [comment]
Fixed
