### ISSUE TITLE
Questions on how to train and do inference on Waymo perception dataset

### ISSUE THREAD

**Issue by cuiliangxian** [HuangJunJie2017/BEVDet#47]
Hi, Junjie
Thanks for your great work. Sorry to bother you. I have some questions about how to train and do inference on Waymo percaption dataset. I wonder if the code support to do so. If true, do I just need to follow the BEVDet/docs/data_preparation.md, converting Waymo datset into Kitti format and training on it? Or should I modify the exsited code files? Can you give me some detailed instructions?

**Comment by HuangJunJie2017** [comment]
@cuiliangxian Sorry to disappoint you that we haven't had any experience with Waymo so far. We will support it when it is time to~

**Comment by cuiliangxian** [comment]
I see. Thank you a lot!
