### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by CatOneTwo** [HuangJunJie2017/BEVDet#49]
When you resize the image from (900, 1600) into (256, 704), do you need to make the same change on the bounding box ground truth?

**Comment by HuangJunJie2017** [comment]
@CatOneTwo As analyzed in the paper, the two view spaces are isolated. Augmentation conducted in the image view space will have no impact on the targets defined in the BEV.

**Comment by CatOneTwo** [comment]
Thank you, I got it~
