### ISSUE TITLE
modle training details for nuscenes test split

### ISSUE THREAD

**Issue by jianingwangind** [HuangJunJie2017/BEVDet#5]
Hi, could you please share some details regarding to the training for the test split? With Swin-small and an input size 768 x 2112, how can you train the model on 3090? 
Looking forward to your reply.

**Comment by drilistbox** [comment]
> Hi, could you please share some details regarding to the training for the test split? With Swin-small and an input size 768 x 2112, how can you train the model on 3090? Looking forward to your reply.

hi, I am also trying to reproduce the project, can we work together, here is my email: drilistbox@buaa.edu.cn, looking forward for your reply.

**Comment by e9190712** [comment]
I have preliminary results for training nuScenes dataset using lift-splat+SSD, you can discuss with me, here is my email: qq8855669@gmail.com.

**Comment by HuangJunJie2017** [comment]
The code has been released. Hope this can help solving your problem. Thanks for your attention!
