### ISSUE TITLE
Hi, I trained the bevdepth-r50.py without CBGS, and the result turns out to be NDS is 22.61 and mAP is 24.75.  Is this reasonable?

### ISSUE THREAD

**Issue by drilistbox** [HuangJunJie2017/BEVDet#53]
Hi, I trained the bevdepth-r50.py without CBGS, and the result turns out to be NDS is 22.61 and mAP is 24.75. Is this reasonable?

**Comment by HuangJunJie2017** [comment]
@drilistbox I haven't trained this without CBGS. There are something different between our implementation and the official implementation(has released just few day ago). They use freeze the first stage of image view encoder backbone,  SECOND FPN and some other different details~

**Comment by drilistbox** [comment]
Thanks a lot.
