### ISSUE TITLE
How to run this on my own dataset?

### ISSUE THREAD

**Issue by lvxuanxuan123** [HuangJunJie2017/BEVDet#54]
Hi,thanks for sharing code.I want to know how can i inference on my own datasets such as 1 frame from six cameras.

**Comment by HuangJunJie2017** [comment]
@lvxuanxuan123 please refer to docs/tutorials/customize_dataset.md for an example

**Comment by lvxuanxuan123** [comment]
> I think the hole detection consists of three steps:
> First step: test(). This step only need camera intrinsics parameters and six images.
> The next step: format(). This step needs lidar2ego ， ego2global parameters and results from the previous step.
> The final step:visualize(). This step needs global2ego, ego2lidar, lidar2cam, cam_intrinsics to convert the box to the pixel coordinate system.
> And I have changed these parameters, but the results is messed up.
![Screenshot from 2022-08-01 13-23-03](https://user-images.githubusercontent.com/32082480/183025791-341d6903-d3ff-4dcd-b42f-09de1861a7ef.png)

**Comment by HuangJunJie2017** [comment]
@lvxuanxuan123 It seems that is far from normal. The first step needs the camera extrinsic as well

**Comment by lvxuanxuan123** [comment]
> BEVDet is parameter sensitive. if you test without training on your own data

yes, I haven't train on my own dataset, So the key of the question is training on my own dataset?

**Comment by lvxuanxuan123** [comment]
> @lvxuanxuan123 It seems that is far from normal. The first step needs the camera extrinsic as well

I test on nuscenes dataset without camera extrinsic, and it looks well.
![bev-nuscenes](https://user-images.githubusercontent.com/32082480/183033103-210736ee-2293-470f-9472-7e03bb82c162.png)

**Comment by lvxuanxuan123** [comment]
> @lvxuanxuan123 It seems that is far from normal. The first step needs the camera extrinsic as well

thanks very much !!!! I add camera extrinsic parameters in the first step , and it looks better!
![Screenshot from 2022-08-05 16-28-51](https://user-images.githubusercontent.com/32082480/183036869-f6e7c947-8f9e-46ff-8bc8-40b1a1d3787b.png)

**Comment by leslieburke** [comment]
> > @lvxuanxuan123 It seems that is far from normal. The first step needs the camera extrinsic as well
> 
> thanks very much !!!! I add camera extrinsic parameters in the first step , and it looks better! ![Screenshot from 2022-08-05 16-28-51](https://user-images.githubusercontent.com/32082480/183036869-f6e7c947-8f9e-46ff-8bc8-40b1a1d3787b.png)

您好，我也想试着在自己的数据集上训练和测试，能像您请教一下吗？

**Comment by leslieburke** [comment]
@lvxuanxuan123 方便交流一下吗？

**Comment by lvxuanxuan123** [comment]
> @lvxuanxuan123 方便交流一下吗？

要问什么呢？

**Comment by leslieburke** [comment]
@lvxuanxuan123 就想请问一下您是怎么用自己数据跑这个模型的呢？我查了一下资料，现在初步是想转成kitti格式，然后在生成pkl文件，这样可行吗？另外我的数据只有相机没有雷达数据能跑吗？

**Comment by lvxuanxuan123** [comment]
> @lvxuanxuan123 就想请问一下您是怎么用自己数据跑这个模型的呢？我查了一下资料，现在初步是想转成kitti格式，然后在生成pkl文件，这样可行吗？另外我的数据只有相机没有雷达数据能跑吗？

我是自己改了一部分代码，才能跑自己的数据，还要修改配置文件。如果没有激光，应该不能跑吧，因为不管是推理、格式化还是可视化步骤，都需要激光。

**Comment by leslieburke** [comment]
@lvxuanxuan123 方便参考一下您的代码？

**Comment by leslieburke** [comment]
@lvxuanxuan123 您是吧自己的数据集改成nuscenes的格式吗？方便让我看看您的数据集是啥样的吗？

**Comment by chrisyan** [comment]
> > @lvxuanxuan123 就想请问一下您是怎么用自己数据跑这个模型的呢？我查了一下资料，现在初步是想转成kitti格式，然后在生成pkl文件，这样可行吗？另外我的数据只有相机没有雷达数据能跑吗？
> 
> 我是自己改了一部分代码，才能跑自己的数据，还要修改配置文件。如果没有激光，应该不能跑吧，因为不管是推理、格式化还是可视化步骤，都需要激光。

hi, 请问你是在test.py的基础上修改的吗？假设我准备好了同一帧的6张照片和一个lidar数据，如何喂给模型呢？如果能提供一个思路，非常感谢

**Comment by zhszysrh** [comment]
> > @lvxuanxuan123 It seems that is far from normal. The first step needs the camera extrinsic as well
> 
> thanks very much !!!! I add camera extrinsic parameters in the first step , and it looks better! ![Screenshot from 2022-08-05 16-28-51](https://user-images.githubusercontent.com/32082480/183036869-f6e7c947-8f9e-46ff-8bc8-40b1a1d3787b.png)

请问 自己相机的外参矩阵要怎么得到呢
