### ISSUE TITLE
Slow convergence for R50 backbone

### ISSUE THREAD

**Issue by Divadi** [HuangJunJie2017/BEVDet#56]
Hi - I have been doing experiments without CBGS due to computational limitations, and I am finding that ResNet50 backbone, when compared to Swin-T backbone, has slow convergence.

For instance, BEVDet-R50 no-CBGS achieves (mAP/NDS) **0.1687/0.2182** while BEVDet-Swin-T no-CBGS achieves **0.2992/0.3437**
This seems odd to me because their with-CBGS performance does not differ by so much: 0.299/0.377 for R50 and 0.308/0.404 for Swin-T.

Further, when referencing Table 1 from BEVDepth, which starts with a baseline BEVDet setup:
![image](https://user-images.githubusercontent.com/17109672/183224753-a16af1f8-ee61-4601-a4b2-b038d9bfbe35.png)
They achieve 0.282/0.333 with R50 backbone, no CBGS (before they add any of their proposed modules). So I think it should be _possible_ to achieve such faster convergence.

I do notice that some of their settings are different (SECOND-FPN taking all levels of backbone, 2x depth prediction resolution, FP16/EMA, etc). However, I feel that these points should not make such a huge difference. Do you have any thoughts on what might be different?

I would appreciate any guidance, and thank you!

**Comment by HuangJunJie2017** [comment]
@Divadi All differences between BEVDepth and BEVDet may lead to this problem……

**Comment by HuangJunJie2017** [comment]
EMMM, I think that I have found the main reasons:
1. have not used grad_clip for resnet-base configs 
2. use warm-up lr_config
when I change the optimizer of bevdepth4d-r50.py as that in  https://github.com/Megvii-BaseDetection/BEVDepth/blob/main/exps/bev_depth_lss_r50_256x704_128x128_24e_2key_ema.py
just like this without CBGS
`
# Optimizer
optimizer = dict(type='AdamW', lr=2e-4, weight_decay=1e-7)
optimizer_config = dict(grad_clip=dict(max_norm=5, norm_type=2))
lr_config = dict(
    policy='step',
    step=[19, 23])
runner = dict(type='EpochBasedRunner', max_epochs=24)
`

I got a close result as megvii:
mAP: 0.3327
mATE: 0.7254
mASE: 0.2852
mAOE: 0.6970
mAVE: 0.4013
mAAE: 0.2171
NDS: 0.4337
Eval time: 168.5s

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.498   0.550   0.173   0.209   0.518   0.214
truck   0.267   0.765   0.229   0.229   0.350   0.219
bus     0.392   0.693   0.214   0.113   0.700   0.265
trailer 0.133   1.086   0.251   0.556   0.218   0.109
construction_vehicle    0.074   0.947   0.517   1.606   0.119   0.373
pedestrian      0.348   0.765   0.295   0.950   0.577   0.314
motorcycle      0.316   0.722   0.259   1.016   0.551   0.233
bicycle 0.318   0.573   0.267   1.412   0.176   0.010
traffic_cone    0.471   0.573   0.367   nan     nan     nan
barrier 0.511   0.579   0.281   0.182   nan     nan

I will update this repo after I have checked all details~ 
some other details like whether to use shuffle in training are under checking...
