### ISSUE TITLE
Overlapping Bounding Boxes

### ISSUE THREAD

**Issue by huangzhengxiang** [HuangJunJie2017/BEVDet#57]
Hello! Thanks for your great work!
After training your model myself and visualizing the results, I found that the results often contain overlapping bounding boxes. What probably may the problem be? Is it related to erroreous dataset?
Thank you very much if you can  give any responses.

**Comment by HuangJunJie2017** [comment]
@huangzhengxiang The paradigm densely predicts results with different detection scores. You can thread the results according to the detection scores to remove the duplicated results
