### ISSUE TITLE
How to calculate the flops of the bevdet?

### ISSUE THREAD

**Issue by exiawsh** [HuangJunJie2017/BEVDet#58]
Hello! Thanks for the great work! The computation is reported in the paper BevDET4D.  How to calculate in the framework of mmdet3d?

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by HuangJunJie2017** [comment]
@exiawsh We have added guidelines in README.md for this operation.
