### ISSUE TITLE
About BEV Feature

### ISSUE THREAD

**Issue by yonghoson** [HuangJunJie2017/BEVDet#59]
Thanks for your great work.
I have a question regarding the bev feature from the view transformer.
What would be the proper way to visualize the bev feature? 
The shape is `[batch, 64, 128, 128]` and `pyplot` library complains that it needs the channel dimension of 3 or 4.
Any suggestion would be highly appreciated.

**Comment by HuangJunJie2017** [comment]
@yonghoson I have no experience with pyplot.

**Comment by ytwanghaoyu** [comment]
@yonghoson Have you found a way to properly visualize it?
