### ISSUE TITLE
nuscenes

### ISSUE THREAD

**Issue by xuxiaoxxxx** [HuangJunJie2017/BEVDet#61]
How to form the nuscenes_infos_val_4d_interval3.pkl ? According to the prepare_nuscenes_for_bevdet4d.py I can get the nuscenes_infos_train_4d_interval3_max60.pkl and nuscenes_infos_val_4d_interval3_max60.pkl.

**Comment by HuangJunJie2017** [comment]
@xuxiaoxxxx just use nuscenes_infos_val_4d_interval3_max60.pkl. instead
I will fix this soon
