### ISSUE TITLE
What does eval_pipeline do?

### ISSUE THREAD

**Issue by shuowang666** [HuangJunJie2017/BEVDet#63]
When evaluating model on the val dataset, it uses "test_pipline" in the code. So what is the meaning of "eval_pipeline" in evaluation?

**Comment by HuangJunJie2017** [comment]
Eval during training

**Comment by shuowang666** [comment]
val=dict(pipeline=test_pipeline, classes=class_names,
        modality=input_modality, img_info_prototype='bevdet'),
It seems that val dataset uses the "test_pipeline" when eval during training. When I set "valuation = dict(interval=1, pipeline=None)", it still works properly.

**Comment by HuangJunJie2017** [comment]
yes, in most case, test and val can share the same pipeline~

**Comment by shuowang666** [comment]
Therefore, "eval_pipeline" appears in the config file but is not used in BEVDet.  Is that right?

**Comment by HuangJunJie2017** [comment]
yes

**Comment by shuowang666** [comment]
Thank you.
