### ISSUE TITLE
关于view transform结果的可视化

### ISSUE THREAD

**Issue by lilkeker** [HuangJunJie2017/BEVDet#65]
你好，我在看论文的过程中，看到了view transform的可视化，我想问一下这个可视化的结果是在LSS的具体哪一个步骤的结果进行可视化
![image](https://user-images.githubusercontent.com/81810465/185422670-04f1568c-2324-4720-9020-ed2fb49c45ea.png)

**Comment by HuangJunJie2017** [comment]
It is just a figure to show the distribution of the pseudo point cloud. All points are with the same color and without being rendered by the depth distribution and feature. The coordinate of the points can be obtained through  'geom' in https://github.com/HuangJunJie2017/BEVDet/blob/b17b6e85b3243ef2eaf3a05102e333cb4b7e830b/mmdet3d/models/necks/view_transformer.py#L272
