### ISSUE TITLE
知乎移步过来的，NDS差距大

### ISSUE THREAD

**Issue by yukaizhou** [HuangJunJie2017/BEVDet#66]
博主你好，我是在知乎给您留言的NDS差距较大的人，参数设置是和您的提供的完全一致的（比对了您的log日志）。麻烦您看下，期待您的回复。

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 7.9 task/s, elapsed: 763s, ETA:     0s
Formating bboxes of pts_bbox
Start to convert detection format...
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 6019/6019, 85.5 task/s, elapsed: 70s, ETA:     0s
Results writes to /tmp/tmpvx8pyo3x/results/pts_bbox/results_nusc.json
Evaluating bboxes of pts_bbox
mAP: 0.3049                                                                                                                                            
mATE: 0.6782
mASE: 0.7065
mAOE: 1.5475
mAVE: 0.9790
mAAE: 0.2633
NDS: 0.2898
Eval time: 80.9s

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE     AAE
car     0.514   0.530   0.751   1.579   1.109   0.241
truck   0.211   0.701   0.796   1.576   0.922   0.246
bus     0.302   0.741   0.856   1.561   2.341   0.361
trailer 0.122   0.977   0.834   1.537   0.442   0.038
construction_vehicle    0.062   0.885   0.671   1.576   0.104   0.383
pedestrian      0.333   0.744   0.332   1.529   0.878   0.685
motorcycle      0.253   0.740   0.795   1.589   1.691   0.132
bicycle 0.228   0.496   0.813   1.694   0.345   0.020
traffic_cone    0.514   0.509   0.326   nan     nan     nan
barrier 0.510   0.459   0.892   1.286   nan     nan
{'pts_bbox_NuScenes/car_AP_dist_0.5': 0.1689, 'pts_bbox_NuScenes/car_AP_dist_1.0': 0.446, 'pts_bbox_NuScenes/car_AP_dist_2.0': 0.6632, 'pts_bbox_NuScenes/car_AP_dist_4.0': 0.7764, 'pts_bbox_NuScenes/car_trans_err': 0.53, 'pts_bbox_NuScenes/car_scale_err': 0.7509, 'pts_bbox_NuScenes/car_orient_err': 1.5789, 'pts_bbox_NuScenes/car_vel_err': 1.109, 'pts_bbox_NuScenes/car_attr_err': 0.2406, 'pts_bbox_NuScenes/mATE': 0.6782, 'pts_bbox_NuScenes/mASE': 0.7065, 'pts_bbox_NuScenes/mAOE': 1.5475, 'pts_bbox_NuScenes/mAVE': 0.979, 'pts_bbox_NuScenes/mAAE': 0.2633, 'pts_bbox_NuScenes/truck_AP_dist_0.5': 0.0159, 'pts_bbox_NuScenes/truck_AP_dist_1.0': 0.1198, 'pts_bbox_NuScenes/truck_AP_dist_2.0': 0.2919, 'pts_bbox_NuScenes/truck_AP_dist_4.0': 0.4154, 'pts_bbox_NuScenes/truck_trans_err': 0.7015, 'pts_bbox_NuScenes/truck_scale_err': 0.796, 'pts_bbox_NuScenes/truck_orient_err': 1.5765, 'pts_bbox_NuScenes/truck_vel_err': 0.9219, 'pts_bbox_NuScenes/truck_attr_err': 0.2463, 'pts_bbox_NuScenes/construction_vehicle_AP_dist_0.5': 0.0, 'pts_bbox_NuScenes/construction_vehicle_AP_dist_1.0': 0.0144, 'pts_bbox_NuScenes/construction_vehicle_AP_dist_2.0': 0.0882, 'pts_bbox_NuScenes/construction_vehicle_AP_dist_4.0': 0.1474, 'pts_bbox_NuScenes/construction_vehicle_trans_err': 0.8849, 'pts_bbox_NuScenes/construction_vehicle_scale_err': 0.6715, 'pts_bbox_NuScenes/construction_vehicle_orient_err': 1.5763, 'pts_bbox_NuScenes/construction_vehicle_vel_err': 0.1039, 'pts_bbox_NuScenes/construction_vehicle_attr_err': 0.3834, 'pts_bbox_NuScenes/bus_AP_dist_0.5': 0.0279, 'pts_bbox_NuScenes/bus_AP_dist_1.0': 0.1692, 'pts_bbox_NuScenes/bus_AP_dist_2.0': 0.4251, 'pts_bbox_NuScenes/bus_AP_dist_4.0': 0.5864, 'pts_bbox_NuScenes/bus_trans_err': 0.741, 'pts_bbox_NuScenes/bus_scale_err': 0.8558, 'pts_bbox_NuScenes/bus_orient_err': 1.561, 'pts_bbox_NuScenes/bus_vel_err': 2.3411, 'pts_bbox_NuScenes/bus_attr_err': 0.3611, 'pts_bbox_NuScenes/trailer_AP_dist_0.5': 0.0, 'pts_bbox_NuScenes/trailer_AP_dist_1.0': 0.0196, 'pts_bbox_NuScenes/trailer_AP_dist_2.0': 0.1543, 'pts_bbox_NuScenes/trailer_AP_dist_4.0': 0.316, 'pts_bbox_NuScenes/trailer_trans_err': 0.977, 'pts_bbox_NuScenes/trailer_scale_err': 0.8336, 'pts_bbox_NuScenes/trailer_orient_err': 1.5366, 'pts_bbox_NuScenes/trailer_vel_err': 0.4418, 'pts_bbox_NuScenes/trailer_attr_err': 0.0381, 'pts_bbox_NuScenes/barrier_AP_dist_0.5': 0.2141, 'pts_bbox_NuScenes/barrier_AP_dist_1.0': 0.5074, 'pts_bbox_NuScenes/barrier_AP_dist_2.0': 0.6329, 'pts_bbox_NuScenes/barrier_AP_dist_4.0': 0.6858, 'pts_bbox_NuScenes/barrier_trans_err': 0.459, 'pts_bbox_NuScenes/barrier_scale_err': 0.8917, 'pts_bbox_NuScenes/barrier_orient_err': 1.2859, 'pts_bbox_NuScenes/barrier_vel_err': nan, 'pts_bbox_NuScenes/barrier_attr_err': nan, 'pts_bbox_NuScenes/motorcycle_AP_dist_0.5': 0.0415, 'pts_bbox_NuScenes/motorcycle_AP_dist_1.0': 0.1708, 'pts_bbox_NuScenes/motorcycle_AP_dist_2.0': 0.3609, 'pts_bbox_NuScenes/motorcycle_AP_dist_4.0': 0.4373, 'pts_bbox_NuScenes/motorcycle_trans_err': 0.7399, 'pts_bbox_NuScenes/motorcycle_scale_err': 0.7946, 'pts_bbox_NuScenes/motorcycle_orient_err': 1.5891, 'pts_bbox_NuScenes/motorcycle_vel_err': 1.6908, 'pts_bbox_NuScenes/motorcycle_attr_err': 0.1317, 'pts_bbox_NuScenes/bicycle_AP_dist_0.5': 0.0957, 'pts_bbox_NuScenes/bicycle_AP_dist_1.0': 0.2073, 'pts_bbox_NuScenes/bicycle_AP_dist_2.0': 0.2825, 'pts_bbox_NuScenes/bicycle_AP_dist_4.0': 0.3272, 'pts_bbox_NuScenes/bicycle_trans_err': 0.4959, 'pts_bbox_NuScenes/bicycle_scale_err': 0.8127, 'pts_bbox_NuScenes/bicycle_orient_err': 1.6942, 'pts_bbox_NuScenes/bicycle_vel_err': 0.345, 'pts_bbox_NuScenes/bicycle_attr_err': 0.02, 'pts_bbox_NuScenes/pedestrian_AP_dist_0.5': 0.0578, 'pts_bbox_NuScenes/pedestrian_AP_dist_1.0': 0.2455, 'pts_bbox_NuScenes/pedestrian_AP_dist_2.0': 0.441, 'pts_bbox_NuScenes/pedestrian_AP_dist_4.0': 0.5893, 'pts_bbox_NuScenes/pedestrian_trans_err': 0.7444, 'pts_bbox_NuScenes/pedestrian_scale_err': 0.3324, 'pts_bbox_NuScenes/pedestrian_orient_err': 1.5289, 'pts_bbox_NuScenes/pedestrian_vel_err': 0.8784, 'pts_bbox_NuScenes/pedestrian_attr_err': 0.685, 'pts_bbox_NuScenes/traffic_cone_AP_dist_0.5': 0.1956, 'pts_bbox_NuScenes/traffic_cone_AP_dist_1.0': 0.4944, 'pts_bbox_NuScenes/traffic_cone_AP_dist_2.0': 0.6474, 'pts_bbox_NuScenes/traffic_cone_AP_dist_4.0': 0.717, 'pts_bbox_NuScenes/traffic_cone_trans_err': 0.5086, 'pts_bbox_NuScenes/traffic_cone_scale_err': 0.3257, 'pts_bbox_NuScenes/traffic_cone_orient_err': nan, 'pts_bbox_NuScenes/traffic_cone_vel_err': nan, 'pts_bbox_NuScenes/traffic_cone_attr_err': nan, 'pts_bbox_NuScenes/NDS': 0.28977237815128287, 'pts_bbox_NuScenes/mAP': 0.30493887472544595}

**Comment by HuangJunJie2017** [comment]
It seem that you have use another version of mmdet3d to process the dataset. You have to rebuild the nuscenes dataset with the BEVDet code base.

**Comment by yukaizhou** [comment]
非常感谢您的回复。我的数据确实不是依赖您代码里的mmdet3d的版本生成的。我将会实验依赖您的代码里的mmdet3d版本进行数据的重新生成。再次感谢。

**Comment by zjwzcx** [comment]
您好, 您提到需要注意新版mmdet3d版本坐标系定义与nuscenes不同. 请问0.17.2的版本mmdet3d是否一致? 我直接按照BEVDet repo配置环境,再跑BEVDepth的代码, 结果只有:
mATE: 0.6662                                                                                                                                                                                                                                                                       
mASE: 0.7095                                                                                                                                                                                                                                                                       
mAOE: 1.5584                                                                                                                                                                                                                                                                       
mAVE: 1.0366                                                                                                                                                                                                                                                                       
mAAE: 0.2936                                                                                                                             
NDS: 0.2982 
NDS离README中的40.6还有明显差距, 不确定是不是坐标系定义的问题. @HuangJunJie2017

**Comment by eezhang123** [comment]
I have a same problem, I exactly follow your REAMDme start step, but the NDS only 0.36.
Besides, I download your r50 pth ,the NDS 45.7 meets the REAMDme
mAp:0.3196
mATE:0.6989
mASE:0.7097
mAOE:1.5772
mAVE:0.3710
mAAE:0.1953
NDS:0.3623

**Comment by eezhang123** [comment]
> It seem that you have use another version of mmdet3d to process the dataset. You have to rebuild the nuscenes dataset with the BEVDet code base.
I have a same problem, I exactly follow your REAMDme start step, but the NDS only 0.36.
Besides, I download your r50 pth ,the NDS 45.7 meets the REAMDme
mAp:0.3196
mATE:0.6989
mASE:0.7097
mAOE:1.5772
mAVE:0.3710
mAAE:0.1953
NDS:0.3623

**Comment by HuangJunJie2017** [comment]
@eezhang123 the main precision loss is in mASE and mAOE, you should process the dataset with BEVDet code base instead of other version of mmdet3d

**Comment by cdb342** [comment]
> @eezhang123 the main precision loss is in mASE and mAOE, you should process the dataset with BEVDet code base instead of other version of mmdet3d
May I ask about the main differences between using the BEVDet codebase and other versions of MMDet3D for dataset processing? I'm particularly curious about how these differences might affect the precision of mASE and mAOE.
