### ISSUE TITLE
question about retraining bevdet4d-base model of the leaderboard

### ISSUE THREAD

**Issue by midpushgogo** [HuangJunJie2017/BEVDet#68]
hi , i am trying to retrain the bevdet4d-base . I have some questions that I hope you can help me answer
(1) According to the understanding of the paper, bevdet4d change the backbone to swin-transformer-base and rise the resolution of bev to 0.4m*0.4m , am i right?
(2) how to set  the test time augmentation when predicting the test dataset

**Comment by HuangJunJie2017** [comment]
So far, the details of the submitted results are still kept private.
