### ISSUE TITLE
AttributeError: 'LoadMultiViewImageFromFiles_BEVDet' object has no attribute 'camera_model_consistent'

### ISSUE THREAD

**Issue by drilistbox** [HuangJunJie2017/BEVDet#7]
Hi, thanks for your great work!!

But I come up with the error "AttributeError: 'LoadMultiViewImageFromFiles_BEVDet' object has no attribute 'camera_model_consistent'", will you help me to solve this, thanks a lot!!

I have just simply correct the error by setting the "self.camera_model_consistent" to be None as defaultly, is it right for reproducting your great work.

**Comment by HuangJunJie2017** [comment]
You are right, we will fix this and update the code as soon as possible.
