### ISSUE TITLE
Convert rot to SECOND format, in nuscenes_converter.py ？

### ISSUE THREAD

**Issue by Deephome** [HuangJunJie2017/BEVDet#73]
Thank you for your great work, I have two questions:

1) In nuscenes_converter.py,  why do you convert rot to SECOND format? 
2) The following conversion of `rot` is  confused, how the `rot` is defined in nuscenes' Lidar frame and SECOND format, respectively?
```
            # we need to convert rot to SECOND format.
            gt_boxes = np.concatenate([locs, dims, -rots - np.pi / 2], axis=1)
```

**Comment by HuangJunJie2017** [comment]
This is inherited from the official openmmlap:mmdetection3d~

**Comment by Deephome** [comment]
Thank you for your reply. But the newest mmdetection3d version is different:

`
            # we need to convert box size to
            # the format of our lidar coordinate system
            # which is x_size, y_size, z_size (corresponding to l, w, h)

            gt_boxes = np.concatenate([locs, dims[:, [1, 0, 2]], rots], axis=1)
`

**Comment by HuangJunJie2017** [comment]
We did not build BEVDet upon the up-to-date mmdetection3d. Instead, v0.17.2 which is the latest one when we publish the BEVDet paper.

**Comment by Deephome** [comment]
Thank you for your reply. But the newest mmdetection3d version is different:

`
            # we need to convert box size to
            # the format of our lidar coordinate system
            # which is x_size, y_size, z_size (corresponding to l, w, h)

            gt_boxes = np.concatenate([locs, dims[:, [1, 0, 2]], rots], axis=1)
`

**Comment by EcustBoy** [comment]
> We did not build BEVDet upon the up-to-date mmdetection3d. Instead, v0.17.2 which is the latest one when we publish the BEVDet paper.

Hi author~ I also wonder what "rots" means in following code:
`gt_boxes = np.concatenate([locs, dims, -rots - np.pi / 2], axis=1)`
Is "rots" here use Lidar frame in nuscenes as the the coordinate system? If so, I'm confused why such a conversion is being made: 
`rots --> -rots-np.pi / 2`
