### ISSUE TITLE
image flip will influence 3d box yaw angle?

### ISSUE THREAD

**Issue by L1aoXingyu** [HuangJunJie2017/BEVDet#79]
I notice that image horizontal flip is applied to inputs, in this case, the vehicle yaw angle seems to change. But I don't find any modification on 3d box targets in lidar coordinate system. 

I just want to know if this is a bug or if there is something I missed.

**Comment by HuangJunJie2017** [comment]
You are missing the key idea of the BEVDet paper. 
The inverse transformation of the image view data augmentation is conducted on the points before they are transferred into the 3D space.
This makes sure that the image view data augmentation will not impact the spatial relationship between the bev feature and the targets.

**Comment by L1aoXingyu** [comment]
Thanks for your quick reply. I just found that in bevdet config, there is no image flip aug, only 3d flip.

https://github.com/HuangJunJie2017/BEVDet/blob/2919b997c8fb2cb4737fd844200936ef04900d37/configs/bevdet/bevdet-r50.py#L137-L170

**Comment by HuangJunJie2017** [comment]
img view data augmentations are conducted in type LoadMultiViewImageFromFiles_BEVDet

**Comment by L1aoXingyu** [comment]
Thanks for your kind explanation.
