### ISSUE TITLE
TypeError: save_for_backward can only save variables, but argument 1 is of type tuple

### ISSUE THREAD

**Issue by drilistbox** [HuangJunJie2017/BEVDet#8]
Bother again. I encounter the problem of "TypeError: save_for_backward can only save variables, but argument 1 is of type tuple", detailed as blow:
  File "..BEVDet/tools/train_debug.py", line 217, in main
    train_model(
  File "..BEVDet/mmdet3d/apis/train.py", line 28, in train_model
    train_detector(
  File "..BEVDet/.plu/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "..BEVDet/.plu/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "..BEVDet/.plu/mmcv/mmcv/runner/epoch_based_runner.py", line 50, in train
    self.run_iter(data_batch, train_mode=True, **kwargs)
  File "..BEVDet/.plu/mmcv/mmcv/runner/epoch_based_runner.py", line 29, in run_iter
    outputs = self.model.train_step(data_batch, self.optimizer,
  File "..BEVDet/.plu/mmcv/mmcv/parallel/data_parallel.py", line 75, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "..BEVDet/.plu/mmdetection/mmdet/models/detectors/base.py", line 237, in train_step
    losses = self(**data)
  File "/workspace/miniconda3/envs/bevdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "..BEVDet/.plu/mmcv/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "..BEVDet/mmdet3d/models/detectors/base.py", line 59, in forward
    return self.forward_train(**kwargs)
  File "..BEVDet/mmdet3d/models/detectors/bevdet.py", line 85, in forward_train
    img_feats, pts_feats = self.extract_feat(
  File "..BEVDet/mmdet3d/models/detectors/bevdet.py", line 46, in extract_feat
    img_feats = self.extract_img_feat(img, img_metas)
  File "..BEVDet/mmdet3d/models/detectors/bevdet.py", line 39, in extract_img_feat
    x = self.image_encoder(img[0])
  File "..BEVDet/mmdet3d/models/detectors/bevdet.py", line 25, in image_encoder
    x = self.img_backbone(imgs)
  File "/workspace/miniconda3/envs/bevdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "..BEVDet/mmdet3d/models/backbones/swin.py", line 804, in forward
    x, hw_shape, out, out_hw_shape = stage(x, hw_shape)
  File "/workspace/miniconda3/envs/bevdet/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "..BEVDet/mmdet3d/models/backbones/swin.py", line 519, in forward
    x = checkpoint.checkpoint(block, x, hw_shape)
  File "/workspace/miniconda3/envs/bevdet/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 177, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
TypeError: save_for_backward can only save variables, but argument 1 is of type tuple

Will you give some suggestion, thanks a lot.

**Comment by HuangJunJie2017** [comment]
I haven't seen this error before.   set with_cp=False for the img_backbone?

**Comment by drilistbox** [comment]
OK, thanks a lot.

**Comment by drilistbox** [comment]
Thanks for your reply, I'm checking the environment.

**Comment by ganyz** [comment]
> Thanks for your reply, I'm checking the environment.

This issue may make helps. 
https://github.com/pytorch/pytorch/issues/63394

I replace the 
x = checkpoint.checkpoint(block, x, hw_shape)
with 
x = checkpoint.checkpoint(lambda x: block(x, hw_shape), x, preserve_rng_state=True)

**Comment by drilistbox** [comment]
> 

Thanks for your sugestion and I follow your changes, but it seems not work, an error comes as follow:

Traceback (most recent call last):
  File "tools/train.py", line 224, in <module>
    main()
  File "tools/train.py", line 220, in main
    meta=meta)
  File "/projects/bev/BEVDet/mmdet3d/apis/train.py", line 35, in train_model
    meta=meta)
  File "/projects/bev/BEVDet/.plu/mmdetection/mmdet/apis/train.py", line 170, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/projects/bev/BEVDet/.plu/mmcv/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/projects/bev/BEVDet/.plu/mmcv/mmcv/runner/epoch_based_runner.py", line 51, in train
    self.call_hook('after_train_iter')
  File "/projects/bev/BEVDet/.plu/mmcv/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/projects/bev/BEVDet/.plu/mmcv/mmcv/runner/hooks/optimizer.py", line 35, in after_train_iter
    runner.outputs['loss'].backward()
  File "/workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: has_marked_unused_parameters_ INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1587428266983/work/torch/csrc/distributed/c10d/reducer.cpp:327, please report a bug to PyTorch.  (mark_variable_ready at /opt/conda/conda-bld/pytorch_1587428266983/work/torch/csrc/distributed/c10d/reducer.cpp:327)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x4e (0x7f4dc48d4b5e in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10d::Reducer::mark_variable_ready(c10d::Reducer::VariableIndex) + 0x9ba (0x7f4df588f2ea in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: c10d::Reducer::autograd_hook(c10d::Reducer::VariableIndex) + 0x2d0 (0x7f4df588f850 in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x8a389c (0x7f4df588489c in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x60d (0x7f4df21aa42d in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #5: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7f4df21ac2f2 in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #6: torch::autograd::Engine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>) + 0x2b6 (0x7f4df21a7e06 in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #7: torch::autograd::python::PythonEngine::execute_with_graph_task(std::shared_ptr<torch::autograd::GraphTask> const&, std::shared_ptr<torch::autograd::Node>) + 0x3c (0x7f4df54eb96c in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #8: torch::autograd::Engine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x7d9 (0x7f4df21acea9 in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #9: torch::autograd::python::PythonEngine::execute(std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&, std::vector<at::Tensor, std::allocator<at::Tensor> > const&, bool, bool, std::vector<torch::autograd::Edge, std::allocator<torch::autograd::Edge> > const&) + 0x4e (0x7f4df54eb75e in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #10: THPEngine_run_backward(THPEngine*, _object*, _object*) + 0x950 (0x7f4df54ec350 in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #11: _PyMethodDef_RawFastCallKeywords + 0x2c9 (0x56440b042909 in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #12: <unknown function> + 0x191ef8 (0x56440b043ef8 in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #13: _PyEval_EvalFrameDefault + 0x16bb (0x56440b06ac9b in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #14: _PyEval_EvalCodeWithName + 0x33d (0x56440afafccd in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #15: _PyFunction_FastCallKeywords + 0x320 (0x56440afe1570 in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #16: <unknown function> + 0x191de8 (0x56440b043de8 in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #17: _PyEval_EvalFrameDefault + 0x4c8a (0x56440b06e26a in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #18: _PyEval_EvalCodeWithName + 0x33d (0x56440afafccd in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #19: _PyFunction_FastCallDict + 0x35d (0x56440afb113d in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x1f86 (0x56440b06b566 in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #21: _PyEval_EvalCodeWithName + 0x33d (0x56440afafccd in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #22: _PyFunction_FastCallDict + 0x35d (0x56440afb113d in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #23: <unknown function> + 0x185a63 (0x56440b037a63 in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #24: PyObject_CallObject + 0x82 (0x56440b02dcb2 in /workspace/miniconda3/envs/bevdet_env/bin/python)
frame #25: torch::autograd::PyNode::apply(std::vector<at::Tensor, std::allocator<at::Tensor> >&&) + 0x173 (0x7f4df54f3363 in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #26: <unknown function> + 0x2ae8215 (0x7f4df21ae215 in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #27: torch::autograd::Engine::evaluate_function(std::shared_ptr<torch::autograd::GraphTask>&, torch::autograd::Node*, torch::autograd::InputBuffer&) + 0x16f3 (0x7f4df21ab513 in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #28: torch::autograd::Engine::thread_main(std::shared_ptr<torch::autograd::GraphTask> const&, bool) + 0x3d2 (0x7f4df21ac2f2 in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #29: torch::autograd::Engine::thread_init(int) + 0x39 (0x7f4df21a4969 in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_cpu.so)
frame #30: torch::autograd::python::PythonEngine::thread_init(int) + 0x38 (0x7f4df54eb558 in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #31: <unknown function> + 0xcdaa3 (0x7f4df7f47aa3 in /workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/lib/../../../.././libstdc++.so.6)
frame #32: <unknown function> + 0x8609 (0x7f4e16f92609 in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #33: clone + 0x43 (0x7f4e16d53133 in /lib/x86_64-linux-gnu/libc.so.6)

Traceback (most recent call last):
  File "/workspace/miniconda3/envs/bevdet_env/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/workspace/miniconda3/envs/bevdet_env/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 263, in <module>
    main()
  File "/workspace/miniconda3/envs/bevdet_env/lib/python3.7/site-packages/torch/distributed/launch.py", line 259, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/workspace/miniconda3/envs/bevdet_env/bin/python', '-u', 'tools/train.py', '--local_rank=3', 'configs/bevdet/bevdet-sttiny.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by fcjian** [comment]
Same issue. Which version is your PyTorch? @HuangJunJie2017

**Comment by HuangJunJie2017** [comment]
hi @fcjian, here is the summary from training log

sys.platform: linux
Python: 3.7.10 (default, Feb 26 2021, 18:47:35) [GCC 7.3.0]
CUDA available: True
GPU 0,1,2,3: NVIDIA GeForce RTX 3090
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.1.TC455_06.29190527_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_37,code=compute_37
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0
OpenCV: 4.5.4-dev
MMCV: 1.3.13
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.1
MMDetection: 2.14.0
MMSegmentation: 0.14.1
MMDetection3D: 0.17.2+99ad831

**Comment by fcjian** [comment]
@HuangJunJie2017 Thanks a lot. I use PyTorch 1.7.0, and it seems the issue is caused by PyTorch.

**Comment by HuangJunJie2017** [comment]
@fcjian ok，thanks for your message, I will make a notice for this problem in README.md

**Comment by LuckySunnye** [comment]
Hi~ 
I also encountered this problem. My CUDA version is 11.0. Only torch1.7.0 can be found on the pytorch official website(http://download.pytorch.org/whl/torch_stable.html), but no version 1.9.0 can be found.

**Comment by HuangJunJie2017** [comment]
@LuckySunnye Set with_cp=False? or change hw_shape into Variable instance through
`                from torch.autograd import Variable
                x = checkpoint.checkpoint(block, x, Variable(hw_shape))`
in line-519 in mmdet3d/models/backbones/swin.py

**Comment by HuangJunJie2017** [comment]
@LuckySunnye I create a new branch name checkpoint with the aforementioned modification and invite you to check if it is ok.
https://github.com/HuangJunJie2017/BEVDet/tree/checkpoint

**Comment by LuckySunnye** [comment]
Thanks a lot!

**Comment by LuckySunnye** [comment]
I have found a docker image based on cuda11.1, so I can install torch1.9.0 without the above problems.

**Comment by HuangJunJie2017** [comment]
@LuckySunnye ok

> I have found a docker image based on cuda11.1, so I can install torch1.9.0 without the above problems.
