### ISSUE TITLE
Question about the inference speed of BEVDet4D

### ISSUE THREAD

**Issue by exiawsh** [HuangJunJie2017/BEVDet#80]
Hello,
    Thanks for the great work! I have question about the inference speed report in the readme.
    Theoretically, BEVDET4D requires more computation than BEVDET. However, why is the reporting speed the same？

**Comment by HuangJunJie2017** [comment]
@exiawsh We only consider the computation in the current frame and consider the feature from the previous frame as an input of the current frame.
