### ISSUE TITLE
Config about training bevdet without cbgs?

### ISSUE THREAD

**Issue by exiawsh** [HuangJunJie2017/BEVDet#83]
Hello! Thanks for your great work!
Is there a setup for the experiment that does not require CBGS？ Due to limited computing resources, I want to recreate Bevdet results on a small scale setting.

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by wangzhihao-coder** [comment]
I have trained a bevdet-r50 model without CBGS but the performance degrades a lot. The mAP/NDS is **0.2029/0.2483**
I don't know if there's something wrong with my training config.
If you did the same experiment, I would appreciate it if you share your results without CBGS.
