### ISSUE TITLE
Can you upload the fp16 model log？

### ISSUE THREAD

**Issue by venchi012** [HuangJunJie2017/BEVDet#84]

**Comment by venchi012** [comment]
There is no fp16 log in the link page of readme

**Comment by HuangJunJie2017** [comment]
@abing222 logs have been uploaded

**Comment by cyn-liu** [comment]
Where can I find the fp16 log?  I don't find in the `Baidu Netdisk`.

**Comment by cyn-liu** [comment]
Hi @abing222 
Where can I find the fp16 log? 
Look forward your reply.
