### ISSUE TITLE
calculate FLOPs

### ISSUE THREAD

**Issue by bruce1408** [HuangJunJie2017/BEVDet#88]
when i have used get_flops.py file to calculate the FLOPs, 
```
python tools/analysis_tools/get_flops.py configs/bevdet/bevdet-r50.py --shape 256 704
```
FLOPs=176.73G, and i wonder this result is single image or 6 images ? If the result is a single image's FLOPs, then i need to multiply by 6 to get the final result?

**Comment by HuangJunJie2017** [comment]
@bruce1408 It is a result of 6 images

**Comment by bruce1408** [comment]
> @bruce1408 It is a result of 6 images

ok， thx~

**Comment by bruce1408** [comment]
> @bruce1408 It is a result of 6 images

ok，thx~
