### ISSUE TITLE
order of dims in LiDARInstance3DBoxes and size in NuscenesBox

### ISSUE THREAD

**Issue by LigZhong** [HuangJunJie2017/BEVDet#89]
Hello, I found that the conversion from results of LiDARInstance3DBoxes to NuscenesBox did not change the order from lwh to wlh. Is this a problem? @HuangJunJie2017

**Comment by HuangJunJie2017** [comment]
Why the order should be changed from lwh to wlh? We indeed use wlh in training
https://github.com/HuangJunJie2017/BEVDet/blob/2919b997c8fb2cb4737fd844200936ef04900d37/tools/data_converter/nuscenes_converter.py#L231

**Comment by LigZhong** [comment]
D

> Why the order should be changed from lwh to wlh? We indeed use wlh in training
> 
> https://github.com/HuangJunJie2017/BEVDet/blob/2919b997c8fb2cb4737fd844200936ef04900d37/tools/data_converter/nuscenes_converter.py#L231

Do you mean you used coordinate shown in this image? Not the same direction as shown in LidarInstance3Dboxes, where length should correspond to axis X?
<img width="496" alt="image" src="https://user-images.githubusercontent.com/31633173/198962272-eafd4bd9-b68f-45fe-98c7-5fe9766b7d15.png">

**Comment by HuangJunJie2017** [comment]
@LigZhong 
at first, we do not care which dimension corresponds to axis X, They are just some values that need regression in an end-to-end framework.  
besides, the target's dimension should be considered under the target's coordinate system, instead of the ego(lidar) coordinate system you mentioned above.

**Comment by LigZhong** [comment]
> @LigZhong at first, we do not care which dimension corresponds to axis X, They are just some values that need regression in an end-to-end framework. besides, the target's dimension should be considered under the target's coordinate system, instead of the ego(lidar) coordinate system you mentioned above.

Thanks for your reply. May I ask which function did you use to plot the point cloud shown above?

**Comment by HuangJunJie2017** [comment]
@LigZhong I used a private script

**Comment by ytwanghaoyu** [comment]
> > @LigZhong at first, we do not care which dimension corresponds to axis X, They are just some values that need regression in an end-to-end framework. besides, the target's dimension should be considered under the target's coordinate system, instead of the ego(lidar) coordinate system you mentioned above.
> 
> Thanks for your reply. May I ask which function did you use to plot the point cloud shown above?


Just visualize the `geom` from the lss get_geometry() part.
![image](https://user-images.githubusercontent.com/25526912/199480960-95527f11-0937-4a0e-a17d-77549b5a8781.png)
