### ISSUE TITLE
I  have some confusion in reproduce Bev4D with resnet101 config.

### ISSUE THREAD

**Issue by Crownwzt** [HuangJunJie2017/BEVDet#9]
Reference to bevdet4d-sttiny.py, i want to reproduce the setting resnet101 pretrained bu fcos. I change the img size to 928 * 1600, and use the last two feature in fpn fusion, but when batch size only 1 in my device(48G memory),  more than 32G memory has been used. I have already used fp16 in training, but the batch size can only afford 2 in per gpu. Can you  help me to reproduce the 64 batch size in your paper, maybe there are some config error in my config file.

**Comment by HuangJunJie2017** [comment]
I think it is not capable for a 48G device to train models with this configuration. On 32G devices, bevdet4d-base is trained with batch size 2,1600x640 input size.  Besides, torch.utils.checkpoint is used. We use 32 GPUs with SyncBN, which is equivalent to 8 GPUs with batch size 8 per GPU.

**Comment by Crownwzt** [comment]
May i have your WeChat num, i want to reproduce the setting resnet101 pretrained by fcos.
