### ISSUE TITLE
Questions about bad heatmaps results.

### ISSUE THREAD

**Issue by ytwanghaoyu** [HuangJunJie2017/BEVDet#90]
Hi,

First of all, thanks for your excellent work.

I've been trying to reproduce the result in a new implementation (which didn't use any mmlab lib) while keeping the same settings (model structures and input pipelines etc.) as yours. But got a bad result in the heatmap part (also those regression losses, but they are not that bad).

You can check this one, left is gt encode, right is pred:

![image](https://user-images.githubusercontent.com/25526912/199482304-38f5ce58-0e70-4118-8ee6-5434d979e32e.png)

I know it might be difficult to tell which part is wrong, but I wonder if there are any thoughts about what part may cause this problem.

**Comment by Kerwin0621** [comment]
Hi, may I ask how did you generate this heatmap?
