### ISSUE TITLE
What may cause the mAP diff for bevdepth? Thanks !

### ISSUE THREAD

**Issue by clw5180** [HuangJunJie2017/BEVDet#94]
the official bevdepth mAP is 35.89, and this repo is 33.3, how many times have you trained to get 33.3, the result is unstable or not ? thanks.

**Comment by HuangJunJie2017** [comment]
@clw5180 We release a private implementation of BEVDepth instead of the official one, which is made public available after our implementation. Some details of implementation may lead to performance inconsistency.
