### ISSUE TITLE
BEV4D time 

### ISSUE THREAD

**Issue by liwuhen** [HuangJunJie2017/BEVDet#95]
if 'dis' in self.speed_mode: 
      time = abs(input_dict['timestamp'] - 1e-6 * input_dict['adjacent']['timestamp'])
      bbox[:, 7:9] = bbox[:, 7:9] * time

bbox[:, 7:9] = bbox[:, 7:9] * time ， How do you understand this sentence？

**Comment by HuangJunJie2017** [comment]
@liwuhen  predict the offset instead of velocity, offset = velocity *time

**Comment by liwuhen** [comment]
thank you very much for your answer
