### ISSUE TITLE
questions about code implementation

### ISSUE THREAD

**Issue by liwuhen** [HuangJunJie2017/BEVDet#96]
bevdet.py
for img, _ , _, intrin, post_rot, post_tran in zip(imgs, rots, trans, intrins, post_rots, post_trans):
            tran = trans[0] # current frame
            rot  = rots[0]  # current frame
            x = self.image_encoder(img)  # [1, 6, 512, 16, 44]
How to understand the camera extrinsics code has not  changed ； eg:  "tran = trans[0] " and " rot  = rots[0]"

**Comment by HuangJunJie2017** [comment]
@liwuhen The camera extrinsics should be fixed as the spatial relationship between camera and lidar(or ego) is physically fixed.
