### ISSUE TITLE
About the implementation of BEVDepth4D

### ISSUE THREAD

**Issue by lhyakn** [HuangJunJie2017/BEVDet#97]
Thanks for your great work! I noticed that your implementation of BEVDepth4D seems to have some differences from the implementation of their paper in feature alignment. If I understand correctly, they do feature alignment in the view transformation phase. Do I understand correctly?

**Comment by HuangJunJie2017** [comment]
@lhyakn 
yes, as the official BEVDepth implementation has not considered the inference logic that the BEV feature retained from the previous frame haven't been aligned with the current frame.
you can control this through hyper-parameter cfg.model.align_after_view_transfromation in branch dev2.0

**Comment by lilkeker** [comment]
> @lhyakn yes, as the official BEVDepth implementation has not considered the inference logic that the BEV feature retained from the previous frame haven't been aligned with the current frame. you can control this through hyper-parameter cfg.model.align_after_view_transfromation in branch dev2.0

Hi,Junjie，I reproduced bevdet4d-r50-cbgs, and its result is correct. I want to check the bevdet4d-r50-cbgs result of align after viewtransfromation. I set cfg.model.align_after_view_transfromation=true, but the result is still the same as before. Do you know the reason?
![image](https://user-images.githubusercontent.com/81810465/218349446-5c4986fe-ac89-48f9-b5f0-c5ed7dd33977.png)

**Comment by HuangJunJie2017** [comment]
@lilkeker  use 'python tools/test.py $config $checkpoint --eval mAP --no-aavt' instead

**Comment by lilkeker** [comment]
> 

Ok, thanks for the reply, I'll try it
