### ISSUE TITLE
About the results in the new dev2.0 branch

### ISSUE THREAD

**Issue by zw615** [HuangJunJie2017/BEVDet#98]
Thanks for the great work!

I've noticed in the latest commits, the _BEVDet-R50-4D-Depth-CBGS_ achieves a mAP of 40.2/40.6 and NDS of 52.3/52.6, which is significantly better than the result of previous implementation _BEVDepth4D-R50_ (36.1mAP, 48.5NDS). Could you please describe what changes lead to this improvement? The long term temporal fusion as SOLOFusion?

**Comment by HuangJunJie2017** [comment]
@zeyuwang615 all details I listed in news/README.md~

**Comment by zw615** [comment]
Hi, I am reading the new code in dev2.0 branch. It seems to me that the 'the long term temporal fusion as SOLOFusion.' is really implemented by concatenating the features extracted from the previous 1-9 key frames, right? So there is no high-resolution, shot-term temporal fusion as SOLOFusion?

**Comment by HuangJunJie2017** [comment]
Yes
