### ISSUE TITLE
Have you ever considered to use bilinear interpolation in bev pooling ?

### ISSUE THREAD

**Issue by Hale423** [HuangJunJie2017/BEVDet#99]
Hi:
 Thanks for your great work, I've noticed your bev pooling suffers from precision loss when float bev feature idxs are converted to int ones, a better solution would be use bilinear interpolation in bev feature assigning. Here I called the latter method `bev align`,  it's much like what `roi align` is to `roi pooling`,  you can see the [code here](https://github.com/HaohaoNJU/bev_align_plugin)

**Comment by HuangJunJie2017** [comment]
@HaohaoNJU interesting perspective！ have you trained bevdet series with this? How about the precision difference?

**Comment by Hale423** [comment]
Yes， I've trained [bevdet4d](https://github.com/HuangJunJie2017/BEVDet/blob/master/configs/bevdet4d/bevdet4d-r50.py) on our private dataset, with bev align, the ATE/AVE metrics are indeed lower， mAP however doesn't show much difference. I didn't have much time to train on Nuscenes， I would be appreciated if your team want to have a try ~

**Comment by HuangJunJie2017** [comment]
@HaohaoNJU  
It is out of my schedule in the nearby future.
